<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Machine Learning Fundamentals | Projects Repository</title>
  <meta name="description" content="This is a collection of notes to my self" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Machine Learning Fundamentals | Projects Repository" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a collection of notes to my self" />
  <meta name="github-repo" content="davutemrah/davutemrah.github.io" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Machine Learning Fundamentals | Projects Repository" />
  
  <meta name="twitter:description" content="This is a collection of notes to my self" />
  

<meta name="author" content="Davut Ayan" />


<meta name="date" content="2024-02-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="projects.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Machine Learning</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="projects.html"><a href="projects.html"><i class="fa fa-check"></i><b>1</b> Projects</a></li>
<li class="chapter" data-level="2" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html"><i class="fa fa-check"></i><b>2</b> Machine Learning Fundamentals</a>
<ul>
<li class="chapter" data-level="2.1" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#definitions"><i class="fa fa-check"></i><b>2.1</b> definitions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#data-science"><i class="fa fa-check"></i><b>2.1.1</b> Data Science</a></li>
<li class="chapter" data-level="2.1.2" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#bootstrapping"><i class="fa fa-check"></i><b>2.1.2</b> Bootstrapping</a></li>
<li class="chapter" data-level="2.1.3" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#classification-models-evaluation"><i class="fa fa-check"></i><b>2.1.3</b> Classification Models: Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#elastic-net-model"><i class="fa fa-check"></i><b>2.2</b> Elastic Net Model</a></li>
<li class="chapter" data-level="2.3" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#survival-analysis"><i class="fa fa-check"></i><b>2.3</b> Survival Analysis</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#references"><i class="fa fa-check"></i><b>2.3.1</b> References</a></li>
<li class="chapter" data-level="2.3.2" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#time-to-event-analysis"><i class="fa fa-check"></i><b>2.3.2</b> Time to event analysis</a></li>
<li class="chapter" data-level="2.3.3" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#kaplan-meier"><i class="fa fa-check"></i><b>2.3.3</b> Kaplan-Meier</a></li>
<li class="chapter" data-level="2.3.4" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#the-basics-of-survival-analysis"><i class="fa fa-check"></i><b>2.3.4</b> The basics of Survival Analysis</a></li>
<li class="chapter" data-level="2.3.5" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#prosper-loan-data"><i class="fa fa-check"></i><b>2.3.5</b> Prosper Loan data</a></li>
<li class="chapter" data-level="2.3.6" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#customer-churn"><i class="fa fa-check"></i><b>2.3.6</b> Customer Churn</a></li>
<li class="chapter" data-level="2.3.7" data-path="machine-learning-fundamentals.html"><a href="machine-learning-fundamentals.html#deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws"><i class="fa fa-check"></i><b>2.3.7</b> Deploying a Scalable End to End Customer Churn Prediction Solution with AWS</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://davutemrah.github.io/notebooks/" target="blank">Personal Repo Home</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Projects Repository</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="machine-learning-fundamentals" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Machine Learning Fundamentals<a href="machine-learning-fundamentals.html#machine-learning-fundamentals" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="definitions" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> definitions<a href="machine-learning-fundamentals.html#definitions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="data-science" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Data Science<a href="machine-learning-fundamentals.html#data-science" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="what-is-data-science" class="section level4 hasAnchor" number="2.1.1.1">
<h4><span class="header-section-number">2.1.1.1</span> What is data science?<a href="machine-learning-fundamentals.html#what-is-data-science" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>At its core, data science is using data to answer questions. This is a pretty broad definition, and that’s because it’s a pretty broad field!</p>
<p>Data science can involve:</p>
<p>• Statistics, computer science, mathematics
• Data cleaning and formatting
• Data visualization
An Economist Special Report sums up this mélange of skills well - they state that a data scientist is broadly defined as someone:
“who combines the skills of software programmer, statistician and storyteller slash artist to extract the nuggets of gold hidden under mountains of data”
And by the end of these courses, hopefully you will feel equipped to do just that!</p>
</div>
<div id="why-do-we-need-data-science" class="section level4 hasAnchor" number="2.1.1.2">
<h4><span class="header-section-number">2.1.1.2</span> Why do we need data science?<a href="machine-learning-fundamentals.html#why-do-we-need-data-science" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One of the reasons for the rise of data science in recent years is the vast amount of data currently available and being generated. Not only are massive amounts of data being collected about many aspects of the world and our lives, but we simultaneously have the rise of inexpensive computing. This has created the perfect storm in which we have rich data and the tools to analyse it: Rising computer memory capabilities, better processors, more software and now, more data scientists with the skills to put this to use and answer questions using this data!
There is a little anecdote that describes the truly exponential growth of data generation we are experiencing. In the third century BC, the Library of Alexandria was believed to house the sum of human knowledge. Today, there is enough information in the world to give every person alive 320 times as much of it as historians think was stored in Alexandria’s entire collection.
And that is still growing.</p>
</div>
<div id="what-is-big-data" class="section level4 hasAnchor" number="2.1.1.3">
<h4><span class="header-section-number">2.1.1.3</span> What is big data?<a href="machine-learning-fundamentals.html#what-is-big-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>It has been so integral to the rise of data science. There are a few qualities that characterize big data. The first is <code>volume.</code> As the name implies, big data involves large datasets - and these large datasets are becoming more and more routine. For example, say you had a question about online video - well, YouTube has approximately 300 hours of video uploaded every minute! You would definitely have a lot of data available to you to analyse, but you can see how this might be a difficult problem to wrangle all of that data!</p>
<p>And this brings us to the second quality of big data: <code>velocity.</code> Data is being generated and collected faster than ever before. In our YouTube example, new data is coming at you every minute! In a completely different example, say you have a question about shipping times or routes. Well, most transport trucks have real time GPS data available - you could in real time analyse the trucks movements… if you have the tools and skills to do so!</p>
<p>The third quality of big data is <code>variety.</code> In the examples I’ve mentioned so far, you have different types of data available to you. In the YouTube example, you could be analysing video or audio, which is a very unstructured data set, or you could have a database of video lengths, views or comments, which is a much more structured dataset to analyse.</p>
</div>
<div id="descriptive-analysis" class="section level4 hasAnchor" number="2.1.1.4">
<h4><span class="header-section-number">2.1.1.4</span> 1. Descriptive analysis<a href="machine-learning-fundamentals.html#descriptive-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The goal of descriptive analysis is to describe or summarize a set of data. Whenever you get a new dataset to examine, this is usually the first kind of analysis you will perform. Descriptive analysis will generate simple summaries about the samples and their measurements. You may be familiar with common descriptive statistics: measures of central tendency (eg: mean, median, mode) or measures of variability (eg: range, standard deviations or variance).
This type of analysis is aimed at summarizing your sample – not for generalizing the results of the analysis to a larger population or trying to make conclusions. Description of data is separated from making interpretations; generalizations and interpretations require additional statistical steps.
Some examples of purely descriptive analysis can be seen in censuses. Here, the government collects a series of measurements on all of the country’s citizens, which can then be summarized. Here, you are being shown the age distribution in the US, stratified by sex.</p>
</div>
<div id="exploratory-analysis" class="section level4 hasAnchor" number="2.1.1.5">
<h4><span class="header-section-number">2.1.1.5</span> 2. Exploratory analysis<a href="machine-learning-fundamentals.html#exploratory-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The goal of exploratory analysis is to examine or explore the data and find relationships that weren’t previously known. Exploratory analyses explore how different measures might be related to each other but do not confirm that relationship as causitive. You’ve probably heard the phrase “Correlation does not imply causation” and exploratory analyses lie at the root of this saying. Just because you observe a relationship between two variables during exploratory analysis, it does not mean that one necessarily causes the other.
Because of this, exploratory analyses, while useful for discovering new connections, should not be the final say in answering a question! It can allow you to formulate hypotheses and drive the design of future studies and data collection, but exploratory analysis alone should never be used as the final say on why or how data might be related to each other.</p>
</div>
<div id="inferential-analysis" class="section level4 hasAnchor" number="2.1.1.6">
<h4><span class="header-section-number">2.1.1.6</span> 3. Inferential analysis<a href="machine-learning-fundamentals.html#inferential-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The goal of inferential analyses is to use a relatively small sample of data to infer or say something about the population at large. Inferential analysis is commonly the goal of statistical modelling, where you have a small amount of information to extrapolate and generalize that information to a larger group.</p>
<p>Inferential analysis typically involves using the data you have to estimate that value in the population and then give a measure of your uncertainty about your estimate. Since you are moving from a small amount of data and trying to generalize to a larger population, your ability to accurately infer information about the larger population depends heavily on your sampling scheme - if the data you collect is not from a representative sample of the population, the generalizations you infer won’t be accurate for the population.</p>
</div>
<div id="predictive-analysis" class="section level4 hasAnchor" number="2.1.1.7">
<h4><span class="header-section-number">2.1.1.7</span> 4. Predictive analysis<a href="machine-learning-fundamentals.html#predictive-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The goal of predictive analysis is to use current data to make predictions about future data. Essentially, you are using current and historical data to find patterns and predict the likelihood of future outcomes.
Like in inferential analysis, your accuracy in predictions is dependent on measuring the right variables. If you aren’t measuring the right variables to predict an outcome, your predictions aren’t going to be accurate. Additionally, there are many ways to build up prediction models with some being better or worse for specific cases, but in general, having more data and a simple model generally performs well at predicting future outcomes.
All this being said, much like in exploratory analysis, just because one variable may predict another, it does not mean that one causes the other; you are just capitalizing on this observed relationship to predict the second variable.
A common saying is that prediction is hard, especially about the future. There aren’t easy ways to gauge how well you are going to predict an event until that event has come to pass; so evaluating different approaches or models is a challenge.</p>
<p>We spend a lot of time trying to predict things - the upcoming weather, the outcomes of sports events, and in the example we’ll explore here, the outcomes of elections. We’ve previously mentioned Nate Silver of FiveThirtyEight, where they try and predict the outcomes of U.S. elections (and sports matches, too!). Using historical polling data and trends and current polling, FiveThirtyEight builds models to predict the outcomes in the next US Presidential vote - and has been fairly accurate at doing so! FiveThirtyEight’s models accurately predicted the 2008 and 2012 elections and was widely considered an outlier in the 2016 US elections, as it was one of the few models to suggest Donald Trump at having a chance of winning.</p>
</div>
<div id="causal-analysis" class="section level4 hasAnchor" number="2.1.1.8">
<h4><span class="header-section-number">2.1.1.8</span> Causal analysis<a href="machine-learning-fundamentals.html#causal-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The caveat to a lot of the analyses we’ve looked at so far is that we can only see correlations and can’t get at the cause of the relationships we observe. Causal analysis fills that gap; the goal of causal analysis is to see what happens to one variable when we manipulate another variable - looking at the cause and effect of a relationship.
Generally, causal analyses are fairly complicated to do with observed data alone; there will always be questions as to whether it is correlation driving your conclusions or that the assumptions underlying your analysis are valid. More often, causal analyses are applied to the results of randomized studies that were designed to identify causation. Causal analysis is often considered the gold standard in data analysis, and is seen frequently in scientific studies where scientists are trying to identify the cause of a phenomenon, but often getting appropriate data for doing a causal analysis is a challenge.
One thing to note about causal analysis is that the data is usually analysed in aggregate and observed relationships are usually average effects; so, while on average giving a certain population a drug may alleviate the symptoms of a disease, this causal relationship may not hold true for every single affected individual.</p>
</div>
<div id="experimental-design" class="section level4 hasAnchor" number="2.1.1.9">
<h4><span class="header-section-number">2.1.1.9</span> Experimental Design<a href="machine-learning-fundamentals.html#experimental-design" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Now that we’ve looked at the different types of data science questions, we are going to spend some time looking at experimental design concepts. As a data scientist, you are a scientist and as such, need to have the ability to design proper experiments to best answer your data science questions!
What does experimental design mean?
Experimental design is organizing an experiment so that you have the correct data (and enough of it!) to clearly and effectively answer your data science question. This process involves clearly formulating your question in advance of any data collection, designing the best set-up possible to gather the data to answer your question, identifying problems or sources of error in your design, and only then, collecting the appropriate data.
Why should you care?</p>
</div>
<div id="confounder" class="section level4 hasAnchor" number="2.1.1.10">
<h4><span class="header-section-number">2.1.1.10</span> Confounder:<a href="machine-learning-fundamentals.html#confounder" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>An extraneous variable that may affect the relationship between the dependent and independent variables.
In our example, since age affects foot size and literacy is affected by age, if we see any relationship between shoe size and literacy, the relationship may actually be due to age – age is “confounding” our experimental design!
To control for this, we can make sure we also measure the age of each individual so that we can take into account the effects of age on literacy, as well. Another way we could control for age’s effect on literacy would be to fix the age of all participants. If everyone we study is the same age, then we have removed the possible effect of age on literacy.</p>
<p>Age is confounding my experimental design! We need to control for this
In other experimental design paradigms, a control group may be appropriate. This is when you have a group of experimental subjects that are not manipulated. So if you were studying the effect of a drug on survival, you would have a group that received the drug (treatment) and a group that did not (control). This way, you can compare the effects of the drug in the treatment versus control group.</p>
<p>A control group is a group of subjects that do not receive the treatment, but still have their dependent variables measured
In these study designs, there are other strategies we can use to control for confounding effects. One, we can blind the subjects to their assigned treatment group. Sometimes, when a subject knows that they are in the treatment group (eg: receiving the experimental drug), they can feel better, not from the drug itself, but from knowing they are receiving treatment. This is known as the placebo effect. To combat this, often participants are blinded to the treatment group they are in; this is usually achieved by giving the control group a mock treatment (eg: given a sugar pill they are told is the drug). In this way, if the placebo effect is causing a problem with your experiment, both groups should experience it equally.</p>
<p>Blinding your study means that your subjects don’t know what group they belong to - all participants receive a “treatment”
And this strategy is at the heart of many of these studies; spreading any possible confounding effects equally across the groups being compared. For example, if you think age is a possible confounding effect, making sure that both groups have similar ages and age ranges will help to mitigate any effect age may be having on your dependent variable - the effect of age is equal between your two groups.
This “balancing” of confounders is often achieved by randomization. Generally, we don’t know what will be a confounder beforehand; to help lessen the risk of accidentally biasing one group to be enriched for a confounder, you can randomly assign individuals to each of your groups. This means that any potential confounding variables should be distributed between each group roughly equally, to help eliminate/reduce systematic errors.</p>
<p>Randomizing subjects to either the control or treatment group is a great strategy to reduce confounders’ effects
There is one final concept of experimental design that we need to cover in this lesson, and that is replication. Replication is pretty much what it sounds like, repeating an experiment with different experimental subjects. A single experiment’s results may have occured by chance; a confounder was unevenly distributed across your groups, there was a systematic error in the data collection, there were some outliers, etc. However, if you can repeat the experiment and collect a whole new set of data and still come to the same conclusion, your study is much stronger. Also at the heart of replication is that it allows you to measure the variability of your data more accurately, which allows you to better assess whether any differences you see in your data are significant.</p>
</div>
<div id="beware-p-hacking" class="section level4 hasAnchor" number="2.1.1.11">
<h4><span class="header-section-number">2.1.1.11</span> Beware p-hacking!<a href="machine-learning-fundamentals.html#beware-p-hacking" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One of the many things often reported in experiments is a value called the p-value. This is a value that tells you the probability that the results of your experiment were observed by chance. This is a very important concept in statistics that we won’t be covering in depth here, if you want to know more, check out this video explaining more about p-values.
What you need to look out for is when you manipulate p-values towards your own end. Often, when your p-value is less than 0.05 (in other words, there is a 5 percent chance that the differences you saw were observed by chance), a result is considered significant. But if you do 20 tests, by chance, you would expect one of the twenty (5%) to be significant. In the age of big data, testing twenty hypotheses is a very easy proposition. And this is where the term p-hacking comes from: This is when you exhaustively search a data set to find patterns and correlations that appear statistically significant by virtue of the sheer number of tests you have performed. These spurious correlations can be reported as significant and if you perform enough tests, you can find a data set and analysis that will show you what you wanted to see.
Check out this FiveThirtyEight activity where you can manipulate and filter data and perform a series of tests such that you can get the data to find whatever relationship you want!
XKCD mocks this concept in a comic testing the link between jelly beans and acne - clearly there is no link there, but if you test enough jelly bean colours, eventually, one of them will be correlated with acne at p-value &lt; 0.05!</p>
</div>
<div id="data-types" class="section level4 hasAnchor" number="2.1.1.12">
<h4><span class="header-section-number">2.1.1.12</span> Data types<a href="machine-learning-fundamentals.html#data-types" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p><code>Continuous variables</code> are anything measured on a quantitative scale that could be any fractional number. An example would be something like weight measured in kg.</p></li>
<li><p><code>Ordinal</code> data are data that have a fixed, small (&lt; 100) number of levels but are ordered. This could be for example survey responses where the choices are: poor, fair, good.</p></li>
<li><p><code>Categorical</code> data are data where there are multiple categories, but they aren’t ordered. One example would be sex: male or female. This coding is attractive because it is self-documenting.</p></li>
<li><p><code>Missing</code> data are data that are unobserved and you don’t know the mechanism. You should code missing values as NA.</p></li>
<li><p><code>Censored</code> data are data where you know the missingness mechanism on some level. Common examples are a measurement being below a detection limit or a patient being lost to follow-up. They should also be coded as NA when you don’t have the data. But you should also add a new column to your tidy data called, “VariableNameCensored” which should have values of TRUE if censored and FALSE if not.</p></li>
</ul>
</div>
<div id="data-scientists-in-marketing-science" class="section level4 hasAnchor" number="2.1.1.13">
<h4><span class="header-section-number">2.1.1.13</span> Data scientists in marketing science<a href="machine-learning-fundamentals.html#data-scientists-in-marketing-science" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Data scientists in marketing science play a crucial role in leveraging data-driven insights to optimize marketing strategies and improve decision-making.</p>
<p>Data scientists in marketing science contribute significantly to the development of targeted, efficient, and impactful marketing campaigns by harnessing the power of data and analytics. Their work helps organizations optimize their marketing spend, enhance customer experiences, and achieve measurable business outcomes.</p>
<p>Here are some key responsibilities and activities that data scientists in marketing science typically engage in:</p>
<ol style="list-style-type: decimal">
<li><strong>Data Analysis:</strong>
<ul>
<li>Conducting extensive data analysis to understand customer behavior, market trends, and other relevant metrics.</li>
<li>Utilizing statistical methods and machine learning algorithms to extract meaningful patterns and insights from large datasets.</li>
</ul></li>
<li>Predictive Modeling:
<ul>
<li>Developing and deploying predictive models to forecast future trends, customer behavior, and campaign outcomes.</li>
<li>Using machine learning techniques, such as regression analysis, decision trees, and ensemble methods, to build predictive models.</li>
</ul></li>
<li>Segmentation and Targeting:
<ul>
<li>Creating customer segments based on demographics, behavior, and other relevant factors.</li>
<li>Optimizing marketing strategies by targeting specific segments with personalized and relevant content.</li>
</ul></li>
<li>A/B Testing:
<ul>
<li>Designing and conducting A/B tests to evaluate the effectiveness of different marketing strategies, campaigns, or variations.</li>
<li>Analyzing A/B test results to make data-driven recommendations for optimization.</li>
</ul></li>
<li><strong>Causal Inference:</strong>
<ul>
<li>Applying advanced causal inference methods to understand the impact of marketing initiatives on customer behavior.</li>
<li>Assessing the causal relationships between marketing activities and business outcomes.</li>
</ul></li>
<li><strong>Data Visualization:</strong>
<ul>
<li>Creating clear and compelling data visualizations to communicate complex insights to non-technical stakeholders.</li>
<li>Using tools like Tableau, Power BI, or custom scripts to visualize data in a meaningful way.</li>
</ul></li>
<li><strong>Optimization Strategies:</strong>
<ul>
<li>Collaborating with marketing teams to develop and optimize marketing strategies based on data insights.</li>
<li>Recommending adjustments to campaigns, targeting strategies, and budget allocations for better performance.</li>
</ul></li>
<li><strong>Performance Measurement:</strong>
<ul>
<li>Developing key performance indicators (KPIs) and metrics to assess the success of marketing campaigns.</li>
<li>Monitoring and evaluating marketing performance against established benchmarks.</li>
</ul></li>
<li><strong>Data Management:</strong>
<ul>
<li>Ensuring the quality and integrity of marketing data by cleaning, preprocessing, and validating datasets.</li>
<li>Collaborating with data engineers to design and implement data pipelines for efficient data processing.</li>
</ul></li>
<li><strong>Communication and Collaboration:</strong>
<ul>
<li>Effectively communicating findings and insights to non-technical stakeholders, including marketing teams and executives.</li>
<li>Collaborating with cross-functional teams to align data-driven strategies with overall business objectives.</li>
</ul></li>
</ol>

<p><strong>Overfitting:</strong></p>
<ul>
<li><p>Statistical model is too complex</p></li>
<li><p>Too many parameters when compared to the total number of observations.</p></li>
<li><p>Poor Predictive Performance</p></li>
<li><p>Overfitted model overreacts to minor fluctuations in the training data</p></li>
</ul>
<p><strong>Underfitting:</strong></p>
<ul>
<li><p>Statistical model is too primitive</p></li>
<li><p>Poor Predictive Performance in the training model</p></li>
<li><p>The underfit model under-reacts to even bigger fluctuations.</p></li>
</ul>
<p><strong>Bias:</strong></p>
<p>Bias is an error introduced in your model because of the oversimplification of a machine learning algorithm. It can lead to underfitting.</p>
<p>In supervised learning, underfitting happens when a model unable to capture the underlying pattern of the data. These models usually have high bias and low variance. It happens when we have very less amount of data to build an accurate model or when we try to build a linear model with a nonlinear data.</p>
<p>Also, these kinds of models are very simple to capture the complex patterns in data like Linear and logistic regression.</p>
<p>In supervised learning, overfitting happens when our model captures the noise along with the underlying pattern in data.</p>
<p>It happens when we train our model a lot over noisy dataset. These models have low bias and high variance. These models are very complex like Decision trees which are prone to overfitting.</p>
<p>Bias is the difference between the average prediction of our model and the correct value which we are trying to predict. Model with high bias pays very little attention to the training data and oversimplifies the model. It always leads to high error on training and test data.</p>
<p><strong>What is variance?</strong></p>
<p>Variance is the variability of model prediction for a given data point or a value which tells us spread of our data. Model with high variance pays a lot of attention to training data and does not generalize on the data which it hasn’t seen before. As a result, such models perform very well on training data but has high error rates on test data. (over-fitting issue)</p>
<p><strong>Why is Bias - Variance Trade-off?</strong></p>
<p>If our model is too simple and has very few parameters then it may have high bias and low variance. On the other hand, if our model has large number of parameters then it’s going to have high variance and low bias. So, we need to find the right/good balance without overfitting and underfitting the data.</p>
<p><strong>Name three types of biases that can occur during sampling</strong></p>
<p>In the sampling process, there are three types of biases, which are:</p>
<p>• Selection bias
• Under coverage bias
• Survivorship bias</p>
<p><strong>Question:</strong> What do you understand by the Selection Bias? What are its various types?</p>
<p><strong>Answer:</strong> Selection bias is typically associated with research that doesn’t have a random selection of participants. It is a type of error that occurs when a researcher decides who is going to be studied. On some occasions, selection bias is also referred to as the selection effect.</p>
<p>In other words, selection bias is a distortion of statistical analysis that results from the sample collecting method. When selection bias is not taken into account, some conclusions made by a research study might not be accurate. Following are the various types of selection bias:</p>
<p>• Sampling Bias – A systematic error resulting due to a non-random sample of a populace causing certain members of the same to be less likely included than others that results in a biased sample.</p>
<p>• Time Interval – A trial might be ended at an extreme value, usually due to ethical reasons, but the extreme value is most likely to be reached by the variable with the most variance, even though all variables have a similar mean.</p>
<p>• Data – Results when specific data subsets are selected for supporting a conclusion or rejection of bad data arbitrarily.</p>
<p>• Attrition – Caused due to attrition, i.e. loss of participants, discounting trial subjects or tests that didn’t run to completion.</p>
<ol start="4" style="list-style-type: decimal">
<li><p>Discuss Decision Tree algorithm
A decision tree is a popular supervised machine learning algorithm. It is mainly used for Regression and Classification. It allows breaks down a dataset into smaller subsets. The decision tree can able to handle both categorical and numerical data.</p></li>
<li><p>What is Prior probability and likelihood?
Prior probability is the proportion of the dependent variable in the data set while the likelihood is the probability of classifying a given observant in the presence of some other variable.</p></li>
<li><p>Explain Recommender Systems?
It is a subclass of information filtering techniques. It helps you to predict the preferences or ratings which users likely to give to a product.</p></li>
</ol>
<p>Question: Please explain Recommender Systems along with an application.
Answer: Recommender Systems is a subclass of information filtering systems, meant for predicting the preferences or ratings awarded by a user to some product.
An application of a recommender system is the product recommendations section in Amazon. This section contains items based on the user’s search history and past orders.</p>
<ol start="7" style="list-style-type: decimal">
<li><p>Name three disadvantages of using a linear model
Three disadvantages of the linear model are:
• The assumption of linearity of the errors.
• You can’t use this model for binary or count outcomes
• There are plenty of overfitting problems that it can’t solve</p></li>
<li><p>Why do you need to perform resampling?</p></li>
</ol>
<p>Resampling is done in below-given cases:
• Estimating the accuracy of sample statistics by drawing randomly with replacement from a set of the data point or using as subsets of accessible data
• Substituting labels on data points when performing necessary tests
• Validating models by using random subsets</p>
<ol start="9" style="list-style-type: decimal">
<li>List out the libraries in Python used for Data Analysis and Scientific Computations.
SciPy, Pandas, Matplotlib, NumPy, SciKit, Seaborn</li>
<li>What is Power Analysis?
The power analysis is an integral part of the experimental design. It helps you to determine the sample size requires to find out the effect of a given size from a cause with a specific level of assurance. It also allows you to deploy a particular probability in a sample size constraint.</li>
<li>Explain Collaborative filtering
Collaborative filtering used to search for correct patterns by collaborating viewpoints, multiple data sources, and various agents.</li>
<li>Discuss ‘Naive’ in a Naive Bayes algorithm?
The Naive Bayes Algorithm model is based on the Bayes Theorem. It describes the probability of an event. It is based on prior knowledge of conditions which might be related to that specific event.</li>
<li>What is a Linear Regression?
Linear regression is a statistical programming method where the score of a variable ‘A’ is predicted from the score of a second variable ‘B’. B is referred to as the predictor variable and A as the criterion variable.</li>
<li>State the difference between the expected value and mean value
They are not many differences, but both of these terms are used in different contexts. Mean value is generally referred to when you are discussing a probability distribution whereas expected value is referred to in the context of a random variable.</li>
<li>What the aim of conducting A/B Testing?
AB testing used to conduct random experiments with two variables, A and B. The goal of this testing method is to find out changes to a web page to maximize or increase the outcome of a strategy.</li>
<li>What is Ensemble Learning?
The ensemble is a method of combining a diverse set of learners together to improvise on the stability and predictive power of the model. Two types of Ensemble learning methods are:</li>
</ol>
<p><strong>Bagging</strong>
Bagging method helps you to implement similar learners on small sample populations. It helps you to make nearer predictions.
Boosting
Boosting is an iterative method which allows you to adjust the weight of an observation depends upon the last classification. Boosting decreases the bias error and helps you to build strong predictive models.
18. Explain Eigenvalue and Eigenvector
Eigenvectors are for understanding linear transformations. Data scientist need to calculate the eigenvectors for a covariance matrix or correlation. Eigenvalues are the directions along using specific linear transformation acts by compressing, flipping, or stretching.
Question: Please explain Eigenvectors and Eigenvalues.
Answer: Eigenvectors help in understanding linear transformations. They are calculated typically for a correlation or covariance matrix in data analysis.
In other words, eigenvectors are those directions along which some particular linear transformation acts by compressing, flipping, or stretching.
Eigenvalues can be understood either as the strengths of the transformation in the direction of the eigenvectors or the factors by which the compressions happens.</p>
<ol start="19" style="list-style-type: decimal">
<li><p>Define the term cross-validation
Cross-validation is a validation technique for evaluating how the outcomes of statistical analysis will generalize for an Independent dataset. This method is used in backgrounds where the objective is forecast, and one needs to estimate how accurately a model will accomplish.
Question: Can you compare the validation set with the test set?
Answer: A validation set is part of the training set used for parameter selection as well as for avoiding overfitting of the machine learning model being developed. On the contrary, a test set is meant for evaluating or testing the performance of a trained machine learning model.</p></li>
<li><p>Explain the steps for a Data analytics project
The following are important steps involved in an analytics project:
• Understand the Business problem
• Explore the data and study it carefully.
• Prepare the data for modeling by finding missing values and transforming variables.
• Start running the model and analyze the Big data result.
• Validate the model with new data set.
• Implement the model and track the result to analyze the performance of the model for a specific period.</p></li>
</ol>
<p>Question: What do you mean by cluster sampling and systematic sampling?
Answer: When studying the target population spread throughout a wide area becomes difficult and applying simple random sampling becomes ineffective, the technique of cluster sampling is used. A cluster sample is a probability sample, in which each of the sampling units is a collection or cluster of elements.
Following the technique of systematic sampling, elements are chosen from an ordered sampling frame. The list is advanced in a circular fashion. This is done in such a way so that once the end of the list is reached, the same is progressed from the start, or top, again.</p>
<ol start="23" style="list-style-type: decimal">
<li>What is a Random Forest?
Random forest is a machine learning method which helps you to perform all types of regression and classification tasks. It is also used for treating missing values and outlier values.</li>
<li>What is the importance of having a selection bias?
Selection Bias occurs when there is no specific randomization achieved while picking individuals or groups or data to be analyzed. It suggests that the given sample does not exactly represent the population which was intended to be analyzed.</li>
<li>What is the K-means clustering method?
K-means clustering is an important unsupervised learning method. It is the technique of classifying data using a certain set of clusters which is called K clusters. It is deployed for grouping to find out the similarity in the data.</li>
<li>Explain the difference between Data Science and Data Analytics
Data Scientists need to slice data to extract valuable insights that a data analyst can apply to real-world business scenarios. The main difference between the two is that the data scientists have more technical knowledge then business analyst. Moreover, they don’t need an understanding of the business required for data visualization.</li>
<li>Explain p-value?
When you conduct a hypothesis test in statistics, a p-value allows you to determine the strength of your results. It is a numerical number between 0 and 1. Based on the value it will help you to denote the strength of the specific result.</li>
<li>Define the term deep learning
Deep Learning is a subtype of machine learning. It is concerned with algorithms inspired by the structure called artificial neural networks (ANN).</li>
<li>Explain the method to collect and analyze data to use social media to predict the weather condition.
You can collect social media data using Facebook, twitter, Instagram’s API’s. For example, for the tweeter, we can construct a feature from each tweet like tweeted date, retweets, list of follower, etc. Then you can use a multivariate time series model to predict the weather condition.</li>
<li>When do you need to update the algorithm in Data science?
You need to update an algorithm in the following situation:
• You want your data model to evolve as data streams using infrastructure
• The underlying data source is changing If it is non-stationarity</li>
<li>What is Normal Distribution
A normal distribution is a set of a continuous variable spread across a normal curve or in the shape of a bell curve. You can consider it as a continuous probability distribution which is useful in statistics. It is useful to analyze the variables and their relationships when we are using the normal distribution curve.</li>
<li>Which language is best for text analytics? R or Python?
Python will more suitable for text analytics as it consists of a rich library known as pandas. It allows you to use high-level data analysis tools and data structures, while R doesn’t offer this feature.</li>
<li>Explain the benefits of using statistics by Data Scientists
Statistics help Data scientist to get a better idea of customer’s expectation. Using the statistic method Data Scientists can get knowledge regarding consumer interest, behavior, engagement, retention, etc. It also helps you to build powerful data models to validate certain inferences and predictions.</li>
<li>Name various types of Deep Learning Frameworks
• Pytorch
• Microsoft Cognitive Toolkit
• TensorFlow
• Caffe
• Chainer
• Keras</li>
<li>Explain why Data Cleansing is essential and which method you use to maintain clean data
Dirty data often leads to the incorrect inside, which can damage the prospect of any organization. For example, if you want to run a targeted marketing campaign. However, our data incorrectly tell you that a specific product will be in-demand with your target audience; the campaign will fail.</li>
<li>What is skewed Distribution &amp; uniform distribution?
Skewed distribution occurs when if data is distributed on any one side of the plot whereas uniform distribution is identified when the data is spread is equal in the range.</li>
<li>When underfitting occurs in a static model?
Underfitting occurs when a statistical model or machine learning algorithm not able to capture the underlying trend of the data.</li>
<li>Name commonly used algorithms.
Four most commonly used algorithm by Data scientist are:
• Linear regression
• Logistic regression
• Random Forest
• KNN</li>
<li>What is precision?
Precision is the most commonly used error metric is n classification mechanism. Its range is from 0 to 1, where 1 represents 100%</li>
<li>What is a univariate analysis?
An analysis which is applied to none attribute at a time is known as univariate analysis. Boxplot is widely used, univariate model.</li>
<li>How do you overcome challenges to your findings?
In order, to overcome challenges of my finding one need to encourage discussion, Demonstrate leadership and respecting different options.</li>
<li>Explain cluster sampling technique in Data science
A cluster sampling method is used when it is challenging to study the target population spread across, and simple random sampling can’t be applied.</li>
<li>State the difference between a Validation Set and a Test Set
A Validation set mostly considered as a part of the training set as it is used for parameter selection which helps you to avoid overfitting of the model being built.
While a Test Set is used for testing or evaluating the performance of a trained machine learning model.</li>
<li>Explain the term Binomial Probability Formula?
“The binomial distribution contains the probabilities of every possible success on N trials for independent events that have a probability of π of occurring.”</li>
<li>What is a recall?
A recall is a ratio of the true positive rate against the actual positive rate. It ranges from 0 to 1.</li>
<li>Discuss normal distribution
Normal distribution equally distributed as such the mean, median and mode are equal.</li>
<li>While working on a data set, how can you select important variables? Explain
Following methods of variable selection you can use:
• Remove the correlated variables before selecting important variables
• Use linear regression and select variables which depend on that p values.
• Use Backward, Forward Selection, and Stepwise Selection
• Use Xgboost, Random Forest, and plot variable importance chart.
• Measure information gain for the given set of features and select top n features accordingly.</li>
<li>Is it possible to capture the correlation between continuous and categorical variable?
Yes, we can use analysis of covariance technique to capture the association between continuous and categorical variables.</li>
<li>Treating a categorical variable as a continuous variable would result in a better predictive model?
Yes, the categorical value should be considered as a continuous variable only when the variable is ordinal in nature. So, it is a better predictive model.
Question:
Recall: What is the proportion of actual positives was identified correctly?
TP / (TP + FN)
Precision: What is the proportion of positive identifications was actually correct?
TP / (TP + FP)
Question:
A false positive is an incorrect identification of the absence of a condition when it is absent.
A false negative is an incorrect identification of the absence of a condition when it is actually present.
Question: Please explain the goal of A/B Testing.
Answer: A/B Testing is a statistical hypothesis testing meant for a randomized experiment with two variables, A and B. The goal of A/B Testing is to maximize the likelihood of an outcome of some interest by identifying any changes to a webpage.
A highly reliable method for finding out the best online marketing and promotional strategies for a business, A/B Testing can be employed for testing everything, ranging from sales emails to search ads and website copy.
Question: Could you explain how to define the number of clusters in a clustering algorithm?
Answer: The primary objective of clustering is to group together similar identities in such a way that while entities within a group are similar to each other, the groups remain different from one another.
Generally, the Within Sum of Squares is used for explaining the homogeneity within a cluster. For defining the number of clusters in a clustering algorithm, WSS is plotted for a range pertaining to a number of clusters. The resultant graph is known as the Elbow Curve.
The Elbow Curve graph contains a point that represents the point post in which there aren’t any decrements in the WSS. This is known as the bending point and represents K in K–Means.
Although the aforementioned is the widely-used approach, another important approach is the Hierarchical clustering. In this approach, dendrograms are created first and then distinct groups are identified from there.
Question: Please explain Gradient Descent.
Answer: The degree of change in the output of a function relating to the changes made to the inputs is known as a gradient. It measures the change in all weights with respect to the change in error. A gradient can also be comprehended as the slope of a function.
Gradient Descent refers to escalating down to the bottom of a valley. Simply, consider this something as opposed to climbing up a hill. It is a minimization algorithm meant for minimizing a given activation function.
Question: Please enumerate the various steps involved in an analytics project.
Answer: Following are the numerous steps involved in an analytics project:
• Understanding the business problem
• Exploring the data and familiarizing with the same
• Preparing the data for modeling by means of detecting outlier values, transforming variables, treating missing values, et cetera
• Running the model and analyzing the result for making appropriate changes or modifications to the model (an iterative step that repeats until the best possible outcome is gained)
• Validating the model using a new dataset
• Implementing the model and tracking the result for analyzing the performance of the same</li>
</ol>
<p>Question: What are outlier values and how do you treat them?
Answer: Outlier values, or simply outliers, are data points in statistics that don’t belong to a certain population. An outlier value is an abnormal observation that is very much different from other values belonging to the set.
Identification of outlier values can be done by using univariate or some other graphical analysis method. Few outlier values can be assessed individually but assessing a large set of outlier values require the substitution of the same with either the 99th or the 1st percentile values.
There are two popular ways of treating outlier values:
1. To change the value so that it can be brought within a range
2. To simply remove the value
Note: - Not all extreme values are outlier values.</p>
<ol start="21" style="list-style-type: decimal">
<li>Discuss Artificial Neural Networks
Artificial Neural networks (ANN) are a special set of algorithms that have revolutionized machine learning. It helps you to adapt according to changing input. So the network generates the best possible result without redesigning the output criteria.</li>
<li>What is Back Propagation?
Back-propagation is the essence of neural net training. It is the method of tuning the weights of a neural net depend upon the error rate obtained in the previous epoch. Proper tuning of the helps you to reduce error rates and to make the model reliable by increasing its generalization.</li>
</ol>
<p><strong>Explain Auto-Encoder</strong></p>
<p>Autoencoders are learning networks. It helps you to transform inputs into outputs with fewer numbers of errors. This means that you will get output to be as close to input as possible.
36. Define Boltzmann Machine
Boltzmann machines is a simple learning algorithm. It helps you to discover those features that represent complex regularities in the training data. This algorithm allows you to optimize the weights and the quantity for the given problem.
40. What is reinforcement learning?
Reinforcement Learning is a learning mechanism about how to map situations to actions. The end result should help you to increase the binary reward signal. In this method, a learner is not told which action to take but instead must discover which action offers a maximum reward. As this method based on the reward/penalty mechanism.</p>

</div>
</div>
<div id="bootstrapping" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Bootstrapping<a href="machine-learning-fundamentals.html#bootstrapping" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="jack-knife" class="section level4 hasAnchor" number="2.1.2.1">
<h4><span class="header-section-number">2.1.2.1</span> Jack-knife<a href="machine-learning-fundamentals.html#jack-knife" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>• The jackknife is a tool for estimating standard errors and the bias of estimators</p>
<p>• As its name suggests, the jackknife is a small, handy tool; in contrast to the
bootstrap, which is then the moral equivalent of a giant workshop full of tools</p>
<p>• Both the jackknife and the bootstrap involve re-sampling data; that is, repeatedly creating new data sets from the original data</p>
<p>The jackknife deletes each observation and calculates an estimate based on the remaining n − 1 of them</p>
<p>• It uses this collection of estimates to do things like estimate the bias and the standard error</p>
<p>• Note that estimating the bias and having a standard error are not needed for things like sample means, which we know are unbiased estimates of population means and what their standard errors are</p>
<p>It has been shown that the jackknife is a linear approximation to the bootstrap</p>
<p>• Generally do not use the jackknife for sample quantiles like the median; as it has been shown to have some poor properties</p>
<p>The bootstrap</p>
<p>• The bootstrap is a tremendously useful tool for constructing confidence intervals and calculating standard errors for difficult statistics
• For example, how would one derive a confidence interval for the median? • The bootstrap procedure follows from the so called bootstrap principle</p>
<p>Suppose that I have a statistic that estimates some population parameter, but I don’t know its sampling distribution
• The bootstrap principle suggests using the distribution defined by the data to approximate its sampling distribution
• In practice, the bootstrap principle is always carried out using simulation
• The general procedure follows by first simulating complete data sets from the observed data with replacement
• This is approximately drawing from the sampling distribution of that statistic, at least as far as the data is able to approximate the true population distribution
• Calculate the statistic for each simulated data set
• Use the simulated statistics to either define a confidence interval or take the standard deviation to calculate a standard error
Example
• Consider again, the data set of 630 measurements of gray matter volume for workers from a lead manufacturing plant
• The median gray matter volume is around 589 cubic centimeters
• We want a confidence interval for the median of these measurements
• Bootstrap procedure for calculating for the median from a data set of n observations
i. Sample n observations with replacement from the observed data resulting in one simulated complete data set
ii. Take the median of the simulated data set
iii. Repeat these two steps B times, resulting in B simulated medians
iv. These medians are approximately draws from the sampling distribution of the
median of n observations; therefore we can
• Draw a histogram of them
• Calculate their standard deviation to estimate the standard error of the median • Take the 2.5th and 97.5th percentiles as a confidence interval for the median</p>
<p>Summary
• The bootstrap is non-parametric
• However, the theoretical arguments proving the validity of the bootstrap rely
on large samples
• Better percentile bootstrap confidence intervals correct for bias
• There are lots of variations on bootstrap procedures; the book “An Introduction to the Bootstrap” by Efron and Tibshirani is a great place to start for both bootstrap and jackknife information</p>

</div>
</div>
<div id="classification-models-evaluation" class="section level3 hasAnchor" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Classification Models: Evaluation<a href="machine-learning-fundamentals.html#classification-models-evaluation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><a href="https://medium.com/@demrahayan/evaluating-binary-classification-models-with-pyspark-2afc5ac7937f">My medium story</a></p>
<p><a href="https://developers.google.com/machine-learning/crash-course/classification/">Google developers</a></p>
<div id="thresholding" class="section level4 hasAnchor" number="2.1.3.1">
<h4><span class="header-section-number">2.1.3.1</span> Thresholding<a href="machine-learning-fundamentals.html#thresholding" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Logistic regression returns a probability. You can use the returned probability “as is” (for example, the probability that the user will click on this ad is 0.00023) or convert the returned probability to a binary value (for example, this email is spam).</p>
<p>A logistic regression model that returns 0.9995 for a particular email message is predicting that it is very likely to be spam. Conversely, another email message with a prediction score of 0.0003 on that same logistic regression model is very likely not spam.</p>
<p>However, what about an email message with a prediction score of 0.6? In order to map a logistic regression value to a binary category, you must define a <code>classification threshold</code> (also called the <code>decision threshold</code>).</p>
<p>A value above that threshold indicates “spam”; a value below indicates “not spam.” It is tempting to assume that the classification threshold should always be 0.5, but thresholds are problem-dependent, and are therefore values that you must tune.</p>
<p>Note: “Tuning” a threshold for logistic regression is different from tuning hyperparameters such as learning rate. Part of choosing a threshold is assessing how much you’ll suffer for making a mistake. For example, mistakenly labeling a non-spam message as spam is very bad. However, mistakenly labeling a spam message as non-spam is unpleasant, but hardly the end of your job.</p>
</div>
<div id="confusion-matrix" class="section level4 hasAnchor" number="2.1.3.2">
<h4><span class="header-section-number">2.1.3.2</span> Confusion Matrix<a href="machine-learning-fundamentals.html#confusion-matrix" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<table>
<thead>
<tr class="header">
<th></th>
<th>Predicted Positive</th>
<th>Predicted Negative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Actual Positive</strong></td>
<td>TP</td>
<td>FN</td>
</tr>
<tr class="even">
<td><strong>Actual Negative</strong></td>
<td>FP</td>
<td>TN</td>
</tr>
</tbody>
</table>
<p><strong>True Positive:</strong> Model predicted positive and it is true.</p>
<p><strong>True negative:</strong> Model predicted negative and it is true.</p>
<p><strong>False positive (Type 1 Error):</strong> Model predicted positive but it is false.</p>
<p><strong>False negative (Type 2 Error):</strong> Model predicted negative and it is true.</p>
<p><strong>False Positive Rate (FPR):</strong></p>
<p>The False Positive Rate is the ratio of false positive predictions to the total number of actual negatives. It measures the rate at which the model incorrectly predicts the positive class among the instances that are actually negative.</p>
<p><span class="math inline">\(FPR = \frac{FP}{TN + FP}\)</span></p>
<p><strong>True Positive Rate (TPR), Sensitivity, or Recall:</strong></p>
<p>The True Positive Rate is the ratio of true positive predictions to the total number of actual positives. It measures the ability of the model to correctly predict the positive class among instances that are actually positive.</p>
<p><span class="math inline">\(Recall (TPR) = \frac{TP}{TP + FN}\)</span></p>
<p><strong>Accuracy:</strong></p>
<p>It represents the ratio of correctly predicted instances to the total number of instances. The accuracy metric is suitable for balanced datasets where the classes are evenly distributed. It is calculated using the following formula:</p>
<p><span class="math inline">\(Accuracy = \frac{TP + TN}{TP + TN + FP + FN}\)</span></p>
<p>Accuracy provides a general sense of how well a model is performing across all classes. It is easy to understand and interpret, making it a commonly used metric, especially when the classes are balanced.</p>
<p>However, accuracy may not be an ideal metric in situations where the class distribution is imbalanced. In imbalanced datasets, where one class significantly outnumbers the other, a high accuracy might be achieved by simply predicting the majority class. In such cases, other metrics like precision, recall, F1 score, or area under the receiver operating characteristic (ROC-AUC) curve may be more informative.</p>
<p><strong>Precision:</strong></p>
<p>Precision is the ratio of true positive predictions to the total number of positive predictions made by the model. It represents the accuracy of the positive predictions made by the model.</p>
<p><span class="math inline">\(Precision = \frac{TP}{TP + FP}\)</span></p>
<p><strong>F1 Measure:</strong></p>
<p>The F1 score is a metric commonly used in binary classification to provide a balance between precision and recall. It is the harmonic mean of precision and recall, combining both measures into a single value. The F1 score is particularly useful when there is an uneven class distribution or when both false positives and false negatives are important considerations.</p>
<p>The F1 score is useful in situations where achieving a balance between precision and recall is important, as it penalizes models that have a significant imbalance between these two metrics.</p>
<p><span class="math inline">\(F1 score = 2 \times \frac{Precision \times Recall}{Precision + Recall}\)</span></p>
</div>
<div id="in-marketing" class="section level4 hasAnchor" number="2.1.3.3">
<h4><span class="header-section-number">2.1.3.3</span> In Marketing<a href="machine-learning-fundamentals.html#in-marketing" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>Precision:</strong></p>
<p>In marketing, precision is valuable when the cost or impact associated with false positives (incorrectly identifying a non-lookalike as a lookalike) is high. For example, if targeting a non-lookalike with a marketing campaign has significant costs, you want to minimize false positives.</p>
<p><strong>Recall:</strong></p>
<p>In marketing, recall is important when you want to ensure that you are not missing potential opportunities (actual lookalikes). If missing a true lookalike has a high cost or lost opportunity, you want to maximize recall.</p>

</div>
</div>
</div>
<div id="elastic-net-model" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Elastic Net Model<a href="machine-learning-fundamentals.html#elastic-net-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Elastic Net is a regularization technique that combines both L1 (Lasso) and L2 (Ridge) regularization penalties in a linear regression model. This technique is commonly used in machine learning, especially when dealing with high-dimensional datasets or situations where some of the features are highly correlated.</p>
<p>In elastic net regularization, the objective function is a combination of the L1 and L2 regularization terms along with the linear regression loss. The regularization strength is controlled by two hyperparameters, often denoted as
α
α (alpha) and
λ
λ (lambda):</p>
<p>α
α controls the mixing between L1 and L2 regularization. When
α
=
0
α=0, it is equivalent to Ridge regression, and when
α
=
1
α=1, it is equivalent to Lasso regression. Any value in between (0 and 1) allows for a mixture of both.
λ
λ controls the overall strength of the regularization.</p>
<p>In R, you can fit an elastic net model using the glmnet package. Here’s a brief example:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="machine-learning-fundamentals.html#cb1-1" tabindex="-1"></a><span class="co"># Install and load the glmnet package if not already installed</span></span>
<span id="cb1-2"><a href="machine-learning-fundamentals.html#cb1-2" tabindex="-1"></a><span class="co"># install.packages(&quot;glmnet&quot;)</span></span>
<span id="cb1-3"><a href="machine-learning-fundamentals.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb1-4"><a href="machine-learning-fundamentals.html#cb1-4" tabindex="-1"></a></span>
<span id="cb1-5"><a href="machine-learning-fundamentals.html#cb1-5" tabindex="-1"></a><span class="co"># Generate some example data</span></span>
<span id="cb1-6"><a href="machine-learning-fundamentals.html#cb1-6" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-7"><a href="machine-learning-fundamentals.html#cb1-7" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb1-8"><a href="machine-learning-fundamentals.html#cb1-8" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb1-9"><a href="machine-learning-fundamentals.html#cb1-9" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(n <span class="sc">*</span> p), <span class="at">nrow =</span> n, <span class="at">ncol =</span> p)</span>
<span id="cb1-10"><a href="machine-learning-fundamentals.html#cb1-10" tabindex="-1"></a>beta_true <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">0</span>)</span>
<span id="cb1-11"><a href="machine-learning-fundamentals.html#cb1-11" tabindex="-1"></a>y <span class="ot">&lt;-</span> X <span class="sc">%*%</span> beta_true <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb1-12"><a href="machine-learning-fundamentals.html#cb1-12" tabindex="-1"></a></span>
<span id="cb1-13"><a href="machine-learning-fundamentals.html#cb1-13" tabindex="-1"></a><span class="co"># Fit an elastic net model</span></span>
<span id="cb1-14"><a href="machine-learning-fundamentals.html#cb1-14" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.5</span>  <span class="co"># You can adjust alpha to control the mixture of L1 and L2 regularization</span></span>
<span id="cb1-15"><a href="machine-learning-fundamentals.html#cb1-15" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="fl">0.1</span>  <span class="co"># You can adjust lambda to control the overall strength of regularization</span></span>
<span id="cb1-16"><a href="machine-learning-fundamentals.html#cb1-16" tabindex="-1"></a></span>
<span id="cb1-17"><a href="machine-learning-fundamentals.html#cb1-17" tabindex="-1"></a>enet_model <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X, y, <span class="at">alpha =</span> alpha, <span class="at">lambda =</span> lambda)</span></code></pre></div>

</div>
<div id="survival-analysis" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Survival Analysis<a href="machine-learning-fundamentals.html#survival-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="references" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> References<a href="machine-learning-fundamentals.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Web Sources</strong></p>
<ol style="list-style-type: decimal">
<li><p><a href="https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html">Emily C. Zabor: Survival Aanalysis in R</a></p></li>
<li><p><a href="https://bookdown.org/sestelo/sa_financial/">A short course on Survival Analysis applied to the Financial Industry</a></p></li>
<li><p><a href="https://www.datacamp.com/tutorial/survival-analysis-R">Survival Analysis in R For Beginners</a></p></li>
<li><p><a href="https://rviews.rstudio.com/2017/09/25/survival-analysis-with-r/">Survival Analysis with R</a></p></li>
<li><p><a href="http://www.sthda.com/english/wiki/survival-analysis-basics">Survival Analysis Basics</a></p></li>
<li><p><a href="https://www.r-bloggers.com/2018/03/steps-to-perform-survival-analysis-in-r/">Steps to perform Survival Analysis in R</a></p></li>
<li><p><a href="http://tagteam.harvard.edu/hub_feeds/1981/feed_items/2286128">Survival Analysis with R, Harvard</a></p></li>
<li><p><a href="https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Survival/BS704_Survival_print.html">Survival Analysis: Lisa Sullivan, PhD</a></p></li>
<li><p><a href="https://www.nature.com/articles/6601118.pdf">Survival Analysis Part I: Basic concepts and first analyses</a></p></li>
<li><p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3932959/pdf/nihms549224.pdf">Practical Guide Paper</a></p></li>
<li><p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5045282/">An Introduction to Survival Statistics: Kaplan-Meier Analysis</a></p></li>
<li><p><a href="https://towardsdatascience.com/kaplan-meier-curves-c5768e349479">Kaplan Meier curves: an introduction</a></p></li>
<li><p><a href="https://stat.ethz.ch/R-manual/R-devel/library/survival/html/lung.html">NCCTG Lung Cancer Data</a></p></li>
</ol>
<p><strong>pdf references</strong></p>
<!-- <iframe src="data_setup_alternative.pdf" style="width:100%; height:100px;"></iframe> -->
<!-- <a href=survival_pdf/survival_data_setup_alternative.pdf>1. Data Setup Alternative</a> -->
<p><a href="survival_pdf/survival_data_setup_alternative.pdf">1. Data Setup Alternative</a></p>
<p><a href="survival_pdf/survival_Intro_Survival_Analysis_Practice.pdf">2. Introduction to Survival Analysis in Practice</a></p>
<p><a href="survival_pdf/survival_lecture_note.pdf">3. Chapter 7 - Survival Models</a></p>
<p><a href="survival_pdf/survival_notes_pat.pdf">4. Notes from Pat</a></p>
<p><a href="survival_pdf/Survival_parametric.pdf">5. Parametric Survival Models</a></p>
<p><a href="survival_pdf/survival_retain_customers.pdf">6. Retain Customers by Churn model</a></p>
<p><a href="survival_pdf/survival_intro.pdf">7. Intro to Survival Analysis</a></p>
</div>
<div id="time-to-event-analysis" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Time to event analysis<a href="machine-learning-fundamentals.html#time-to-event-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Time to event analysis has also been used widely in the social sciences where interest is on analyzing time to events such as job changes, marriage, birth of children and so forth.</p>
<p>There are certain aspects of survival analysis data, such as censoring and non-normality, that generate great difficulty when trying to analyze the data using traditional statistical models such as multiple linear regression.</p>
<p>The non-normality aspect of the data violates the normality assumption of most commonly used statistical model such as regression or ANOVA, etc.</p>
<p>A censored observation is defined as an observation with incomplete information.
When an observation is right censored it means that the information is incomplete because the subject did not have an event during the time that the subject was part of the study.</p>
<p>The point of survival analysis is to follow subjects over time and observe at which point in time they experience the event of interest.</p>
<p>It often happens that the study does not span enough time in order to observe the event for all the subjects in the study. This could be due to a number of reasons. Perhaps subjects drop out of the study for reasons unrelated to the study (i.e. patients moving to another area and leaving no forwarding address).</p>
<p>The common feature of all of these examples is that if the subject had been able to stay in the study then it would have been possible to observe the time of the event eventually.</p>
<p>Type of censoring
- Right truncation
- Right censoring
- Left truncation
- Left censoring</p>
<p>In survival analysis, censoring refers to situations where the event of interest (e.g., death, failure, or another outcome) is not observed for some subjects during the study period. There are two main types of censoring: right truncation and right censoring.</p>
<ol style="list-style-type: decimal">
<li><strong>Right Truncation:</strong>
<ul>
<li><strong>Definition:</strong> Right truncation occurs when individuals enter the study at different times, and some individuals have already experienced the event of interest before the study begins.</li>
<li><strong>Example:</strong> Consider a study on the time until a machine fails. If the study starts at a certain date, and some machines have already failed before that date, those machines are considered right-truncated because their failure times are not observed in the study.</li>
</ul></li>
<li><strong>Right Censoring:</strong>
<ul>
<li><strong>Definition:</strong> Right censoring occurs when individuals are followed for a certain period, but the event of interest does not occur for some of them by the end of the study.</li>
<li><strong>Example:</strong> In a clinical trial studying the time until disease recurrence, if a patient has not experienced recurrence by the end of the study period or is lost to follow-up, their survival time is right-censored. The exact time of recurrence is not known for these patients.</li>
</ul></li>
</ol>
<p>In summary, right truncation involves incomplete observation due to some subjects entering the study late, whereas right censoring occurs when the event of interest has not occurred for some subjects by the end of the study. Both types of censoring are common in survival analysis and need to be appropriately accounted for in statistical models to obtain unbiased estimates of survival probabilities and hazard rates.</p>
<p><strong>What is survival data?</strong></p>
<p>Time-to-event data that consist of a distinct start time and end time.</p>
<p>Examples from cancer
• Time from surgery to death
• Time from start of treatment to progression
• Time from response to recurrence</p>
<p>Examples from other fields</p>
<p>Time-to-event data are common in many fields including, but not limited to
• Time from HIV infection to development of AIDS
• Time to heart attack
• Time to onset of substance abuse
• Time to initiation of sexual activity
• Time to machine malfunction</p>
<p>Types of censoring</p>
<p>A subject may be censored due to:
• Loss to follow-up
• Withdrawal from study
• No event by end of fixed study period</p>
<p>Specifically these are examples of right censoring.</p>
<p>Left censoring and interval censoring are also possible, and methods exist to analyze this type of data.</p>
</div>
<div id="kaplan-meier" class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Kaplan-Meier<a href="machine-learning-fundamentals.html#kaplan-meier" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><a href="https://datatab.net/tutorial/kaplan-meier-curve#:~:text=The%20Kaplan-Meier%20curve%20shows,therefore%20a%20better%20survival%20prognosis.">Source</a></p>
<p>The Kaplan-Meier curve is commonly used to analyze time-to-event data, such as the time until death or the time until a specific event occurs. For this, the Kaplan Meier curve graphically represent the survival rate or survival function. Time is plotted on the x-axis and the survival rate is plotted on the y-axis.</p>
<div id="survival-rate" class="section level4 hasAnchor" number="2.3.3.1">
<h4><span class="header-section-number">2.3.3.1</span> Survival rate<a href="machine-learning-fundamentals.html#survival-rate" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Suppose you’re a dental technician and you want to study the “survival time” of a filling in a tooth.</p>
<p>So your start time is the moment when a person goes to the dentist for a filling, and your end time, the event, is the moment when the filling breaks. The time between these two events is the focus of your study.</p>
<p><img src="figs/survival2.png" /></p>
<p>For example, you may be interested in the probability that your filling will last longer than 5 years.</p>
<p>To do this, you read off the value at 5 years on the graph, which is the survival rate.</p>
<p>At 5 years, the Kaplan-Meier curve gives you a value of 0.7.</p>
<pre><code>  So there is a 70% chance that your filling will last longer than 5 years.</code></pre>
</div>
<div id="interpreting-the-kaplan-meier-curve" class="section level4 hasAnchor" number="2.3.3.2">
<h4><span class="header-section-number">2.3.3.2</span> Interpreting the Kaplan-Meier curve<a href="machine-learning-fundamentals.html#interpreting-the-kaplan-meier-curve" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Kaplan-Meier curve shows the cumulative survival probabilities.</p>
<p>A steeper slope indicates a higher event rate (death rate) and therefore a worse survival prognosis. A flatter slope indicates a lower event rate and therefore a better survival prognosis. The curve may have plateaus or flat areas, indicating periods of relatively stable survival.</p>
<p>If there are multiple curves representing different groups, you can compare their shapes and patterns. If the curves are parallel, it suggests that the groups have similar survival experiences. If the curves diverge or cross, it indicates differences in survival between the groups.</p>
<p>At specific time points, you can estimate the survival probability by locating the time point on the horizontal axis and dropping a vertical line to the curve. Then, read the corresponding survival probability from the vertical axis.</p>
</div>
<div id="calculating-the-kaplan-meier-curve" class="section level4 hasAnchor" number="2.3.3.3">
<h4><span class="header-section-number">2.3.3.3</span> Calculating the Kaplan-Meier curve<a href="machine-learning-fundamentals.html#calculating-the-kaplan-meier-curve" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s say the filling lasted 3 years for the first subject, 4 years for the second subject, 4 years for the third subject, and so on.</p>
<p><img src="figs/km0.png" /></p>
<p>Let’s assume that none of the cases are “censored”. The data are already arranged so that the shortest survival time is at the top and the longest at the bottom.</p>
<p>Now we create a second table that we can use to draw the Kaplan-Meier curve. To do this, we look at the time points in the left table and add the time zero. So we have the time points 0, then 3, 4, 6, 7, 8 11 and 13. In total we have 10 subjects.</p>
<p>Now we look at how many fills break out at each time. We enter this in the column m. So at time 0, no fillings were broken out. After 3 years, there were one broken fillings, after 4 years there were two, after 6 years there was one. We now do the same for all the other times.</p>
<p>Next, we look at the number of cases that have survived to the time plus the number of cases where the event occurs at the exact time. We enter this in column n.</p>
<p>So n is the number of cases that survived to that point, plus the people who dropped out at that exact point.</p>
<p>After zero years we still have all 10 people. After 3 years, we get 10 for n, 9 people still have their fill intact, and one person’s fill broke out exactly after 3 years.</p>
<p>The easiest way to get n is to take the previous n value and subtract the previous m value. So we get 10 - 1 equals 9. Then 9 minus 2 equals 7, 7 - 1 equals 6… and so on and so forth.</p>
<p>From column n we can now calculate the survival rates. To do this, we simply divide n by the total number, i.e. 10.</p>
<p>So 10 divided by 10 is equal to 1, 9 divided by 10 is equal to 0.9, 7 divided by 10 is equal to 0.7. Now we do the same for all the others.</p>
</div>
<div id="draw-kaplan-meier-curve" class="section level4 hasAnchor" number="2.3.3.4">
<h4><span class="header-section-number">2.3.3.4</span> Draw Kaplan Meier curve<a href="machine-learning-fundamentals.html#draw-kaplan-meier-curve" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can now plot the Kaplan-Meier curve. At time 0 we have a value of 1, after 3 years we have a value of 0.9 or 90%. After 4 years we get 0.7, after 6 years 0.6 and so on and so forth.</p>
<p><img src="figs/km1.png" /></p>
<p>From the Kaplan-Meier curve, we can now see what percentage of the filling has not broken out after a certain time.</p>
</div>
<div id="censored-data" class="section level4 hasAnchor" number="2.3.3.5">
<h4><span class="header-section-number">2.3.3.5</span> Censored data<a href="machine-learning-fundamentals.html#censored-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Censored data has been added to the example in these three places.</p>
<p><img src="figs/km2.png" /></p>
<p>We now need to enter this data into our Kaplan-Meier curve table. We do this as follows: We create our m exactly as we did before, looking at how many cases failed at each time point.</p>
<p>Now we add a column q, in which we enter how many cases were censored at each time.</p>
<p>Note that the time at which each censored case occurred does not get its own row, but is assigned to the previous time.</p>
<p><img src="figs/km3.png" /></p>
<p>Let’s look at this case. The censoring took place at time 9. In this table, however, there is no event with nine years and we also don’t add it. The person is added at time 8.</p>
<p>We can now re-calculate the values for the survival curve. If we have censored data, this is a little more complex.</p>
<p>For this, we write down the values in the first step. We get these values by calculating n-m/n. In the third row, for example, we get the value 10/12 with 12-2 by 12.</p>
<p>The calculation of the real value is iterative. To do this, we multiply the result from the previous row by the value we have just calculated.</p>
<p>So, in the first row we get 1, now we calculate 12/13 times 1, which is equal to 0.923. In the next row we calculate 10/12 times 0.923 and get a value of 0.769. We take this value again for the next row.</p>
<p>We do this for all the rows. We can then plot the Kaplan-Meier curve with this data in the same way as before.</p>
</div>
<div id="comparing-different-groups" class="section level4 hasAnchor" number="2.3.3.6">
<h4><span class="header-section-number">2.3.3.6</span> Comparing different groups<a href="machine-learning-fundamentals.html#comparing-different-groups" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you are comparing several groups or categories (e.g. treatment groups), the Kaplan-Meier curve consists of several lines, each representing a different group. Each line shows the estimated survival rate for that particular group. To test whether there is a statistically significant difference between the groups, the log-rank test can be used.</p>
<p>If you have several factors and you want to see if they have an effect on the curve, you can calculate a Log Rank Test or calculate a Cox Regression here on DATAtab.</p>
</div>
<div id="kaplan-meier-curve-assumptions" class="section level4 hasAnchor" number="2.3.3.7">
<h4><span class="header-section-number">2.3.3.7</span> Kaplan-Meier curve assumptions<a href="machine-learning-fundamentals.html#kaplan-meier-curve-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Random or Non-informative censoring: This assumption states that the occurrence of censoring is unrelated to the likelihood of experiencing the event of interest. In other words, censoring should be random and not influenced by factors that affect the event outcome. If censoring is not non-informative, the estimated survival probabilities may be biased.</p>
<p>Independence of censoring: This assumption assumes that the censoring times of different individuals are independent of each other. This means that the occurrence or timing of censoring for one participant should not provide any information about the censoring times for other participants.</p>
<p>Survival probabilities do not change over time: The Kaplan-Meier curve assumes that the survival probabilities estimated at each time point remain constant over time. This assumption may not be valid if there are time-varying factors or treatments that can influence survival probabilities.</p>
<p>No competing risks: The Kaplan-Meier curve assumes that the event of interest is the only possible outcome and there are no other competing events that could prevent the occurrence of the event being studied. Competing events can include other causes of death or events that render the occurrence of the event of interest impossible.</p>

</div>
</div>
<div id="the-basics-of-survival-analysis" class="section level3 hasAnchor" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> The basics of Survival Analysis<a href="machine-learning-fundamentals.html#the-basics-of-survival-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="machine-learning-fundamentals.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb3-2"><a href="machine-learning-fundamentals.html#cb3-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="machine-learning-fundamentals.html#cb3-3" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb3-4"><a href="machine-learning-fundamentals.html#cb3-4" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-5"><a href="machine-learning-fundamentals.html#cb3-5" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb3-6"><a href="machine-learning-fundamentals.html#cb3-6" tabindex="-1"></a></span>
<span id="cb3-7"><a href="machine-learning-fundamentals.html#cb3-7" tabindex="-1"></a><span class="co"># devtools::install_github(&quot;zabore/ezfun&quot;)</span></span>
<span id="cb3-8"><a href="machine-learning-fundamentals.html#cb3-8" tabindex="-1"></a>ezfun<span class="sc">::</span><span class="fu">set_ccf_palette</span>(<span class="st">&quot;contrast&quot;</span>)</span></code></pre></div>
<pre><code>## &lt;environment: R_GlobalEnv&gt;</code></pre>
<p><a href="https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html">Original article</a></p>
<p>Survival data are time-to-event data that consist of a distinct start time and end time.</p>
<p>Examples from cancer:</p>
<ul>
<li>Time from surgery to death</li>
<li>Time from start of treatment to progression</li>
<li>Time from response to recurrence</li>
<li>Time-to-event data are common in many other fields.</li>
</ul>
<p>Some other examples include:</p>
<ul>
<li>Time from HIV infection to development of AIDS</li>
<li>Time to heart attack</li>
<li>Time to onset of substance abuse</li>
<li>Time to initiation of sexual activity</li>
<li>Time to machine malfunction</li>
</ul>
<p>Because time-to-event data are common in many fields, it also goes by names besides survival analysis including:</p>
<ul>
<li>Reliability analysis</li>
<li>Duration analysis</li>
<li>Event history analysis</li>
<li>Time-to-event analysis</li>
</ul>
<p>A key feature of survival data is censoring.</p>
<p>Censoring occurs if a subject has not experienced the event of interest by the end of data collection.</p>
<p>A subject may be censored due to:</p>
<ul>
<li>Loss to follow-up</li>
<li>Withdrawal from study</li>
<li>No event by end of fixed study period</li>
</ul>
<p>Specifically these are examples of <strong>right censoring.</strong></p>
<p><strong>Left censoring</strong> and <strong>interval censoring</strong> are also possible, and methods exist to analyze these types of data, but this tutorial will be focus on right censoring.</p>
<p>To illustrate the impact of censoring, suppose we have the following data:</p>
<p><img src="figs/survival1.png" /></p>
<p>How would we compute the proportion who are event-free at 10 years?</p>
<ul>
<li>Subjects 6 and 7 were event-free at 10 years.</li>
<li>Subjects 2, 9, and 10 had the event before 10 years.</li>
<li>Subjects 1, 3, 4, 5, and 8 were censored before 10 years, so we don’t know whether they had the event or not at 10 years. But we know something about them - that they were each followed for a certain amount of time without the event of interest prior to being censored.</li>
</ul>
<p>Survival analysis techniques provide a way to appropriately account for censored patients in the analysis.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="machine-learning-fundamentals.html#cb5-1" tabindex="-1"></a><span class="co"># install.packages(c(&quot;lubridate&quot;, &quot;ggsurvfit&quot;, &quot;gtsummary&quot;, &quot;tidycmprsk&quot;))</span></span>
<span id="cb5-2"><a href="machine-learning-fundamentals.html#cb5-2" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="machine-learning-fundamentals.html#cb8-1" tabindex="-1"></a><span class="fu">library</span>(ggsurvfit)</span>
<span id="cb8-2"><a href="machine-learning-fundamentals.html#cb8-2" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb8-3"><a href="machine-learning-fundamentals.html#cb8-3" tabindex="-1"></a><span class="fu">library</span>(tidycmprsk)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;tidycmprsk&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:gtsummary&#39;:
## 
##     trial</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="machine-learning-fundamentals.html#cb11-1" tabindex="-1"></a><span class="co"># devtools::install_github(&quot;zabore/condsurv&quot;)</span></span>
<span id="cb11-2"><a href="machine-learning-fundamentals.html#cb11-2" tabindex="-1"></a><span class="fu">library</span>(condsurv)</span></code></pre></div>
<p><strong>The lung dataset</strong></p>
<p>Throughout this section, we will use the <code>lung</code> dataset from the <code>survival</code> package as example data. The data contain subjects with advanced lung cancer from the North Central Cancer Treatment Group. We will focus on the following variables throughout this tutorial:</p>
<pre><code> **time:** Observed survival time in days
 **status:** censoring status 1=censored, 2=dead
 **sex:** 1=Male, 2=Female</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="machine-learning-fundamentals.html#cb13-1" tabindex="-1"></a><span class="fu">head</span>(lung[, <span class="fu">c</span>(<span class="st">&quot;time&quot;</span>, <span class="st">&quot;status&quot;</span>, <span class="st">&quot;sex&quot;</span>)])</span></code></pre></div>
<pre><code>##   time status sex
## 1  306      2   1
## 2  455      2   1
## 3 1010      1   1
## 4  210      2   1
## 5  883      2   1
## 6 1022      1   1</code></pre>
<p>Note that the status is coded in a non-standard way in this dataset. Typically you will see 1=event, 0=censored. Let’s recode it to avoid confusion:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="machine-learning-fundamentals.html#cb15-1" tabindex="-1"></a>lung1 <span class="ot">&lt;-</span> </span>
<span id="cb15-2"><a href="machine-learning-fundamentals.html#cb15-2" tabindex="-1"></a>  lung <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="machine-learning-fundamentals.html#cb15-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-4"><a href="machine-learning-fundamentals.html#cb15-4" tabindex="-1"></a>    <span class="at">status =</span> <span class="fu">recode</span>(status, <span class="st">&#39;1&#39;</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">&#39;2&#39;</span> <span class="ot">=</span> <span class="dv">1</span>)</span>
<span id="cb15-5"><a href="machine-learning-fundamentals.html#cb15-5" tabindex="-1"></a>  )</span>
<span id="cb15-6"><a href="machine-learning-fundamentals.html#cb15-6" tabindex="-1"></a></span>
<span id="cb15-7"><a href="machine-learning-fundamentals.html#cb15-7" tabindex="-1"></a><span class="fu">head</span>(lung[, <span class="fu">c</span>(<span class="st">&quot;time&quot;</span>, <span class="st">&quot;status&quot;</span>, <span class="st">&quot;sex&quot;</span>)])</span></code></pre></div>
<pre><code>##   time status sex
## 1  306      2   1
## 2  455      2   1
## 3 1010      1   1
## 4  210      2   1
## 5  883      2   1
## 6 1022      1   1</code></pre>
<p>Now we have:</p>
<pre><code>time: Observed survival time in days
status: censoring status 0=censored, 1=dead
sex: 1=Male, 2=Female</code></pre>
<p>Note: the <code>Surv()</code> function in the {<code>survival</code>} package accepts by default TRUE/FALSE, where TRUE is event and FALSE is censored; 1/0 where 1 is event and 0 is censored; or 2/1 where 2 is event and 1 is censored. Please take care to ensure the event indicator is properly formatted.</p>
<p><strong>Calculating survival times</strong></p>
<p>Data will often come with start and end dates rather than pre-calculated survival times. The first step is to make sure these are formatted as dates in R.</p>
<p>Let’s create a small example dataset with variables <code>sx_date</code> for surgery date and <code>last_fup_date</code> for the last follow-up date:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="machine-learning-fundamentals.html#cb18-1" tabindex="-1"></a>date_ex <span class="ot">&lt;-</span> </span>
<span id="cb18-2"><a href="machine-learning-fundamentals.html#cb18-2" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb18-3"><a href="machine-learning-fundamentals.html#cb18-3" tabindex="-1"></a>    <span class="at">sx_date =</span> <span class="fu">c</span>(<span class="st">&quot;2007-06-22&quot;</span>, <span class="st">&quot;2004-02-13&quot;</span>, <span class="st">&quot;2010-10-27&quot;</span>), </span>
<span id="cb18-4"><a href="machine-learning-fundamentals.html#cb18-4" tabindex="-1"></a>    <span class="at">last_fup_date =</span> <span class="fu">c</span>(<span class="st">&quot;2017-04-15&quot;</span>, <span class="st">&quot;2018-07-04&quot;</span>, <span class="st">&quot;2016-10-31&quot;</span>)</span>
<span id="cb18-5"><a href="machine-learning-fundamentals.html#cb18-5" tabindex="-1"></a>    )</span>
<span id="cb18-6"><a href="machine-learning-fundamentals.html#cb18-6" tabindex="-1"></a></span>
<span id="cb18-7"><a href="machine-learning-fundamentals.html#cb18-7" tabindex="-1"></a>date_ex</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   sx_date    last_fup_date
##   &lt;chr&gt;      &lt;chr&gt;        
## 1 2007-06-22 2017-04-15   
## 2 2004-02-13 2018-07-04   
## 3 2010-10-27 2016-10-31</code></pre>
<p>We see these are both <code>character</code> variables, but we need them to be formatted as <code>dates.</code></p>
<p>We will use the {<code>lubridate</code>} package to work with dates. In this case, we need to use the <code>ymd()</code> function to change the format, since the dates are currently in the character format where the year comes first, followed by the month, and followed by the day.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="machine-learning-fundamentals.html#cb20-1" tabindex="-1"></a>date_ex1 <span class="ot">&lt;-</span></span>
<span id="cb20-2"><a href="machine-learning-fundamentals.html#cb20-2" tabindex="-1"></a>  date_ex <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="machine-learning-fundamentals.html#cb20-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-4"><a href="machine-learning-fundamentals.html#cb20-4" tabindex="-1"></a>    <span class="at">sx_date =</span> <span class="fu">ymd</span>(sx_date), </span>
<span id="cb20-5"><a href="machine-learning-fundamentals.html#cb20-5" tabindex="-1"></a>    <span class="at">last_fup_date =</span> <span class="fu">ymd</span>(last_fup_date)</span>
<span id="cb20-6"><a href="machine-learning-fundamentals.html#cb20-6" tabindex="-1"></a>    )</span>
<span id="cb20-7"><a href="machine-learning-fundamentals.html#cb20-7" tabindex="-1"></a></span>
<span id="cb20-8"><a href="machine-learning-fundamentals.html#cb20-8" tabindex="-1"></a>date_ex1</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   sx_date    last_fup_date
##   &lt;date&gt;     &lt;date&gt;       
## 1 2007-06-22 2017-04-15   
## 2 2004-02-13 2018-07-04   
## 3 2010-10-27 2016-10-31</code></pre>
<p>Now that the dates are formatted, we need to calculate the difference between start and end dates in some units, usually months or years. Using the {<code>lubridate</code>} package, the operator <code>%--%</code> designates a time interval, which is then converted to the number of elapsed seconds using <code>as.duration()</code> and finally converted to years by dividing by <code>dyears(1)</code>, which gives the number of seconds in a year.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="machine-learning-fundamentals.html#cb22-1" tabindex="-1"></a>date_ex2 <span class="ot">&lt;-</span></span>
<span id="cb22-2"><a href="machine-learning-fundamentals.html#cb22-2" tabindex="-1"></a>  date_ex1 <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="machine-learning-fundamentals.html#cb22-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-4"><a href="machine-learning-fundamentals.html#cb22-4" tabindex="-1"></a>    <span class="at">observed_yrs =</span> <span class="fu">as.duration</span>(sx_date <span class="sc">%--%</span> last_fup_date) <span class="sc">/</span> <span class="fu">dyears</span>(<span class="dv">1</span>)</span>
<span id="cb22-5"><a href="machine-learning-fundamentals.html#cb22-5" tabindex="-1"></a>    )</span>
<span id="cb22-6"><a href="machine-learning-fundamentals.html#cb22-6" tabindex="-1"></a></span>
<span id="cb22-7"><a href="machine-learning-fundamentals.html#cb22-7" tabindex="-1"></a>date_ex2</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   sx_date    last_fup_date observed_yrs
##   &lt;date&gt;     &lt;date&gt;               &lt;dbl&gt;
## 1 2007-06-22 2017-04-15            9.82
## 2 2004-02-13 2018-07-04           14.4 
## 3 2010-10-27 2016-10-31            6.01</code></pre>
<div id="creating-survival-objects-and-curves" class="section level4 hasAnchor" number="2.3.4.1">
<h4><span class="header-section-number">2.3.4.1</span> Creating survival objects and curves<a href="machine-learning-fundamentals.html#creating-survival-objects-and-curves" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Kaplan-Meier method is the most common way to estimate survival times and probabilities. It is a <code>non-parametric</code> approach that results in a step function, where there is a step down each time an event occurs.</p>
<p>Lets see the data again:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="machine-learning-fundamentals.html#cb24-1" tabindex="-1"></a>lung[, <span class="fu">c</span>(<span class="st">&quot;time&quot;</span>, <span class="st">&quot;status&quot;</span>)][<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span></code></pre></div>
<pre><code>##   time status
## 1  306      2
## 2  455      2
## 3 1010      1
## 4  210      2
## 5  883      2</code></pre>
<p>The <code>Surv()</code> function from the {<code>survival</code>} package creates a survival object for use as the response in a model formula. There will be one entry for each subject that is the survival time, which is followed by a + if the subject was censored.</p>
<p>Let’s look at the first 10 observations:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="machine-learning-fundamentals.html#cb26-1" tabindex="-1"></a><span class="fu">Surv</span>(lung<span class="sc">$</span>time, lung<span class="sc">$</span>status)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1]  306   455  1010+  210   883  1022+  310   361   218   166</code></pre>
<p>We see that subject 1 had an event at time 306 days, subject 2 had an event at time 455 days, subject 3 was censored at time 1010 days, etc.</p>
<p>The <code>survfit()</code> function creates survival curves using the Kaplan-Meier method based on a formula. Let’s generate the overall survival curve for the entire cohort, assign it to object s1, and look at the structure using <code>str()</code>:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="machine-learning-fundamentals.html#cb28-1" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung)</span>
<span id="cb28-2"><a href="machine-learning-fundamentals.html#cb28-2" tabindex="-1"></a><span class="fu">str</span>(s1)</span></code></pre></div>
<pre><code>## List of 16
##  $ n        : int 228
##  $ time     : num [1:186] 5 11 12 13 15 26 30 31 53 54 ...
##  $ n.risk   : num [1:186] 228 227 224 223 221 220 219 218 217 215 ...
##  $ n.event  : num [1:186] 1 3 1 2 1 1 1 1 2 1 ...
##  $ n.censor : num [1:186] 0 0 0 0 0 0 0 0 0 0 ...
##  $ surv     : num [1:186] 0.996 0.982 0.978 0.969 0.965 ...
##  $ std.err  : num [1:186] 0.0044 0.00885 0.00992 0.01179 0.01263 ...
##  $ cumhaz   : num [1:186] 0.00439 0.0176 0.02207 0.03103 0.03556 ...
##  $ std.chaz : num [1:186] 0.00439 0.0088 0.00987 0.01173 0.01257 ...
##  $ type     : chr &quot;right&quot;
##  $ logse    : logi TRUE
##  $ conf.int : num 0.95
##  $ conf.type: chr &quot;log&quot;
##  $ lower    : num [1:186] 0.987 0.966 0.959 0.947 0.941 ...
##  $ upper    : num [1:186] 1 1 0.997 0.992 0.989 ...
##  $ call     : language survfit(formula = Surv(time, status) ~ 1, data = lung)
##  - attr(*, &quot;class&quot;)= chr &quot;survfit&quot;</code></pre>
<p><strong>n:</strong> There are 228 subjects in the data.</p>
<p><strong>time:</strong> Distinct time points.</p>
<p><strong>n.risk:</strong> Number of cases that have survived to the time plus the number of cases where the event occurs at the exact time.</p>
<p><strong>n.event:</strong> Number of event happened at the time.</p>
</div>
<div id="kaplan-meier-plotscurves" class="section level4 hasAnchor" number="2.3.4.2">
<h4><span class="header-section-number">2.3.4.2</span> Kaplan-Meier plots/Curves<a href="machine-learning-fundamentals.html#kaplan-meier-plotscurves" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Kaplan Meier curve graphically represent the survival rate or survival function.</p>
<p>We will use the {<code>ggsurvfit</code>} package to generate Kaplan-Meier plots.</p>
<p>This package aims to ease plotting of time-to-event endpoints using the power of the {<code>ggplot2</code>} package. See <a href="http://www.danieldsjoberg.com/ggsurvfit/index.html" class="uri">http://www.danieldsjoberg.com/ggsurvfit/index.html</a> for details.</p>
<p>Note: alternatively, survival plots can be created using base R or the {<code>survminer</code>} package.</p>
<p>The {<code>ggsurvfit</code>} package works best if you create the <code>survfit</code> object using the included <code>ggsurvfit::survfit2()</code> function, which uses the same syntax to what we saw previously with <code>survival::survfit()</code>.</p>
<p>The <code>ggsurvfit::survfit2()</code> tracks the environment from the function call, which allows the plot to have better default values for labeling and p-value reporting.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="machine-learning-fundamentals.html#cb30-1" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="machine-learning-fundamentals.html#cb30-2" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="machine-learning-fundamentals.html#cb30-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-4"><a href="machine-learning-fundamentals.html#cb30-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>,</span>
<span id="cb30-5"><a href="machine-learning-fundamentals.html#cb30-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Overall survival probability&quot;</span></span>
<span id="cb30-6"><a href="machine-learning-fundamentals.html#cb30-6" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The default plot in <code>ggsurvfit()</code> shows the step function only.</p>
<p>We can add the confidence interval using <code>add_confidence_interval()</code>:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="machine-learning-fundamentals.html#cb31-1" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="machine-learning-fundamentals.html#cb31-2" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb31-3"><a href="machine-learning-fundamentals.html#cb31-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb31-4"><a href="machine-learning-fundamentals.html#cb31-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>,</span>
<span id="cb31-5"><a href="machine-learning-fundamentals.html#cb31-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Overall survival probability&quot;</span></span>
<span id="cb31-6"><a href="machine-learning-fundamentals.html#cb31-6" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb31-7"><a href="machine-learning-fundamentals.html#cb31-7" tabindex="-1"></a>  <span class="fu">add_confidence_interval</span>()</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Typically we will also want to see the numbers at risk in a table below the x-axis.</p>
<p>We can add this using <code>add_risktable()</code>:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="machine-learning-fundamentals.html#cb32-1" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="machine-learning-fundamentals.html#cb32-2" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="machine-learning-fundamentals.html#cb32-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb32-4"><a href="machine-learning-fundamentals.html#cb32-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>,</span>
<span id="cb32-5"><a href="machine-learning-fundamentals.html#cb32-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Overall survival probability&quot;</span></span>
<span id="cb32-6"><a href="machine-learning-fundamentals.html#cb32-6" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb32-7"><a href="machine-learning-fundamentals.html#cb32-7" tabindex="-1"></a>  <span class="fu">add_confidence_interval</span>() <span class="sc">+</span></span>
<span id="cb32-8"><a href="machine-learning-fundamentals.html#cb32-8" tabindex="-1"></a>  <span class="fu">add_risktable</span>()</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Plots can be customized using many standard {ggplot2} options.</p>
</div>
<div id="estimating-x-year-survival" class="section level4 hasAnchor" number="2.3.4.3">
<h4><span class="header-section-number">2.3.4.3</span> Estimating x-year survival<a href="machine-learning-fundamentals.html#estimating-x-year-survival" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One quantity often of interest in a survival analysis is the probability of surviving beyond a certain number of years, x.</p>
<p>For example, to estimate the probability of surviving to 1 year, use summary with the times argument
(Note: the time variable in the lung data is actually in days, so we need to use <code>times = 365.25</code>)</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="machine-learning-fundamentals.html#cb33-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung), <span class="at">times =</span> <span class="fl">365.25</span>)</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ 1, data = lung)
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##   365     65     121    0.409  0.0358        0.345        0.486</code></pre>
<pre><code>We find that the 1-year probability of survival in this study is 41%.</code></pre>
<p>The associated lower and upper bounds of the 95% confidence interval are also displayed.</p>
<p>The 1-year survival probability is the point on the y-axis that corresponds to 1
year on the x-axis for the survival curve.</p>
<p><img src="figs/survival3.png" /></p>
<p>What happens if you use a “naive” estimate? Here “naive” means that the patients who were censored prior to 1-year are considered event-free and included in the denominator.</p>
<p>121 of the 228 patients in the lung data died by 1 year so the “naive” estimate is calculated as:</p>
<p><span class="math display">\[(1−\frac{121}{228})×100=47\%\]</span></p>
<p>You get an incorrect estimate of the 1-year probability of survival when you ignore the fact that 42 patients were censored before 1-year.</p>
<p>Recall the correct estimate of the 1-year probability of survival, accounting for censoring using the Kaplan-Meier method, was 41%.</p>
<p>Ignoring censoring leads to an overestimate of the overall survival probability.</p>
<p>Imagine two studies, each with 228 subjects. There are 165 deaths in each study. Censoring is ignored in one (blue line), censoring is accounted for in the other (yellow line).</p>
<p>The censored subjects only contribute information for a portion of the follow-up time, and then fall out of the risk set, thus pulling down the cumulative probability of survival. Ignoring censoring erroneously treats patients who are censored as part of the risk set for the entire follow-up period.</p>
<p><img src="figs/survival4.png" /></p>
<p>We can produce nice tables of x-time survival probability estimates using the <code>tbl_survfit()</code> function from the {<code>gtsummary</code>} package:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="machine-learning-fundamentals.html#cb36-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="machine-learning-fundamentals.html#cb36-2" tabindex="-1"></a>  <span class="fu">tbl_survfit</span>(</span>
<span id="cb36-3"><a href="machine-learning-fundamentals.html#cb36-3" tabindex="-1"></a>    <span class="at">times =</span> <span class="fl">365.25</span>,</span>
<span id="cb36-4"><a href="machine-learning-fundamentals.html#cb36-4" tabindex="-1"></a>    <span class="at">label_header =</span> <span class="st">&quot;**1-year survival (95% CI)**&quot;</span></span>
<span id="cb36-5"><a href="machine-learning-fundamentals.html#cb36-5" tabindex="-1"></a>  )</span></code></pre></div>
<div id="shdidzklpp" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#shdidzklpp table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#shdidzklpp thead, #shdidzklpp tbody, #shdidzklpp tfoot, #shdidzklpp tr, #shdidzklpp td, #shdidzklpp th {
  border-style: none;
}

#shdidzklpp p {
  margin: 0;
  padding: 0;
}

#shdidzklpp .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#shdidzklpp .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#shdidzklpp .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#shdidzklpp .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#shdidzklpp .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#shdidzklpp .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#shdidzklpp .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#shdidzklpp .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#shdidzklpp .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#shdidzklpp .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#shdidzklpp .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#shdidzklpp .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#shdidzklpp .gt_spanner_row {
  border-bottom-style: hidden;
}

#shdidzklpp .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#shdidzklpp .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#shdidzklpp .gt_from_md > :first-child {
  margin-top: 0;
}

#shdidzklpp .gt_from_md > :last-child {
  margin-bottom: 0;
}

#shdidzklpp .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#shdidzklpp .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#shdidzklpp .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#shdidzklpp .gt_row_group_first td {
  border-top-width: 2px;
}

#shdidzklpp .gt_row_group_first th {
  border-top-width: 2px;
}

#shdidzklpp .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#shdidzklpp .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#shdidzklpp .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#shdidzklpp .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#shdidzklpp .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#shdidzklpp .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#shdidzklpp .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#shdidzklpp .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#shdidzklpp .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#shdidzklpp .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#shdidzklpp .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#shdidzklpp .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#shdidzklpp .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#shdidzklpp .gt_left {
  text-align: left;
}

#shdidzklpp .gt_center {
  text-align: center;
}

#shdidzklpp .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#shdidzklpp .gt_font_normal {
  font-weight: normal;
}

#shdidzklpp .gt_font_bold {
  font-weight: bold;
}

#shdidzklpp .gt_font_italic {
  font-style: italic;
}

#shdidzklpp .gt_super {
  font-size: 65%;
}

#shdidzklpp .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#shdidzklpp .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#shdidzklpp .gt_indent_1 {
  text-indent: 5px;
}

#shdidzklpp .gt_indent_2 {
  text-indent: 10px;
}

#shdidzklpp .gt_indent_3 {
  text-indent: 15px;
}

#shdidzklpp .gt_indent_4 {
  text-indent: 20px;
}

#shdidzklpp .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;1-year survival (95% CI)&lt;/strong&gt;"><strong>1-year survival (95% CI)</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Overall</td>
<td headers="stat_1" class="gt_row gt_center">41% (34%, 49%)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
<div id="estimating-median-survival-time" class="section level4 hasAnchor" number="2.3.4.4">
<h4><span class="header-section-number">2.3.4.4</span> Estimating median survival time<a href="machine-learning-fundamentals.html#estimating-median-survival-time" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Another quantity often of interest in a survival analysis is the average survival time, which we quantify using the median. Survival times are not expected to be normally distributed so the mean is not an appropriate summary.</p>
<p>We can obtain the median survival directly from the <code>survfit</code> object:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="machine-learning-fundamentals.html#cb37-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung)</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ 1, data = lung)
## 
##        n events median 0.95LCL 0.95UCL
## [1,] 228    165    310     285     363</code></pre>
<p>We see the median survival time is 310 days The lower and upper bounds of the 95% confidence interval are also displayed.</p>
<p>Median survival is the time corresponding to a survival probability of 0.5:</p>
<p><img src="figs/survival5.png" /></p>
<p>What happens if you use a “naive” estimate? Here “naive” means that you exclude the censored patients from the calculation entirely to estimate median survival time among the patients who have had the event.</p>
<p>Summarize the median survival time among the 165 patients who died:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="machine-learning-fundamentals.html#cb39-1" tabindex="-1"></a>lung <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="machine-learning-fundamentals.html#cb39-2" tabindex="-1"></a>  <span class="fu">filter</span>(status <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb39-3"><a href="machine-learning-fundamentals.html#cb39-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_surv =</span> <span class="fu">median</span>(time))</span></code></pre></div>
<pre><code>##   median_surv
## 1         284</code></pre>
<p>You get an incorrect estimate of median survival time of 284 days when you ignore the fact that censored patients also contribute follow-up time.</p>
<p>Recall the correct estimate of median survival time is 310 days.</p>
<p>Ignoring censoring will lead to an underestimate of median survival time because the follow-up time that censored patients contribute is excluded (blue line). The true survival curve accounting for censoring in the lung data is shown in yellow for comparison.</p>
<p><img src="figs/survival6.png" /></p>
<p>We can produce nice tables of median survival time estimates using the <code>tbl_survfit()</code> function from the {<code>gtsummary</code>} package:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="machine-learning-fundamentals.html#cb41-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="machine-learning-fundamentals.html#cb41-2" tabindex="-1"></a>  <span class="fu">tbl_survfit</span>(</span>
<span id="cb41-3"><a href="machine-learning-fundamentals.html#cb41-3" tabindex="-1"></a>    <span class="at">probs =</span> <span class="fl">0.5</span>,</span>
<span id="cb41-4"><a href="machine-learning-fundamentals.html#cb41-4" tabindex="-1"></a>    <span class="at">label_header =</span> <span class="st">&quot;**Median survival (95% CI)**&quot;</span></span>
<span id="cb41-5"><a href="machine-learning-fundamentals.html#cb41-5" tabindex="-1"></a>  )</span></code></pre></div>
<div id="xgdzttuaph" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xgdzttuaph table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xgdzttuaph thead, #xgdzttuaph tbody, #xgdzttuaph tfoot, #xgdzttuaph tr, #xgdzttuaph td, #xgdzttuaph th {
  border-style: none;
}

#xgdzttuaph p {
  margin: 0;
  padding: 0;
}

#xgdzttuaph .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xgdzttuaph .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xgdzttuaph .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xgdzttuaph .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xgdzttuaph .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xgdzttuaph .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xgdzttuaph .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xgdzttuaph .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xgdzttuaph .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xgdzttuaph .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xgdzttuaph .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xgdzttuaph .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xgdzttuaph .gt_spanner_row {
  border-bottom-style: hidden;
}

#xgdzttuaph .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xgdzttuaph .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xgdzttuaph .gt_from_md > :first-child {
  margin-top: 0;
}

#xgdzttuaph .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xgdzttuaph .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xgdzttuaph .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xgdzttuaph .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xgdzttuaph .gt_row_group_first td {
  border-top-width: 2px;
}

#xgdzttuaph .gt_row_group_first th {
  border-top-width: 2px;
}

#xgdzttuaph .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xgdzttuaph .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xgdzttuaph .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xgdzttuaph .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xgdzttuaph .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xgdzttuaph .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xgdzttuaph .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xgdzttuaph .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xgdzttuaph .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xgdzttuaph .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xgdzttuaph .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xgdzttuaph .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xgdzttuaph .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xgdzttuaph .gt_left {
  text-align: left;
}

#xgdzttuaph .gt_center {
  text-align: center;
}

#xgdzttuaph .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xgdzttuaph .gt_font_normal {
  font-weight: normal;
}

#xgdzttuaph .gt_font_bold {
  font-weight: bold;
}

#xgdzttuaph .gt_font_italic {
  font-style: italic;
}

#xgdzttuaph .gt_super {
  font-size: 65%;
}

#xgdzttuaph .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xgdzttuaph .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xgdzttuaph .gt_indent_1 {
  text-indent: 5px;
}

#xgdzttuaph .gt_indent_2 {
  text-indent: 10px;
}

#xgdzttuaph .gt_indent_3 {
  text-indent: 15px;
}

#xgdzttuaph .gt_indent_4 {
  text-indent: 20px;
}

#xgdzttuaph .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Median survival (95% CI)&lt;/strong&gt;"><strong>Median survival (95% CI)</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Overall</td>
<td headers="stat_1" class="gt_row gt_center">310 (285, 363)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
<div id="comparing-survival-times-between-groups" class="section level4 hasAnchor" number="2.3.4.5">
<h4><span class="header-section-number">2.3.4.5</span> Comparing survival times between groups<a href="machine-learning-fundamentals.html#comparing-survival-times-between-groups" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can conduct between-group significance tests using a <code>log-rank test</code>.</p>
<p>The log-rank test equally weights observations over the entire follow-up time and is the most common way to compare survival times between groups. There are versions that more heavily weight the early or late follow-up that could be more appropriate depending on the research question (see <code>?survdiff</code> for different test options).</p>
<p>We get the log-rank p-value using the <code>survdiff</code> function. For example, we can test whether there was a difference in survival time according to sex in the lung data:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="machine-learning-fundamentals.html#cb42-1" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(time, status) ~ sex, data = lung)
## 
##         N Observed Expected (O-E)^2/E (O-E)^2/V
## sex=1 138      112     91.6      4.55      10.3
## sex=2  90       53     73.4      5.68      10.3
## 
##  Chisq= 10.3  on 1 degrees of freedom, p= 0.001</code></pre>
<p>We see that there was a significant difference in overall survival according to sex in the lung data, with a p-value of <code>p = 0.001</code>.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="machine-learning-fundamentals.html#cb44-1" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;survival&quot;</span>)</span>
<span id="cb44-2"><a href="machine-learning-fundamentals.html#cb44-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;survminer&quot;</span>)</span>
<span id="cb44-3"><a href="machine-learning-fundamentals.html#cb44-3" tabindex="-1"></a></span>
<span id="cb44-4"><a href="machine-learning-fundamentals.html#cb44-4" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung)</span>
<span id="cb44-5"><a href="machine-learning-fundamentals.html#cb44-5" tabindex="-1"></a></span>
<span id="cb44-6"><a href="machine-learning-fundamentals.html#cb44-6" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit, <span class="at">data =</span> lung)</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="machine-learning-fundamentals.html#cb45-1" tabindex="-1"></a><span class="fu">ggsurvplot</span>(</span>
<span id="cb45-2"><a href="machine-learning-fundamentals.html#cb45-2" tabindex="-1"></a>  fit,</span>
<span id="cb45-3"><a href="machine-learning-fundamentals.html#cb45-3" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb45-4"><a href="machine-learning-fundamentals.html#cb45-4" tabindex="-1"></a>  <span class="at">size =</span> <span class="dv">1</span>,                 <span class="co"># change line size</span></span>
<span id="cb45-5"><a href="machine-learning-fundamentals.html#cb45-5" tabindex="-1"></a>  <span class="at">palette =</span></span>
<span id="cb45-6"><a href="machine-learning-fundamentals.html#cb45-6" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">&quot;#E7B800&quot;</span>, <span class="st">&quot;#2E9FDF&quot;</span>),<span class="co"># custom color palettes</span></span>
<span id="cb45-7"><a href="machine-learning-fundamentals.html#cb45-7" tabindex="-1"></a>  <span class="at">conf.int =</span> <span class="cn">TRUE</span>,          <span class="co"># Add confidence interval</span></span>
<span id="cb45-8"><a href="machine-learning-fundamentals.html#cb45-8" tabindex="-1"></a>  <span class="at">pval =</span> <span class="cn">TRUE</span>,              <span class="co"># Add p-value</span></span>
<span id="cb45-9"><a href="machine-learning-fundamentals.html#cb45-9" tabindex="-1"></a>  <span class="at">risk.table =</span> <span class="cn">TRUE</span>,        <span class="co"># Add risk table</span></span>
<span id="cb45-10"><a href="machine-learning-fundamentals.html#cb45-10" tabindex="-1"></a>  <span class="at">risk.table.col =</span> <span class="st">&quot;strata&quot;</span>,<span class="co"># Risk table color by groups</span></span>
<span id="cb45-11"><a href="machine-learning-fundamentals.html#cb45-11" tabindex="-1"></a>  <span class="at">legend.labs =</span></span>
<span id="cb45-12"><a href="machine-learning-fundamentals.html#cb45-12" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>),    <span class="co"># Change legend labels</span></span>
<span id="cb45-13"><a href="machine-learning-fundamentals.html#cb45-13" tabindex="-1"></a>  <span class="at">risk.table.height =</span> <span class="fl">0.25</span>, <span class="co"># Useful to change when you have multiple groups</span></span>
<span id="cb45-14"><a href="machine-learning-fundamentals.html#cb45-14" tabindex="-1"></a>  <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()      <span class="co"># Change ggplot2 theme</span></span>
<span id="cb45-15"><a href="machine-learning-fundamentals.html#cb45-15" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="the-cox-regression-model" class="section level4 hasAnchor" number="2.3.4.6">
<h4><span class="header-section-number">2.3.4.6</span> The Cox regression model<a href="machine-learning-fundamentals.html#the-cox-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We may want to quantify an effect size for a single variable, or include more than one variable into a regression model to account for the effects of multiple variables.</p>
<p>The Cox regression model is a semi-parametric model that can be used to fit univariable and multivariable regression models that have survival outcomes.</p>
<p><span class="math display">\[h(t|Xi)=h0(t)exp(β1Xi1+⋯+βpXip)\]</span></p>
<dl>
<dt><span class="math inline">\(h(t)\)</span></dt>
<dd>
hazard, or the instantaneous rate at which events occur h0(t)
</dd>
<dd>
underlying baseline hazard
</dd>
</dl>
<p>Some key assumptions of the model:</p>
<p>non-informative censoring
proportional hazards</p>
<p><strong>Note:</strong> parametric regression models for survival outcomes are also available, but they won’t be addressed here.</p>
<p>We can fit regression models for survival data using the <code>coxph()</code> function from the {<code>survival</code>} package, which takes a <code>Surv()</code> object on the left hand side and has standard syntax for regression formulas in R on the right hand side.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="machine-learning-fundamentals.html#cb46-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex, data = lung)
## 
##        coef exp(coef) se(coef)      z       p
## sex -0.5310    0.5880   0.1672 -3.176 0.00149
## 
## Likelihood ratio test=10.63  on 1 df, p=0.001111
## n= 228, number of events= 165</code></pre>
<p>We can obtain tables of results using the <code>tbl_regression()</code> function from the {<code>gtsummary</code>} package, with the option to <code>exponentiate</code> set to <code>TRUE</code> to return the hazard ratio rather than the log hazard ratio:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="machine-learning-fundamentals.html#cb48-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="machine-learning-fundamentals.html#cb48-2" tabindex="-1"></a>  <span class="fu">tbl_regression</span>(<span class="at">exp =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="hucnmvxhyr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hucnmvxhyr table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hucnmvxhyr thead, #hucnmvxhyr tbody, #hucnmvxhyr tfoot, #hucnmvxhyr tr, #hucnmvxhyr td, #hucnmvxhyr th {
  border-style: none;
}

#hucnmvxhyr p {
  margin: 0;
  padding: 0;
}

#hucnmvxhyr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hucnmvxhyr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hucnmvxhyr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hucnmvxhyr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hucnmvxhyr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hucnmvxhyr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hucnmvxhyr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hucnmvxhyr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hucnmvxhyr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hucnmvxhyr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hucnmvxhyr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hucnmvxhyr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hucnmvxhyr .gt_spanner_row {
  border-bottom-style: hidden;
}

#hucnmvxhyr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hucnmvxhyr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hucnmvxhyr .gt_from_md > :first-child {
  margin-top: 0;
}

#hucnmvxhyr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hucnmvxhyr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hucnmvxhyr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hucnmvxhyr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hucnmvxhyr .gt_row_group_first td {
  border-top-width: 2px;
}

#hucnmvxhyr .gt_row_group_first th {
  border-top-width: 2px;
}

#hucnmvxhyr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hucnmvxhyr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hucnmvxhyr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hucnmvxhyr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hucnmvxhyr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hucnmvxhyr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hucnmvxhyr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hucnmvxhyr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hucnmvxhyr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hucnmvxhyr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hucnmvxhyr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hucnmvxhyr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hucnmvxhyr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hucnmvxhyr .gt_left {
  text-align: left;
}

#hucnmvxhyr .gt_center {
  text-align: center;
}

#hucnmvxhyr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hucnmvxhyr .gt_font_normal {
  font-weight: normal;
}

#hucnmvxhyr .gt_font_bold {
  font-weight: bold;
}

#hucnmvxhyr .gt_font_italic {
  font-style: italic;
}

#hucnmvxhyr .gt_super {
  font-size: 65%;
}

#hucnmvxhyr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hucnmvxhyr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hucnmvxhyr .gt_indent_1 {
  text-indent: 5px;
}

#hucnmvxhyr .gt_indent_2 {
  text-indent: 10px;
}

#hucnmvxhyr .gt_indent_3 {
  text-indent: 15px;
}

#hucnmvxhyr .gt_indent_4 {
  text-indent: 20px;
}

#hucnmvxhyr .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;HR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>HR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;p-value&lt;/strong&gt;"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">sex</td>
<td headers="estimate" class="gt_row gt_center">0.59</td>
<td headers="ci" class="gt_row gt_center">0.42, 0.82</td>
<td headers="p.value" class="gt_row gt_center">0.001</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> HR = Hazard Ratio, CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
<p>The quantity of interest from a Cox regression model is a hazard ratio (HR). The HR represents the ratio of hazards between two groups at any particular point in time.</p>
<p>The HR is interpreted as the instantaneous rate of occurrence of the event of interest in those who are still at risk for the event. It is not a risk, though it is commonly mis-interpreted as such. If you have a regression parameter β, then <span class="math inline">\(HR = exp(β)\)</span></p>
<p>A HR &lt; 1 indicates reduced hazard of death whereas a HR &gt; 1 indicates an increased hazard of death.</p>
<p>So the HR = 0.59 implies that 0.59 times as many females are dying as males, at any given time. Stated differently, females have a significantly lower hazard of death than males in these data.</p>

</div>
</div>
<div id="prosper-loan-data" class="section level3 hasAnchor" number="2.3.5">
<h3><span class="header-section-number">2.3.5</span> Prosper Loan data<a href="machine-learning-fundamentals.html#prosper-loan-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="machine-learning-fundamentals.html#cb49-1" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;data.table&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:lubridate&#39;:
## 
##     hour, isoweek, mday, minute, month, quarter, second, wday, week,
##     yday, year</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     between, first, last</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="machine-learning-fundamentals.html#cb53-1" tabindex="-1"></a><span class="co"># web &lt;- &quot;https://s3.amazonaws.com/udacity-hosted-downloads/ud651/prosperLoanData.csv&quot;</span></span>
<span id="cb53-2"><a href="machine-learning-fundamentals.html#cb53-2" tabindex="-1"></a><span class="co"># loan &lt;- fread(web)</span></span>
<span id="cb53-3"><a href="machine-learning-fundamentals.html#cb53-3" tabindex="-1"></a></span>
<span id="cb53-4"><a href="machine-learning-fundamentals.html#cb53-4" tabindex="-1"></a><span class="co"># head(loan)[, c(51, 65, 6, 7, 19, 18, 50)]</span></span></code></pre></div>

</div>
<div id="customer-churn" class="section level3 hasAnchor" number="2.3.6">
<h3><span class="header-section-number">2.3.6</span> Customer Churn<a href="machine-learning-fundamentals.html#customer-churn" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It usually costs more to acquire a customer than it does to retain a customer.</p>
<p>Focusing on customer retention enables companies to maximize customer revenue over their lifetime.</p>
<p>These models are seldom done optimally as they rely on binary classification flags (churn yes or no). Churn classification models do not tell WHEN a customer is likely to leave but only indicate that it’s going to happen within a certain number of days or months.</p>
<p>In the churn classification model, we don’t usually account for the differences in time.</p>
<p>It is probably a mistake to treat a customer that is at risk of leaving in 40 days the same as a customer that remains for over a 100 days. Traditional churn modeling does not make this differentiation.</p>
<p><img src="figs/churn1.png" /></p>
<p>As it fails to account for time, we have no clear idea at what point a marketing intervention is needed and it causes preventable customer attrition.</p>
<p>The only point in time here is the “within 40 days” threshold. As it fails to account for time, we have no clear idea at what point a marketing intervention is needed and it causes preventable customer attrition.</p>
<div id="re-framing-the-problem-to-know-when" class="section level4 hasAnchor" number="2.3.6.1">
<h4><span class="header-section-number">2.3.6.1</span> Re-framing the Problem to Know When<a href="machine-learning-fundamentals.html#re-framing-the-problem-to-know-when" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Rather then use a binary classifier, we are going to re-frame the problem as time-dependent one. This enables us to intervene at the right time to stop customer attrition before it happens.</p>
<p>No longer relying on thresholds, we now set churn as continuous time conditioned event. As the below graph shows, we now know the time that attrition risk is most likely to happen.</p>
<p><img src="figs/churn2.png" /></p>
<p>No longer is time held constant, we now track risk over time to determine when a marketing intervention is needed to retain the customer.</p>
<p>If we model for both the time and event, the right moment to intervene and prevent attrition is apparent. A modeling technique called <code>Survival Analysis</code> allows for us to do this and with the advent of modern Machine Learning, it’s now a trivial task.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb54-1"><a href="machine-learning-fundamentals.html#cb54-1" tabindex="-1"></a><span class="co"># %reload_ext autoreload</span></span>
<span id="cb54-2"><a href="machine-learning-fundamentals.html#cb54-2" tabindex="-1"></a><span class="co"># %autoreload 2</span></span>
<span id="cb54-3"><a href="machine-learning-fundamentals.html#cb54-3" tabindex="-1"></a><span class="co"># %matplotlib inline</span></span>
<span id="cb54-4"><a href="machine-learning-fundamentals.html#cb54-4" tabindex="-1"></a></span>
<span id="cb54-5"><a href="machine-learning-fundamentals.html#cb54-5" tabindex="-1"></a><span class="im">import</span> xgboost <span class="im">as</span> xgb</span>
<span id="cb54-6"><a href="machine-learning-fundamentals.html#cb54-6" tabindex="-1"></a><span class="im">import</span> shap</span>
<span id="cb54-7"><a href="machine-learning-fundamentals.html#cb54-7" tabindex="-1"></a><span class="im">import</span> sksurv.metrics <span class="im">as</span> surv_metrics</span>
<span id="cb54-8"><a href="machine-learning-fundamentals.html#cb54-8" tabindex="-1"></a><span class="im">from</span> sksurv.datasets <span class="im">import</span> get_x_y</span>
<span id="cb54-9"><a href="machine-learning-fundamentals.html#cb54-9" tabindex="-1"></a><span class="im">from</span> lifelines <span class="im">import</span> KaplanMeierFitter</span>
<span id="cb54-10"><a href="machine-learning-fundamentals.html#cb54-10" tabindex="-1"></a><span class="im">from</span> lifelines.plotting <span class="im">import</span> plot_lifetimes</span>
<span id="cb54-11"><a href="machine-learning-fundamentals.html#cb54-11" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb54-12"><a href="machine-learning-fundamentals.html#cb54-12" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb54-13"><a href="machine-learning-fundamentals.html#cb54-13" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb54-14"><a href="machine-learning-fundamentals.html#cb54-14" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb54-15"><a href="machine-learning-fundamentals.html#cb54-15" tabindex="-1"></a><span class="im">from</span> sklearn.compose <span class="im">import</span> ColumnTransformer</span>
<span id="cb54-16"><a href="machine-learning-fundamentals.html#cb54-16" tabindex="-1"></a><span class="im">from</span> sklearn.exceptions <span class="im">import</span> DataConversionWarning</span>
<span id="cb54-17"><a href="machine-learning-fundamentals.html#cb54-17" tabindex="-1"></a><span class="im">from</span> sklearn.impute <span class="im">import</span> SimpleImputer</span>
<span id="cb54-18"><a href="machine-learning-fundamentals.html#cb54-18" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb54-19"><a href="machine-learning-fundamentals.html#cb54-19" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb54-20"><a href="machine-learning-fundamentals.html#cb54-20" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> OneHotEncoder, StandardScaler</span>
<span id="cb54-21"><a href="machine-learning-fundamentals.html#cb54-21" tabindex="-1"></a></span>
<span id="cb54-22"><a href="machine-learning-fundamentals.html#cb54-22" tabindex="-1"></a></span>
<span id="cb54-23"><a href="machine-learning-fundamentals.html#cb54-23" tabindex="-1"></a></span>
<span id="cb54-24"><a href="machine-learning-fundamentals.html#cb54-24" tabindex="-1"></a>plt.rcParams[<span class="st">&#39;figure.figsize&#39;</span>] <span class="op">=</span> [<span class="fl">7.2</span>, <span class="fl">4.8</span>]</span>
<span id="cb54-25"><a href="machine-learning-fundamentals.html#cb54-25" tabindex="-1"></a>pd.set_option(<span class="st">&quot;display.float_format&quot;</span>, <span class="kw">lambda</span> x: <span class="st">&quot;</span><span class="sc">%.4f</span><span class="st">&quot;</span> <span class="op">%</span> x)</span>
<span id="cb54-26"><a href="machine-learning-fundamentals.html#cb54-26" tabindex="-1"></a></span>
<span id="cb54-27"><a href="machine-learning-fundamentals.html#cb54-27" tabindex="-1"></a>sns.set_style(<span class="st">&#39;darkgrid&#39;</span>)</span>
<span id="cb54-28"><a href="machine-learning-fundamentals.html#cb54-28" tabindex="-1"></a></span>
<span id="cb54-29"><a href="machine-learning-fundamentals.html#cb54-29" tabindex="-1"></a>SEED <span class="op">=</span> <span class="dv">123</span></span></code></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb55-1"><a href="machine-learning-fundamentals.html#cb55-1" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">&quot;../../data/churn.txt&quot;</span>)</span>
<span id="cb55-2"><a href="machine-learning-fundamentals.html#cb55-2" tabindex="-1"></a><span class="co"># denoting churn and duration</span></span>
<span id="cb55-3"><a href="machine-learning-fundamentals.html#cb55-3" tabindex="-1"></a>df[<span class="st">&quot;event&quot;</span>] <span class="op">=</span> np.where(df[<span class="st">&quot;churn?&quot;</span>] <span class="op">==</span> <span class="st">&quot;False.&quot;</span>, <span class="dv">0</span>, <span class="dv">1</span>) </span>
<span id="cb55-4"><a href="machine-learning-fundamentals.html#cb55-4" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>{<span class="st">&quot;account_length&quot;</span>: <span class="st">&quot;duration&quot;</span>})</span>
<span id="cb55-5"><a href="machine-learning-fundamentals.html#cb55-5" tabindex="-1"></a><span class="kw">del</span> df[<span class="st">&#39;churn?&#39;</span>]</span>
<span id="cb55-6"><a href="machine-learning-fundamentals.html#cb55-6" tabindex="-1"></a>df <span class="op">=</span> df.dropna()</span>
<span id="cb55-7"><a href="machine-learning-fundamentals.html#cb55-7" tabindex="-1"></a>df <span class="op">=</span> df.drop_duplicates()</span>
<span id="cb55-8"><a href="machine-learning-fundamentals.html#cb55-8" tabindex="-1"></a>df.head()</span></code></pre></div>
<div class="sourceCode" id="cb56"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb56-1"><a href="machine-learning-fundamentals.html#cb56-1" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Total Records:&quot;</span>,df.shape[<span class="dv">0</span>],<span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb56-2"><a href="machine-learning-fundamentals.html#cb56-2" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Percent Churn Rate:&quot;</span>,df.event.mean())</span>
<span id="cb56-3"><a href="machine-learning-fundamentals.html#cb56-3" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;&quot;</span>)</span>
<span id="cb56-4"><a href="machine-learning-fundamentals.html#cb56-4" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Duration Intervals&quot;</span>)</span>
<span id="cb56-5"><a href="machine-learning-fundamentals.html#cb56-5" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">&#39;duration&#39;</span>].describe())</span></code></pre></div>
<p>For Survival models data is different from a traditional classification problem and requires:
- A Censor — For our purposes these are customers who’ve yet to churn. Read about right censoring here.</p>
<ul>
<li><p>Duration — The duration or time t of the customer’s activity. In this case, it’s Account Length in days.</p></li>
<li><p>Event — The binary target, in this case if they terminated their phone plan marked by Churn? .</p></li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb57-1"><a href="machine-learning-fundamentals.html#cb57-1" tabindex="-1"></a>ax <span class="op">=</span> plot_lifetimes(df.head(<span class="dv">10</span>)[<span class="st">&#39;duration&#39;</span>], df.head(<span class="dv">10</span>)[<span class="st">&#39;event&#39;</span>])</span>
<span id="cb57-2"><a href="machine-learning-fundamentals.html#cb57-2" tabindex="-1"></a>_<span class="op">=</span>ax.set_xlabel(<span class="st">&quot;Duration: Account Length (days)&quot;</span>) _<span class="op">=</span>ax.set_ylabel(<span class="st">&quot;Customer Number&quot;</span>) _<span class="op">=</span>ax.set_title(<span class="st">&quot;Observed Customer Attrition&quot;</span>)</span></code></pre></div>
<p><img src="figs/churn3.png" /></p>
<p>In the above plot, the red lines indicates when a customer has left with the dots indicating the specific point in time.</p>
<p>Blue lines are customers that are still active up to the time measured on the x-axis in Duration.</p>
<p>Here we see that customer number 8 did not attrit until up to 195 days, with customer numbers 0 and 4 leaving in 163 and 146 days respectively. All other customers are still active.</p>
<p>Notice how all customers are set on the same time scale because the data is analytically aligned. Each customer might have come in at different times but we’ve set the days as the same.</p>
<p>This is what allowed us to right-censor the data on the churn event. Real world data needs both censoring and aligning before modeling can begin.</p>
</div>
<div id="the-risk-of-churn" class="section level4 hasAnchor" number="2.3.6.2">
<h4><span class="header-section-number">2.3.6.2</span> The Risk of Churn<a href="machine-learning-fundamentals.html#the-risk-of-churn" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A more informative approach might be to estimate the Survival Function or the time in days a customer has until they attrit. For this purpose, we will use a Kaplan Meier Estimator to calculate how long until attrition occurs. The estimator is defined as:</p>
<p><img src="figs/churn4.png" /></p>
<p>Where <span class="math inline">\(𝑑_𝑖\)</span> are the number of churn events at time <span class="math inline">\(𝑡\)</span> and <span class="math inline">\(𝑛_𝑖\)</span> is the number of customers at risk of churn just prior to time <span class="math inline">\(𝑡\)</span>.</p>
<p>We will use the great python package <code>lifelines</code> to plot the Survival Function as the function is a component of the final churn model.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb58-1"><a href="machine-learning-fundamentals.html#cb58-1" tabindex="-1"></a>kmf <span class="op">=</span> KaplanMeierFitter()</span>
<span id="cb58-2"><a href="machine-learning-fundamentals.html#cb58-2" tabindex="-1"></a>kmf.fit(df[<span class="st">&#39;duration&#39;</span>], event_observed<span class="op">=</span>df[<span class="st">&#39;event&#39;</span>])</span>
<span id="cb58-3"><a href="machine-learning-fundamentals.html#cb58-3" tabindex="-1"></a>kmf.plot_survival_function()</span>
<span id="cb58-4"><a href="machine-learning-fundamentals.html#cb58-4" tabindex="-1"></a></span>
<span id="cb58-5"><a href="machine-learning-fundamentals.html#cb58-5" tabindex="-1"></a>_<span class="op">=</span>plt.title(<span class="st">&#39;Survival Function for Telco Churn&#39;</span>)<span class="op">;</span> _<span class="op">=</span>plt.xlabel(<span class="st">&quot;Duration: Account Length (days)&quot;</span>)</span>
<span id="cb58-6"><a href="machine-learning-fundamentals.html#cb58-6" tabindex="-1"></a>_<span class="op">=</span>plt.ylabel(<span class="st">&quot;Churn Risk (Percent Churned)&quot;</span>) </span>
<span id="cb58-7"><a href="machine-learning-fundamentals.html#cb58-7" tabindex="-1"></a>_<span class="op">=</span>plt.axvline(x<span class="op">=</span>kmf.median_survival_time_, color<span class="op">=</span><span class="st">&#39;r&#39;</span>,linestyle<span class="op">=</span><span class="st">&#39;--&#39;</span>)</span></code></pre></div>
<p><img src="figs/churn5.png" /></p>
<p>Let’s look at the <code>median</code> survival time. This is the point by which half of customers have churned out. According to this graph, where it’s marked by the red dotted line, by about 152 days half of customers churn.</p>
<p>This is helpful because it gives overall baseline when intervention is needed. However, for each individual customer this is uninformative.
<strong>What is missing is the point in time in which churn risk is highest for each customer.</strong></p>
<p>For that we will create a model using <code>Cox’s Proportional Hazard</code> which uses a log-risk function <span class="math inline">\(h(x)\)</span>. The Hazard function is conditioned on rate of a customers remaining until time t or later, this allows to estimate the risk of churn overtime.</p>
<p>This will enable us to score each customer and anticipate when a marketing intervention is needed. However, before we proceed to that, we need to preprocess the data.</p>
</div>
<div id="data-splitting-and-preprocessing" class="section level4 hasAnchor" number="2.3.6.3">
<h4><span class="header-section-number">2.3.6.3</span> Data Splitting and Preprocessing<a href="machine-learning-fundamentals.html#data-splitting-and-preprocessing" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>First we will split the data into training and testing. We’ll use the testing set as the validation for the example.</p>
<pre><code>In practice, you want all three of these splits so that you don’t tune to the validation set.</code></pre>
<p>Next, we take the numeric features and categorical features and then preprocess them for downstream modeling.</p>
<p>In the case of categories, we will first impute with the constant and then simply one-hot encode them. In the case of numerics, we will fill with the median then standardize them between values of 0 and 1. This is all wrapped into Sklearn’s Pipeline and ColumnTransformer for simplicity’s sake.
As part of the Churn Pipeline all these steps are included with the final preprocessor saved for use at inference time.</p>

</div>
</div>
<div id="deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws" class="section level3 hasAnchor" number="2.3.7">
<h3><span class="header-section-number">2.3.7</span> Deploying a Scalable End to End Customer Churn Prediction Solution with AWS<a href="machine-learning-fundamentals.html#deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><a href="https://towardsdatascience.com/deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws-cbf3536be996">Source</a></p>
<p>Wouldn’t it be great if you could hold onto customers longer, maximizing their lifetime revenue?</p>
<p>In this blog post, you will deploy an End to End Customer Churn Prediction solution using AWS services.</p>

<div class="sourceCode" id="cb60"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb60-1"><a href="machine-learning-fundamentals.html#cb60-1" tabindex="-1"></a><span class="im">import</span> findspark</span>
<span id="cb60-2"><a href="machine-learning-fundamentals.html#cb60-2" tabindex="-1"></a>findspark.init()</span></code></pre></div>
<div class="sourceCode" id="cb61"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb61-1"><a href="machine-learning-fundamentals.html#cb61-1" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb61-2"><a href="machine-learning-fundamentals.html#cb61-2" tabindex="-1"></a><span class="im">from</span> pyspark <span class="im">import</span> SparkFiles</span>
<span id="cb61-3"><a href="machine-learning-fundamentals.html#cb61-3" tabindex="-1"></a><span class="im">from</span> pyspark.ml.classification <span class="im">import</span> LogisticRegression</span>
<span id="cb61-4"><a href="machine-learning-fundamentals.html#cb61-4" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> BinaryClassificationEvaluator, MulticlassClassificationEvaluator</span>
<span id="cb61-5"><a href="machine-learning-fundamentals.html#cb61-5" tabindex="-1"></a><span class="im">from</span> pyspark.ml.tuning <span class="im">import</span> CrossValidator, ParamGridBuilder</span>
<span id="cb61-6"><a href="machine-learning-fundamentals.html#cb61-6" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> VectorAssembler</span></code></pre></div>
<div class="sourceCode" id="cb62"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb62-1"><a href="machine-learning-fundamentals.html#cb62-1" tabindex="-1"></a>my_appname <span class="op">=</span> <span class="st">&quot;LogisticRegression with PySpark MLlib&quot;</span></span>
<span id="cb62-2"><a href="machine-learning-fundamentals.html#cb62-2" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.appName(my_appname).getOrCreate()</span></code></pre></div>
<div class="sourceCode" id="cb63"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb63-1"><a href="machine-learning-fundamentals.html#cb63-1" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb63-2"><a href="machine-learning-fundamentals.html#cb63-2" tabindex="-1"></a>url <span class="op">=</span> <span class="st">&quot;https://raw.githubusercontent.com/pkmklong/Breast-Cancer-Wisconsin-Diagnostic-DataSet/master/data.csv&quot;</span></span>
<span id="cb63-3"><a href="machine-learning-fundamentals.html#cb63-3" tabindex="-1"></a>spark.sparkContext.addFile(url)</span>
<span id="cb63-4"><a href="machine-learning-fundamentals.html#cb63-4" tabindex="-1"></a></span>
<span id="cb63-5"><a href="machine-learning-fundamentals.html#cb63-5" tabindex="-1"></a>df <span class="op">=</span> spark.read.csv(SparkFiles.get(<span class="st">&quot;data.csv&quot;</span>), header<span class="op">=</span><span class="va">True</span>, inferSchema<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb63-6"><a href="machine-learning-fundamentals.html#cb63-6" tabindex="-1"></a></span>
<span id="cb63-7"><a href="machine-learning-fundamentals.html#cb63-7" tabindex="-1"></a><span class="co"># df.show()</span></span></code></pre></div>
<div class="sourceCode" id="cb64"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb64-1"><a href="machine-learning-fundamentals.html#cb64-1" tabindex="-1"></a><span class="co"># Rename columns and map diagnosis to label</span></span>
<span id="cb64-2"><a href="machine-learning-fundamentals.html#cb64-2" tabindex="-1"></a>columns <span class="op">=</span> [<span class="st">&#39;id&#39;</span>, <span class="st">&#39;diagnosis&#39;</span>] <span class="op">+</span> [<span class="ss">f&#39;feature_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">&#39;</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">32</span>)]</span>
<span id="cb64-3"><a href="machine-learning-fundamentals.html#cb64-3" tabindex="-1"></a>data <span class="op">=</span> df.toDF(<span class="op">*</span>columns)</span>
<span id="cb64-4"><a href="machine-learning-fundamentals.html#cb64-4" tabindex="-1"></a>data <span class="op">=</span> data.withColumn(<span class="st">&quot;label&quot;</span>, (data[<span class="st">&quot;diagnosis&quot;</span>] <span class="op">==</span> <span class="st">&quot;M&quot;</span>).cast(<span class="st">&quot;integer&quot;</span>)).drop(<span class="st">&quot;diagnosis&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb65"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb65-1"><a href="machine-learning-fundamentals.html#cb65-1" tabindex="-1"></a><span class="co"># Assemble features into a single vector</span></span>
<span id="cb65-2"><a href="machine-learning-fundamentals.html#cb65-2" tabindex="-1"></a>feature_columns <span class="op">=</span> [<span class="ss">f&#39;feature_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">&#39;</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">25</span>)]</span>
<span id="cb65-3"><a href="machine-learning-fundamentals.html#cb65-3" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(inputCols<span class="op">=</span>feature_columns, outputCol<span class="op">=</span><span class="st">&quot;features&quot;</span>)</span>
<span id="cb65-4"><a href="machine-learning-fundamentals.html#cb65-4" tabindex="-1"></a>data <span class="op">=</span> assembler.transform(data)</span></code></pre></div>
<div class="sourceCode" id="cb66"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb66-1"><a href="machine-learning-fundamentals.html#cb66-1" tabindex="-1"></a><span class="co"># Split data into training and test sets</span></span>
<span id="cb66-2"><a href="machine-learning-fundamentals.html#cb66-2" tabindex="-1"></a>train_data, test_data <span class="op">=</span> data.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb66-3"><a href="machine-learning-fundamentals.html#cb66-3" tabindex="-1"></a></span>
<span id="cb66-4"><a href="machine-learning-fundamentals.html#cb66-4" tabindex="-1"></a><span class="co"># Build the Logistic Regression model</span></span>
<span id="cb66-5"><a href="machine-learning-fundamentals.html#cb66-5" tabindex="-1"></a>logistic_regression <span class="op">=</span> LogisticRegression(featuresCol<span class="op">=</span><span class="st">&quot;features&quot;</span>, labelCol<span class="op">=</span><span class="st">&quot;label&quot;</span>)</span>
<span id="cb66-6"><a href="machine-learning-fundamentals.html#cb66-6" tabindex="-1"></a>model <span class="op">=</span> logistic_regression.fit(train_data)</span></code></pre></div>
<div class="sourceCode" id="cb67"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb67-1"><a href="machine-learning-fundamentals.html#cb67-1" tabindex="-1"></a><span class="co"># Evaluate the model on test data</span></span>
<span id="cb67-2"><a href="machine-learning-fundamentals.html#cb67-2" tabindex="-1"></a>predictions <span class="op">=</span> model.transform(test_data)</span></code></pre></div>
<div class="sourceCode" id="cb68"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb68-1"><a href="machine-learning-fundamentals.html#cb68-1" tabindex="-1"></a><span class="co"># AUC-ROC</span></span>
<span id="cb68-2"><a href="machine-learning-fundamentals.html#cb68-2" tabindex="-1"></a>evaluator <span class="op">=</span> BinaryClassificationEvaluator(rawPredictionCol<span class="op">=</span><span class="st">&quot;rawPrediction&quot;</span>, labelCol<span class="op">=</span><span class="st">&quot;label&quot;</span>)</span>
<span id="cb68-3"><a href="machine-learning-fundamentals.html#cb68-3" tabindex="-1"></a>auc <span class="op">=</span> evaluator.evaluate(predictions)</span></code></pre></div>
<div class="sourceCode" id="cb69"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb69-1"><a href="machine-learning-fundamentals.html#cb69-1" tabindex="-1"></a><span class="co"># Accuracy, Precision, and Recall</span></span>
<span id="cb69-2"><a href="machine-learning-fundamentals.html#cb69-2" tabindex="-1"></a>multi_evaluator <span class="op">=</span> MulticlassClassificationEvaluator(labelCol<span class="op">=</span><span class="st">&quot;label&quot;</span>, predictionCol<span class="op">=</span><span class="st">&quot;prediction&quot;</span>)</span>
<span id="cb69-3"><a href="machine-learning-fundamentals.html#cb69-3" tabindex="-1"></a>accuracy <span class="op">=</span> multi_evaluator.evaluate(predictions, {multi_evaluator.metricName: <span class="st">&quot;accuracy&quot;</span>})</span>
<span id="cb69-4"><a href="machine-learning-fundamentals.html#cb69-4" tabindex="-1"></a>precision <span class="op">=</span> multi_evaluator.evaluate(predictions, {multi_evaluator.metricName: <span class="st">&quot;weightedPrecision&quot;</span>})</span>
<span id="cb69-5"><a href="machine-learning-fundamentals.html#cb69-5" tabindex="-1"></a>recall <span class="op">=</span> multi_evaluator.evaluate(predictions, {multi_evaluator.metricName: <span class="st">&quot;weightedRecall&quot;</span>})</span>
<span id="cb69-6"><a href="machine-learning-fundamentals.html#cb69-6" tabindex="-1"></a></span>
<span id="cb69-7"><a href="machine-learning-fundamentals.html#cb69-7" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;AUC-ROC: </span><span class="sc">{</span>auc<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## AUC-ROC: 0.9989</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb71-1"><a href="machine-learning-fundamentals.html#cb71-1" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Accuracy: </span><span class="sc">{</span>accuracy<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## Accuracy: 0.9651</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb73-1"><a href="machine-learning-fundamentals.html#cb73-1" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Precision: </span><span class="sc">{</span>precision<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## Precision: 0.9653</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb75-1"><a href="machine-learning-fundamentals.html#cb75-1" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Recall: </span><span class="sc">{</span>recall<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## Recall: 0.9651</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="projects.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/PROJECTS/00_Fundamentals/00_00_intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Project_Archive.pdf", "Project_Archive.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
