<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Projects | Projects Repository</title>
  <meta name="description" content="This is a collection of notes to my self" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Projects | Projects Repository" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a collection of notes to my self" />
  <meta name="github-repo" content="davutemrah/davutemrah.github.io" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Projects | Projects Repository" />
  
  <meta name="twitter:description" content="This is a collection of notes to my self" />
  

<meta name="author" content="Davut Ayan" />


<meta name="date" content="2024-01-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="preface-1.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Machine Learning</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="projects.html"><a href="projects.html"><i class="fa fa-check"></i><b>1</b> Projects</a>
<ul>
<li class="chapter" data-level="1.0.1" data-path="projects.html"><a href="projects.html#notes-on-visuals"><i class="fa fa-check"></i><b>1.0.1</b> NOTES ON VISUALS</a></li>
<li class="chapter" data-level="1.1" data-path="projects.html"><a href="projects.html#elastic-net-model"><i class="fa fa-check"></i><b>1.1</b> Elastic Net Model</a></li>
<li class="chapter" data-level="1.2" data-path="projects.html"><a href="projects.html#survival-analysis"><i class="fa fa-check"></i><b>1.2</b> Survival Analysis</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="projects.html"><a href="projects.html#references"><i class="fa fa-check"></i><b>1.2.1</b> References</a></li>
<li class="chapter" data-level="1.2.2" data-path="projects.html"><a href="projects.html#time-to-event-analysis"><i class="fa fa-check"></i><b>1.2.2</b> Time to event analysis</a></li>
<li class="chapter" data-level="1.2.3" data-path="projects.html"><a href="projects.html#kaplan-meier"><i class="fa fa-check"></i><b>1.2.3</b> Kaplan-Meier</a></li>
<li class="chapter" data-level="1.2.4" data-path="projects.html"><a href="projects.html#the-basics-of-survival-analysis"><i class="fa fa-check"></i><b>1.2.4</b> The basics of Survival Analysis</a></li>
<li class="chapter" data-level="1.2.5" data-path="projects.html"><a href="projects.html#prosper-loan-data"><i class="fa fa-check"></i><b>1.2.5</b> Prosper Loan data</a></li>
<li class="chapter" data-level="1.2.6" data-path="projects.html"><a href="projects.html#customer-churn"><i class="fa fa-check"></i><b>1.2.6</b> Customer Churn</a></li>
<li class="chapter" data-level="1.2.7" data-path="projects.html"><a href="projects.html#deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws"><i class="fa fa-check"></i><b>1.2.7</b> Deploying a Scalable End to End Customer Churn Prediction Solution with AWS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="preface-1.html"><a href="preface-1.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="2" data-path="projects-1.html"><a href="projects-1.html"><i class="fa fa-check"></i><b>2</b> Projects</a>
<ul>
<li class="chapter" data-level="2.0.1" data-path="projects-1.html"><a href="projects-1.html#notes-on-visuals-1"><i class="fa fa-check"></i><b>2.0.1</b> NOTES ON VISUALS</a></li>
<li class="chapter" data-level="2.1" data-path="projects-1.html"><a href="projects-1.html#elastic-net-model-1"><i class="fa fa-check"></i><b>2.1</b> Elastic Net Model</a></li>
<li class="chapter" data-level="2.2" data-path="projects-1.html"><a href="projects-1.html#survival-analysis-1"><i class="fa fa-check"></i><b>2.2</b> Survival Analysis</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="projects-1.html"><a href="projects-1.html#references-1"><i class="fa fa-check"></i><b>2.2.1</b> References</a></li>
<li class="chapter" data-level="2.2.2" data-path="projects-1.html"><a href="projects-1.html#time-to-event-analysis-1"><i class="fa fa-check"></i><b>2.2.2</b> Time to event analysis</a></li>
<li class="chapter" data-level="2.2.3" data-path="projects-1.html"><a href="projects-1.html#kaplan-meier-1"><i class="fa fa-check"></i><b>2.2.3</b> Kaplan-Meier</a></li>
<li class="chapter" data-level="2.2.4" data-path="projects-1.html"><a href="projects-1.html#the-basics-of-survival-analysis-1"><i class="fa fa-check"></i><b>2.2.4</b> The basics of Survival Analysis</a></li>
<li class="chapter" data-level="2.2.5" data-path="projects-1.html"><a href="projects-1.html#prosper-loan-data-1"><i class="fa fa-check"></i><b>2.2.5</b> Prosper Loan data</a></li>
<li class="chapter" data-level="2.2.6" data-path="projects-1.html"><a href="projects-1.html#customer-churn-1"><i class="fa fa-check"></i><b>2.2.6</b> Customer Churn</a></li>
<li class="chapter" data-level="2.2.7" data-path="projects-1.html"><a href="projects-1.html#deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws-1"><i class="fa fa-check"></i><b>2.2.7</b> Deploying a Scalable End to End Customer Churn Prediction Solution with AWS</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://davutemrah.github.io/notebooks/" target="blank">Personal Repo Home</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Projects Repository</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="projects-1" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Projects<a href="projects-1.html#projects-1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><a href="https://datatab.net/tutorial/get-started">DataTab Statistics Tutorials</a></p>

<div id="notes-on-visuals-1" class="section level3 hasAnchor" number="2.0.1">
<h3><span class="header-section-number">2.0.1</span> NOTES ON VISUALS<a href="projects-1.html#notes-on-visuals-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>pre attentive principles, colurs, shape, size etc.</p></li>
<li><p>GESTALT principles</p></li>
<li><p>why data visualization is needed with summary statistics. Data patterns may be different although means may be different</p></li>
<li><p>exploratory graphs: may be good for people with some background. filtering and some control may be given to audience</p></li>
<li><p>explanatory graphs: may be good for people with no backgroung. made simple</p></li>
</ul>

</div>
<div id="elastic-net-model-1" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Elastic Net Model<a href="projects-1.html#elastic-net-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Elastic Net is a regularization technique that combines both L1 (Lasso) and L2 (Ridge) regularization penalties in a linear regression model. This technique is commonly used in machine learning, especially when dealing with high-dimensional datasets or situations where some of the features are highly correlated.</p>
<p>In elastic net regularization, the objective function is a combination of the L1 and L2 regularization terms along with the linear regression loss. The regularization strength is controlled by two hyperparameters, often denoted as
α
α (alpha) and
λ
λ (lambda):</p>
<p>α
α controls the mixing between L1 and L2 regularization. When
α
=
0
α=0, it is equivalent to Ridge regression, and when
α
=
1
α=1, it is equivalent to Lasso regression. Any value in between (0 and 1) allows for a mixture of both.
λ
λ controls the overall strength of the regularization.</p>
<p>In R, you can fit an elastic net model using the glmnet package. Here’s a brief example:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="projects-1.html#cb77-1" tabindex="-1"></a><span class="co"># Install and load the glmnet package if not already installed</span></span>
<span id="cb77-2"><a href="projects-1.html#cb77-2" tabindex="-1"></a><span class="co"># install.packages(&quot;glmnet&quot;)</span></span>
<span id="cb77-3"><a href="projects-1.html#cb77-3" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb77-4"><a href="projects-1.html#cb77-4" tabindex="-1"></a></span>
<span id="cb77-5"><a href="projects-1.html#cb77-5" tabindex="-1"></a><span class="co"># Generate some example data</span></span>
<span id="cb77-6"><a href="projects-1.html#cb77-6" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb77-7"><a href="projects-1.html#cb77-7" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb77-8"><a href="projects-1.html#cb77-8" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb77-9"><a href="projects-1.html#cb77-9" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(n <span class="sc">*</span> p), <span class="at">nrow =</span> n, <span class="at">ncol =</span> p)</span>
<span id="cb77-10"><a href="projects-1.html#cb77-10" tabindex="-1"></a>beta_true <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">0</span>)</span>
<span id="cb77-11"><a href="projects-1.html#cb77-11" tabindex="-1"></a>y <span class="ot">&lt;-</span> X <span class="sc">%*%</span> beta_true <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb77-12"><a href="projects-1.html#cb77-12" tabindex="-1"></a></span>
<span id="cb77-13"><a href="projects-1.html#cb77-13" tabindex="-1"></a><span class="co"># Fit an elastic net model</span></span>
<span id="cb77-14"><a href="projects-1.html#cb77-14" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.5</span>  <span class="co"># You can adjust alpha to control the mixture of L1 and L2 regularization</span></span>
<span id="cb77-15"><a href="projects-1.html#cb77-15" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="fl">0.1</span>  <span class="co"># You can adjust lambda to control the overall strength of regularization</span></span>
<span id="cb77-16"><a href="projects-1.html#cb77-16" tabindex="-1"></a></span>
<span id="cb77-17"><a href="projects-1.html#cb77-17" tabindex="-1"></a>enet_model <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X, y, <span class="at">alpha =</span> alpha, <span class="at">lambda =</span> lambda)</span></code></pre></div>

</div>
<div id="survival-analysis-1" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Survival Analysis<a href="projects-1.html#survival-analysis-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="references-1" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> References<a href="projects-1.html#references-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Web Sources</strong></p>
<ol style="list-style-type: decimal">
<li><p><a href="https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html">Emily C. Zabor: Survival Aanalysis in R</a></p></li>
<li><p><a href="https://bookdown.org/sestelo/sa_financial/">A short course on Survival Analysis applied to the Financial Industry</a></p></li>
<li><p><a href="https://www.datacamp.com/tutorial/survival-analysis-R">Survival Analysis in R For Beginners</a></p></li>
<li><p><a href="https://rviews.rstudio.com/2017/09/25/survival-analysis-with-r/">Survival Analysis with R</a></p></li>
<li><p><a href="http://www.sthda.com/english/wiki/survival-analysis-basics">Survival Analysis Basics</a></p></li>
<li><p><a href="https://www.r-bloggers.com/2018/03/steps-to-perform-survival-analysis-in-r/">Steps to perform Survival Analysis in R</a></p></li>
<li><p><a href="http://tagteam.harvard.edu/hub_feeds/1981/feed_items/2286128">Survival Analysis with R, Harvard</a></p></li>
<li><p><a href="https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Survival/BS704_Survival_print.html">Survival Analysis: Lisa Sullivan, PhD</a></p></li>
<li><p><a href="https://www.nature.com/articles/6601118.pdf">Survival Analysis Part I: Basic concepts and first analyses</a></p></li>
<li><p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3932959/pdf/nihms549224.pdf">Practical Guide Paper</a></p></li>
<li><p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5045282/">An Introduction to Survival Statistics: Kaplan-Meier Analysis</a></p></li>
<li><p><a href="https://towardsdatascience.com/kaplan-meier-curves-c5768e349479">Kaplan Meier curves: an introduction</a></p></li>
<li><p><a href="https://stat.ethz.ch/R-manual/R-devel/library/survival/html/lung.html">NCCTG Lung Cancer Data</a></p></li>
</ol>
<p><strong>pdf references</strong></p>
<!-- <iframe src="data_setup_alternative.pdf" style="width:100%; height:100px;"></iframe> -->
<!-- <a href=survival_pdf/survival_data_setup_alternative.pdf>1. Data Setup Alternative</a> -->
<p><a href="survival_pdf/survival_data_setup_alternative.pdf">1. Data Setup Alternative</a></p>
<p><a href="survival_pdf/survival_Intro_Survival_Analysis_Practice.pdf">2. Introduction to Survival Analysis in Practice</a></p>
<p><a href="survival_pdf/survival_lecture_note.pdf">3. Chapter 7 - Survival Models</a></p>
<p><a href="survival_pdf/survival_notes_pat.pdf">4. Notes from Pat</a></p>
<p><a href="survival_pdf/Survival_parametric.pdf">5. Parametric Survival Models</a></p>
<p><a href="survival_pdf/survival_retain_customers.pdf">6. Retain Customers by Churn model</a></p>
<p><a href="survival_pdf/survival_intro.pdf">7. Intro to Survival Analysis</a></p>
</div>
<div id="time-to-event-analysis-1" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Time to event analysis<a href="projects-1.html#time-to-event-analysis-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Time to event analysis has also been used widely in the social sciences where interest is on analyzing time to events such as job changes, marriage, birth of children and so forth.</p>
<p>There are certain aspects of survival analysis data, such as censoring and non-normality, that generate great difficulty when trying to analyze the data using traditional statistical models such as multiple linear regression.</p>
<p>The non-normality aspect of the data violates the normality assumption of most commonly used statistical model such as regression or ANOVA, etc.</p>
<p>A censored observation is defined as an observation with incomplete information.
When an observation is right censored it means that the information is incomplete because the subject did not have an event during the time that the subject was part of the study.</p>
<p>The point of survival analysis is to follow subjects over time and observe at which point in time they experience the event of interest.</p>
<p>It often happens that the study does not span enough time in order to observe the event for all the subjects in the study. This could be due to a number of reasons. Perhaps subjects drop out of the study for reasons unrelated to the study (i.e. patients moving to another area and leaving no forwarding address).</p>
<p>The common feature of all of these examples is that if the subject had been able to stay in the study then it would have been possible to observe the time of the event eventually.</p>
<p>Type of censoring
- Right truncation
- Right censoring
- Left truncation
- Left censoring</p>
<p>In survival analysis, censoring refers to situations where the event of interest (e.g., death, failure, or another outcome) is not observed for some subjects during the study period. There are two main types of censoring: right truncation and right censoring.</p>
<ol style="list-style-type: decimal">
<li><strong>Right Truncation:</strong>
<ul>
<li><strong>Definition:</strong> Right truncation occurs when individuals enter the study at different times, and some individuals have already experienced the event of interest before the study begins.</li>
<li><strong>Example:</strong> Consider a study on the time until a machine fails. If the study starts at a certain date, and some machines have already failed before that date, those machines are considered right-truncated because their failure times are not observed in the study.</li>
</ul></li>
<li><strong>Right Censoring:</strong>
<ul>
<li><strong>Definition:</strong> Right censoring occurs when individuals are followed for a certain period, but the event of interest does not occur for some of them by the end of the study.</li>
<li><strong>Example:</strong> In a clinical trial studying the time until disease recurrence, if a patient has not experienced recurrence by the end of the study period or is lost to follow-up, their survival time is right-censored. The exact time of recurrence is not known for these patients.</li>
</ul></li>
</ol>
<p>In summary, right truncation involves incomplete observation due to some subjects entering the study late, whereas right censoring occurs when the event of interest has not occurred for some subjects by the end of the study. Both types of censoring are common in survival analysis and need to be appropriately accounted for in statistical models to obtain unbiased estimates of survival probabilities and hazard rates.</p>
<p><strong>What is survival data?</strong></p>
<p>Time-to-event data that consist of a distinct start time and end time.</p>
<p>Examples from cancer
• Time from surgery to death
• Time from start of treatment to progression
• Time from response to recurrence</p>
<p>Examples from other fields</p>
<p>Time-to-event data are common in many fields including, but not limited to
• Time from HIV infection to development of AIDS
• Time to heart attack
• Time to onset of substance abuse
• Time to initiation of sexual activity
• Time to machine malfunction</p>
<p>Types of censoring</p>
<p>A subject may be censored due to:
• Loss to follow-up
• Withdrawal from study
• No event by end of fixed study period</p>
<p>Specifically these are examples of right censoring.</p>
<p>Left censoring and interval censoring are also possible, and methods exist to analyze this type of data.</p>
</div>
<div id="kaplan-meier-1" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Kaplan-Meier<a href="projects-1.html#kaplan-meier-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><a href="https://datatab.net/tutorial/kaplan-meier-curve#:~:text=The%20Kaplan-Meier%20curve%20shows,therefore%20a%20better%20survival%20prognosis.">Source</a></p>
<p>The Kaplan-Meier curve is commonly used to analyze time-to-event data, such as the time until death or the time until a specific event occurs. For this, the Kaplan Meier curve graphically represent the survival rate or survival function. Time is plotted on the x-axis and the survival rate is plotted on the y-axis.</p>
<div id="survival-rate-1" class="section level4 hasAnchor" number="2.2.3.1">
<h4><span class="header-section-number">2.2.3.1</span> Survival rate<a href="projects-1.html#survival-rate-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Suppose you’re a dental technician and you want to study the “survival time” of a filling in a tooth.</p>
<p>So your start time is the moment when a person goes to the dentist for a filling, and your end time, the event, is the moment when the filling breaks. The time between these two events is the focus of your study.</p>
<p><img src="figs/survival2.png" /></p>
<p>For example, you may be interested in the probability that your filling will last longer than 5 years.</p>
<p>To do this, you read off the value at 5 years on the graph, which is the survival rate.</p>
<p>At 5 years, the Kaplan-Meier curve gives you a value of 0.7.</p>
<pre><code>  So there is a 70% chance that your filling will last longer than 5 years.</code></pre>
</div>
<div id="interpreting-the-kaplan-meier-curve-1" class="section level4 hasAnchor" number="2.2.3.2">
<h4><span class="header-section-number">2.2.3.2</span> Interpreting the Kaplan-Meier curve<a href="projects-1.html#interpreting-the-kaplan-meier-curve-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Kaplan-Meier curve shows the cumulative survival probabilities.</p>
<p>A steeper slope indicates a higher event rate (death rate) and therefore a worse survival prognosis. A flatter slope indicates a lower event rate and therefore a better survival prognosis. The curve may have plateaus or flat areas, indicating periods of relatively stable survival.</p>
<p>If there are multiple curves representing different groups, you can compare their shapes and patterns. If the curves are parallel, it suggests that the groups have similar survival experiences. If the curves diverge or cross, it indicates differences in survival between the groups.</p>
<p>At specific time points, you can estimate the survival probability by locating the time point on the horizontal axis and dropping a vertical line to the curve. Then, read the corresponding survival probability from the vertical axis.</p>
</div>
<div id="calculating-the-kaplan-meier-curve-1" class="section level4 hasAnchor" number="2.2.3.3">
<h4><span class="header-section-number">2.2.3.3</span> Calculating the Kaplan-Meier curve<a href="projects-1.html#calculating-the-kaplan-meier-curve-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s say the filling lasted 3 years for the first subject, 4 years for the second subject, 4 years for the third subject, and so on.</p>
<p><img src="figs/km0.png" /></p>
<p>Let’s assume that none of the cases are “censored”. The data are already arranged so that the shortest survival time is at the top and the longest at the bottom.</p>
<p>Now we create a second table that we can use to draw the Kaplan-Meier curve. To do this, we look at the time points in the left table and add the time zero. So we have the time points 0, then 3, 4, 6, 7, 8 11 and 13. In total we have 10 subjects.</p>
<p>Now we look at how many fills break out at each time. We enter this in the column m. So at time 0, no fillings were broken out. After 3 years, there were one broken fillings, after 4 years there were two, after 6 years there was one. We now do the same for all the other times.</p>
<p>Next, we look at the number of cases that have survived to the time plus the number of cases where the event occurs at the exact time. We enter this in column n.</p>
<p>So n is the number of cases that survived to that point, plus the people who dropped out at that exact point.</p>
<p>After zero years we still have all 10 people. After 3 years, we get 10 for n, 9 people still have their fill intact, and one person’s fill broke out exactly after 3 years.</p>
<p>The easiest way to get n is to take the previous n value and subtract the previous m value. So we get 10 - 1 equals 9. Then 9 minus 2 equals 7, 7 - 1 equals 6… and so on and so forth.</p>
<p>From column n we can now calculate the survival rates. To do this, we simply divide n by the total number, i.e. 10.</p>
<p>So 10 divided by 10 is equal to 1, 9 divided by 10 is equal to 0.9, 7 divided by 10 is equal to 0.7. Now we do the same for all the others.</p>
</div>
<div id="draw-kaplan-meier-curve-1" class="section level4 hasAnchor" number="2.2.3.4">
<h4><span class="header-section-number">2.2.3.4</span> Draw Kaplan Meier curve<a href="projects-1.html#draw-kaplan-meier-curve-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can now plot the Kaplan-Meier curve. At time 0 we have a value of 1, after 3 years we have a value of 0.9 or 90%. After 4 years we get 0.7, after 6 years 0.6 and so on and so forth.</p>
<p><img src="figs/km1.png" /></p>
<p>From the Kaplan-Meier curve, we can now see what percentage of the filling has not broken out after a certain time.</p>
</div>
<div id="censored-data-1" class="section level4 hasAnchor" number="2.2.3.5">
<h4><span class="header-section-number">2.2.3.5</span> Censored data<a href="projects-1.html#censored-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Censored data has been added to the example in these three places.</p>
<p><img src="figs/km2.png" /></p>
<p>We now need to enter this data into our Kaplan-Meier curve table. We do this as follows: We create our m exactly as we did before, looking at how many cases failed at each time point.</p>
<p>Now we add a column q, in which we enter how many cases were censored at each time.</p>
<p>Note that the time at which each censored case occurred does not get its own row, but is assigned to the previous time.</p>
<p><img src="figs/km3.png" /></p>
<p>Let’s look at this case. The censoring took place at time 9. In this table, however, there is no event with nine years and we also don’t add it. The person is added at time 8.</p>
<p>We can now re-calculate the values for the survival curve. If we have censored data, this is a little more complex.</p>
<p>For this, we write down the values in the first step. We get these values by calculating n-m/n. In the third row, for example, we get the value 10/12 with 12-2 by 12.</p>
<p>The calculation of the real value is iterative. To do this, we multiply the result from the previous row by the value we have just calculated.</p>
<p>So, in the first row we get 1, now we calculate 12/13 times 1, which is equal to 0.923. In the next row we calculate 10/12 times 0.923 and get a value of 0.769. We take this value again for the next row.</p>
<p>We do this for all the rows. We can then plot the Kaplan-Meier curve with this data in the same way as before.</p>
</div>
<div id="comparing-different-groups-1" class="section level4 hasAnchor" number="2.2.3.6">
<h4><span class="header-section-number">2.2.3.6</span> Comparing different groups<a href="projects-1.html#comparing-different-groups-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you are comparing several groups or categories (e.g. treatment groups), the Kaplan-Meier curve consists of several lines, each representing a different group. Each line shows the estimated survival rate for that particular group. To test whether there is a statistically significant difference between the groups, the log-rank test can be used.</p>
<p>If you have several factors and you want to see if they have an effect on the curve, you can calculate a Log Rank Test or calculate a Cox Regression here on DATAtab.</p>
</div>
<div id="kaplan-meier-curve-assumptions-1" class="section level4 hasAnchor" number="2.2.3.7">
<h4><span class="header-section-number">2.2.3.7</span> Kaplan-Meier curve assumptions<a href="projects-1.html#kaplan-meier-curve-assumptions-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Random or Non-informative censoring: This assumption states that the occurrence of censoring is unrelated to the likelihood of experiencing the event of interest. In other words, censoring should be random and not influenced by factors that affect the event outcome. If censoring is not non-informative, the estimated survival probabilities may be biased.</p>
<p>Independence of censoring: This assumption assumes that the censoring times of different individuals are independent of each other. This means that the occurrence or timing of censoring for one participant should not provide any information about the censoring times for other participants.</p>
<p>Survival probabilities do not change over time: The Kaplan-Meier curve assumes that the survival probabilities estimated at each time point remain constant over time. This assumption may not be valid if there are time-varying factors or treatments that can influence survival probabilities.</p>
<p>No competing risks: The Kaplan-Meier curve assumes that the event of interest is the only possible outcome and there are no other competing events that could prevent the occurrence of the event being studied. Competing events can include other causes of death or events that render the occurrence of the event of interest impossible.</p>

</div>
</div>
<div id="the-basics-of-survival-analysis-1" class="section level3 hasAnchor" number="2.2.4">
<h3><span class="header-section-number">2.2.4</span> The basics of Survival Analysis<a href="projects-1.html#the-basics-of-survival-analysis-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="projects-1.html#cb79-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb79-2"><a href="projects-1.html#cb79-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb79-3"><a href="projects-1.html#cb79-3" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb79-4"><a href="projects-1.html#cb79-4" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb79-5"><a href="projects-1.html#cb79-5" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb79-6"><a href="projects-1.html#cb79-6" tabindex="-1"></a></span>
<span id="cb79-7"><a href="projects-1.html#cb79-7" tabindex="-1"></a><span class="co"># devtools::install_github(&quot;zabore/ezfun&quot;)</span></span>
<span id="cb79-8"><a href="projects-1.html#cb79-8" tabindex="-1"></a>ezfun<span class="sc">::</span><span class="fu">set_ccf_palette</span>(<span class="st">&quot;contrast&quot;</span>)</span></code></pre></div>
<pre><code>## &lt;environment: R_GlobalEnv&gt;</code></pre>
<p><a href="https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html">Original article</a></p>
<p>Survival data are time-to-event data that consist of a distinct start time and end time.</p>
<p>Examples from cancer:</p>
<ul>
<li>Time from surgery to death</li>
<li>Time from start of treatment to progression</li>
<li>Time from response to recurrence</li>
<li>Time-to-event data are common in many other fields.</li>
</ul>
<p>Some other examples include:</p>
<ul>
<li>Time from HIV infection to development of AIDS</li>
<li>Time to heart attack</li>
<li>Time to onset of substance abuse</li>
<li>Time to initiation of sexual activity</li>
<li>Time to machine malfunction</li>
</ul>
<p>Because time-to-event data are common in many fields, it also goes by names besides survival analysis including:</p>
<ul>
<li>Reliability analysis</li>
<li>Duration analysis</li>
<li>Event history analysis</li>
<li>Time-to-event analysis</li>
</ul>
<p>A key feature of survival data is censoring.</p>
<p>Censoring occurs if a subject has not experienced the event of interest by the end of data collection.</p>
<p>A subject may be censored due to:</p>
<ul>
<li>Loss to follow-up</li>
<li>Withdrawal from study</li>
<li>No event by end of fixed study period</li>
</ul>
<p>Specifically these are examples of <strong>right censoring.</strong></p>
<p><strong>Left censoring</strong> and <strong>interval censoring</strong> are also possible, and methods exist to analyze these types of data, but this tutorial will be focus on right censoring.</p>
<p>To illustrate the impact of censoring, suppose we have the following data:</p>
<p><img src="figs/survival1.png" /></p>
<p>How would we compute the proportion who are event-free at 10 years?</p>
<ul>
<li>Subjects 6 and 7 were event-free at 10 years.</li>
<li>Subjects 2, 9, and 10 had the event before 10 years.</li>
<li>Subjects 1, 3, 4, 5, and 8 were censored before 10 years, so we don’t know whether they had the event or not at 10 years. But we know something about them - that they were each followed for a certain amount of time without the event of interest prior to being censored.</li>
</ul>
<p>Survival analysis techniques provide a way to appropriately account for censored patients in the analysis.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="projects-1.html#cb81-1" tabindex="-1"></a><span class="co"># install.packages(c(&quot;lubridate&quot;, &quot;ggsurvfit&quot;, &quot;gtsummary&quot;, &quot;tidycmprsk&quot;))</span></span>
<span id="cb81-2"><a href="projects-1.html#cb81-2" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb81-3"><a href="projects-1.html#cb81-3" tabindex="-1"></a><span class="fu">library</span>(ggsurvfit)</span>
<span id="cb81-4"><a href="projects-1.html#cb81-4" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb81-5"><a href="projects-1.html#cb81-5" tabindex="-1"></a><span class="fu">library</span>(tidycmprsk)</span>
<span id="cb81-6"><a href="projects-1.html#cb81-6" tabindex="-1"></a></span>
<span id="cb81-7"><a href="projects-1.html#cb81-7" tabindex="-1"></a><span class="co"># devtools::install_github(&quot;zabore/condsurv&quot;)</span></span>
<span id="cb81-8"><a href="projects-1.html#cb81-8" tabindex="-1"></a><span class="fu">library</span>(condsurv)</span></code></pre></div>
<p><strong>The lung dataset</strong></p>
<p>Throughout this section, we will use the <code>lung</code> dataset from the <code>survival</code> package as example data. The data contain subjects with advanced lung cancer from the North Central Cancer Treatment Group. We will focus on the following variables throughout this tutorial:</p>
<pre><code> **time:** Observed survival time in days
 **status:** censoring status 1=censored, 2=dead
 **sex:** 1=Male, 2=Female</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="projects-1.html#cb83-1" tabindex="-1"></a><span class="fu">head</span>(lung[, <span class="fu">c</span>(<span class="st">&quot;time&quot;</span>, <span class="st">&quot;status&quot;</span>, <span class="st">&quot;sex&quot;</span>)])</span></code></pre></div>
<pre><code>##   time status sex
## 1  306      2   1
## 2  455      2   1
## 3 1010      1   1
## 4  210      2   1
## 5  883      2   1
## 6 1022      1   1</code></pre>
<p>Note that the status is coded in a non-standard way in this dataset. Typically you will see 1=event, 0=censored. Let’s recode it to avoid confusion:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="projects-1.html#cb85-1" tabindex="-1"></a>lung1 <span class="ot">&lt;-</span> </span>
<span id="cb85-2"><a href="projects-1.html#cb85-2" tabindex="-1"></a>  lung <span class="sc">%&gt;%</span> </span>
<span id="cb85-3"><a href="projects-1.html#cb85-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb85-4"><a href="projects-1.html#cb85-4" tabindex="-1"></a>    <span class="at">status =</span> <span class="fu">recode</span>(status, <span class="st">&#39;1&#39;</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">&#39;2&#39;</span> <span class="ot">=</span> <span class="dv">1</span>)</span>
<span id="cb85-5"><a href="projects-1.html#cb85-5" tabindex="-1"></a>  )</span>
<span id="cb85-6"><a href="projects-1.html#cb85-6" tabindex="-1"></a></span>
<span id="cb85-7"><a href="projects-1.html#cb85-7" tabindex="-1"></a><span class="fu">head</span>(lung[, <span class="fu">c</span>(<span class="st">&quot;time&quot;</span>, <span class="st">&quot;status&quot;</span>, <span class="st">&quot;sex&quot;</span>)])</span></code></pre></div>
<pre><code>##   time status sex
## 1  306      2   1
## 2  455      2   1
## 3 1010      1   1
## 4  210      2   1
## 5  883      2   1
## 6 1022      1   1</code></pre>
<p>Now we have:</p>
<pre><code>time: Observed survival time in days
status: censoring status 0=censored, 1=dead
sex: 1=Male, 2=Female</code></pre>
<p>Note: the <code>Surv()</code> function in the {<code>survival</code>} package accepts by default TRUE/FALSE, where TRUE is event and FALSE is censored; 1/0 where 1 is event and 0 is censored; or 2/1 where 2 is event and 1 is censored. Please take care to ensure the event indicator is properly formatted.</p>
<p><strong>Calculating survival times</strong></p>
<p>Data will often come with start and end dates rather than pre-calculated survival times. The first step is to make sure these are formatted as dates in R.</p>
<p>Let’s create a small example dataset with variables <code>sx_date</code> for surgery date and <code>last_fup_date</code> for the last follow-up date:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="projects-1.html#cb88-1" tabindex="-1"></a>date_ex <span class="ot">&lt;-</span> </span>
<span id="cb88-2"><a href="projects-1.html#cb88-2" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb88-3"><a href="projects-1.html#cb88-3" tabindex="-1"></a>    <span class="at">sx_date =</span> <span class="fu">c</span>(<span class="st">&quot;2007-06-22&quot;</span>, <span class="st">&quot;2004-02-13&quot;</span>, <span class="st">&quot;2010-10-27&quot;</span>), </span>
<span id="cb88-4"><a href="projects-1.html#cb88-4" tabindex="-1"></a>    <span class="at">last_fup_date =</span> <span class="fu">c</span>(<span class="st">&quot;2017-04-15&quot;</span>, <span class="st">&quot;2018-07-04&quot;</span>, <span class="st">&quot;2016-10-31&quot;</span>)</span>
<span id="cb88-5"><a href="projects-1.html#cb88-5" tabindex="-1"></a>    )</span>
<span id="cb88-6"><a href="projects-1.html#cb88-6" tabindex="-1"></a></span>
<span id="cb88-7"><a href="projects-1.html#cb88-7" tabindex="-1"></a>date_ex</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   sx_date    last_fup_date
##   &lt;chr&gt;      &lt;chr&gt;        
## 1 2007-06-22 2017-04-15   
## 2 2004-02-13 2018-07-04   
## 3 2010-10-27 2016-10-31</code></pre>
<p>We see these are both <code>character</code> variables, but we need them to be formatted as <code>dates.</code></p>
<p>We will use the {<code>lubridate</code>} package to work with dates. In this case, we need to use the <code>ymd()</code> function to change the format, since the dates are currently in the character format where the year comes first, followed by the month, and followed by the day.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="projects-1.html#cb90-1" tabindex="-1"></a>date_ex1 <span class="ot">&lt;-</span></span>
<span id="cb90-2"><a href="projects-1.html#cb90-2" tabindex="-1"></a>  date_ex <span class="sc">%&gt;%</span> </span>
<span id="cb90-3"><a href="projects-1.html#cb90-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb90-4"><a href="projects-1.html#cb90-4" tabindex="-1"></a>    <span class="at">sx_date =</span> <span class="fu">ymd</span>(sx_date), </span>
<span id="cb90-5"><a href="projects-1.html#cb90-5" tabindex="-1"></a>    <span class="at">last_fup_date =</span> <span class="fu">ymd</span>(last_fup_date)</span>
<span id="cb90-6"><a href="projects-1.html#cb90-6" tabindex="-1"></a>    )</span>
<span id="cb90-7"><a href="projects-1.html#cb90-7" tabindex="-1"></a></span>
<span id="cb90-8"><a href="projects-1.html#cb90-8" tabindex="-1"></a>date_ex1</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   sx_date    last_fup_date
##   &lt;date&gt;     &lt;date&gt;       
## 1 2007-06-22 2017-04-15   
## 2 2004-02-13 2018-07-04   
## 3 2010-10-27 2016-10-31</code></pre>
<p>Now that the dates are formatted, we need to calculate the difference between start and end dates in some units, usually months or years. Using the {<code>lubridate</code>} package, the operator <code>%--%</code> designates a time interval, which is then converted to the number of elapsed seconds using <code>as.duration()</code> and finally converted to years by dividing by <code>dyears(1)</code>, which gives the number of seconds in a year.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="projects-1.html#cb92-1" tabindex="-1"></a>date_ex2 <span class="ot">&lt;-</span></span>
<span id="cb92-2"><a href="projects-1.html#cb92-2" tabindex="-1"></a>  date_ex1 <span class="sc">%&gt;%</span> </span>
<span id="cb92-3"><a href="projects-1.html#cb92-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb92-4"><a href="projects-1.html#cb92-4" tabindex="-1"></a>    <span class="at">observed_yrs =</span> <span class="fu">as.duration</span>(sx_date <span class="sc">%--%</span> last_fup_date) <span class="sc">/</span> <span class="fu">dyears</span>(<span class="dv">1</span>)</span>
<span id="cb92-5"><a href="projects-1.html#cb92-5" tabindex="-1"></a>    )</span>
<span id="cb92-6"><a href="projects-1.html#cb92-6" tabindex="-1"></a></span>
<span id="cb92-7"><a href="projects-1.html#cb92-7" tabindex="-1"></a>date_ex2</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   sx_date    last_fup_date observed_yrs
##   &lt;date&gt;     &lt;date&gt;               &lt;dbl&gt;
## 1 2007-06-22 2017-04-15            9.82
## 2 2004-02-13 2018-07-04           14.4 
## 3 2010-10-27 2016-10-31            6.01</code></pre>
<div id="creating-survival-objects-and-curves-1" class="section level4 hasAnchor" number="2.2.4.1">
<h4><span class="header-section-number">2.2.4.1</span> Creating survival objects and curves<a href="projects-1.html#creating-survival-objects-and-curves-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Kaplan-Meier method is the most common way to estimate survival times and probabilities. It is a <code>non-parametric</code> approach that results in a step function, where there is a step down each time an event occurs.</p>
<p>Lets see the data again:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="projects-1.html#cb94-1" tabindex="-1"></a>lung[, <span class="fu">c</span>(<span class="st">&quot;time&quot;</span>, <span class="st">&quot;status&quot;</span>)][<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span></code></pre></div>
<pre><code>##   time status
## 1  306      2
## 2  455      2
## 3 1010      1
## 4  210      2
## 5  883      2</code></pre>
<p>The <code>Surv()</code> function from the {<code>survival</code>} package creates a survival object for use as the response in a model formula. There will be one entry for each subject that is the survival time, which is followed by a + if the subject was censored.</p>
<p>Let’s look at the first 10 observations:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="projects-1.html#cb96-1" tabindex="-1"></a><span class="fu">Surv</span>(lung<span class="sc">$</span>time, lung<span class="sc">$</span>status)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1]  306   455  1010+  210   883  1022+  310   361   218   166</code></pre>
<p>We see that subject 1 had an event at time 306 days, subject 2 had an event at time 455 days, subject 3 was censored at time 1010 days, etc.</p>
<p>The <code>survfit()</code> function creates survival curves using the Kaplan-Meier method based on a formula. Let’s generate the overall survival curve for the entire cohort, assign it to object s1, and look at the structure using <code>str()</code>:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="projects-1.html#cb98-1" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung)</span>
<span id="cb98-2"><a href="projects-1.html#cb98-2" tabindex="-1"></a><span class="fu">str</span>(s1)</span></code></pre></div>
<pre><code>## List of 16
##  $ n        : int 228
##  $ time     : num [1:186] 5 11 12 13 15 26 30 31 53 54 ...
##  $ n.risk   : num [1:186] 228 227 224 223 221 220 219 218 217 215 ...
##  $ n.event  : num [1:186] 1 3 1 2 1 1 1 1 2 1 ...
##  $ n.censor : num [1:186] 0 0 0 0 0 0 0 0 0 0 ...
##  $ surv     : num [1:186] 0.996 0.982 0.978 0.969 0.965 ...
##  $ std.err  : num [1:186] 0.0044 0.00885 0.00992 0.01179 0.01263 ...
##  $ cumhaz   : num [1:186] 0.00439 0.0176 0.02207 0.03103 0.03556 ...
##  $ std.chaz : num [1:186] 0.00439 0.0088 0.00987 0.01173 0.01257 ...
##  $ type     : chr &quot;right&quot;
##  $ logse    : logi TRUE
##  $ conf.int : num 0.95
##  $ conf.type: chr &quot;log&quot;
##  $ lower    : num [1:186] 0.987 0.966 0.959 0.947 0.941 ...
##  $ upper    : num [1:186] 1 1 0.997 0.992 0.989 ...
##  $ call     : language survfit(formula = Surv(time, status) ~ 1, data = lung)
##  - attr(*, &quot;class&quot;)= chr &quot;survfit&quot;</code></pre>
<p><strong>n:</strong> There are 228 subjects in the data.</p>
<p><strong>time:</strong> Distinct time points.</p>
<p><strong>n.risk:</strong> Number of cases that have survived to the time plus the number of cases where the event occurs at the exact time.</p>
<p><strong>n.event:</strong> Number of event happened at the time.</p>
</div>
<div id="kaplan-meier-plotscurves-1" class="section level4 hasAnchor" number="2.2.4.2">
<h4><span class="header-section-number">2.2.4.2</span> Kaplan-Meier plots/Curves<a href="projects-1.html#kaplan-meier-plotscurves-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Kaplan Meier curve graphically represent the survival rate or survival function.</p>
<p>We will use the {<code>ggsurvfit</code>} package to generate Kaplan-Meier plots.</p>
<p>This package aims to ease plotting of time-to-event endpoints using the power of the {<code>ggplot2</code>} package. See <a href="http://www.danieldsjoberg.com/ggsurvfit/index.html" class="uri">http://www.danieldsjoberg.com/ggsurvfit/index.html</a> for details.</p>
<p>Note: alternatively, survival plots can be created using base R or the {<code>survminer</code>} package.</p>
<p>The {<code>ggsurvfit</code>} package works best if you create the <code>survfit</code> object using the included <code>ggsurvfit::survfit2()</code> function, which uses the same syntax to what we saw previously with <code>survival::survfit()</code>.</p>
<p>The <code>ggsurvfit::survfit2()</code> tracks the environment from the function call, which allows the plot to have better default values for labeling and p-value reporting.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="projects-1.html#cb100-1" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb100-2"><a href="projects-1.html#cb100-2" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb100-3"><a href="projects-1.html#cb100-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb100-4"><a href="projects-1.html#cb100-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>,</span>
<span id="cb100-5"><a href="projects-1.html#cb100-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Overall survival probability&quot;</span></span>
<span id="cb100-6"><a href="projects-1.html#cb100-6" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>The default plot in <code>ggsurvfit()</code> shows the step function only.</p>
<p>We can add the confidence interval using <code>add_confidence_interval()</code>:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="projects-1.html#cb101-1" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="projects-1.html#cb101-2" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb101-3"><a href="projects-1.html#cb101-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb101-4"><a href="projects-1.html#cb101-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>,</span>
<span id="cb101-5"><a href="projects-1.html#cb101-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Overall survival probability&quot;</span></span>
<span id="cb101-6"><a href="projects-1.html#cb101-6" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb101-7"><a href="projects-1.html#cb101-7" tabindex="-1"></a>  <span class="fu">add_confidence_interval</span>()</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>Typically we will also want to see the numbers at risk in a table below the x-axis.</p>
<p>We can add this using <code>add_risktable()</code>:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="projects-1.html#cb102-1" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb102-2"><a href="projects-1.html#cb102-2" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb102-3"><a href="projects-1.html#cb102-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb102-4"><a href="projects-1.html#cb102-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>,</span>
<span id="cb102-5"><a href="projects-1.html#cb102-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Overall survival probability&quot;</span></span>
<span id="cb102-6"><a href="projects-1.html#cb102-6" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb102-7"><a href="projects-1.html#cb102-7" tabindex="-1"></a>  <span class="fu">add_confidence_interval</span>() <span class="sc">+</span></span>
<span id="cb102-8"><a href="projects-1.html#cb102-8" tabindex="-1"></a>  <span class="fu">add_risktable</span>()</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>Plots can be customized using many standard {ggplot2} options.</p>
</div>
<div id="estimating-x-year-survival-1" class="section level4 hasAnchor" number="2.2.4.3">
<h4><span class="header-section-number">2.2.4.3</span> Estimating x-year survival<a href="projects-1.html#estimating-x-year-survival-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One quantity often of interest in a survival analysis is the probability of surviving beyond a certain number of years, x.</p>
<p>For example, to estimate the probability of surviving to 1 year, use summary with the times argument
(Note: the time variable in the lung data is actually in days, so we need to use <code>times = 365.25</code>)</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="projects-1.html#cb103-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung), <span class="at">times =</span> <span class="fl">365.25</span>)</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ 1, data = lung)
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##   365     65     121    0.409  0.0358        0.345        0.486</code></pre>
<pre><code>We find that the 1-year probability of survival in this study is 41%.</code></pre>
<p>The associated lower and upper bounds of the 95% confidence interval are also displayed.</p>
<p>The 1-year survival probability is the point on the y-axis that corresponds to 1
year on the x-axis for the survival curve.</p>
<p><img src="figs/survival3.png" /></p>
<p>What happens if you use a “naive” estimate? Here “naive” means that the patients who were censored prior to 1-year are considered event-free and included in the denominator.</p>
<p>121 of the 228 patients in the lung data died by 1 year so the “naive” estimate is calculated as:</p>
<p><span class="math display">\[(1−\frac{121}{228})×100=47\%\]</span></p>
<p>You get an incorrect estimate of the 1-year probability of survival when you ignore the fact that 42 patients were censored before 1-year.</p>
<p>Recall the correct estimate of the 1-year probability of survival, accounting for censoring using the Kaplan-Meier method, was 41%.</p>
<p>Ignoring censoring leads to an overestimate of the overall survival probability.</p>
<p>Imagine two studies, each with 228 subjects. There are 165 deaths in each study. Censoring is ignored in one (blue line), censoring is accounted for in the other (yellow line).</p>
<p>The censored subjects only contribute information for a portion of the follow-up time, and then fall out of the risk set, thus pulling down the cumulative probability of survival. Ignoring censoring erroneously treats patients who are censored as part of the risk set for the entire follow-up period.</p>
<p><img src="figs/survival4.png" /></p>
<p>We can produce nice tables of x-time survival probability estimates using the <code>tbl_survfit()</code> function from the {<code>gtsummary</code>} package:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="projects-1.html#cb106-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb106-2"><a href="projects-1.html#cb106-2" tabindex="-1"></a>  <span class="fu">tbl_survfit</span>(</span>
<span id="cb106-3"><a href="projects-1.html#cb106-3" tabindex="-1"></a>    <span class="at">times =</span> <span class="fl">365.25</span>,</span>
<span id="cb106-4"><a href="projects-1.html#cb106-4" tabindex="-1"></a>    <span class="at">label_header =</span> <span class="st">&quot;**1-year survival (95% CI)**&quot;</span></span>
<span id="cb106-5"><a href="projects-1.html#cb106-5" tabindex="-1"></a>  )</span></code></pre></div>
<div id="anakodxnce" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#anakodxnce table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#anakodxnce thead, #anakodxnce tbody, #anakodxnce tfoot, #anakodxnce tr, #anakodxnce td, #anakodxnce th {
  border-style: none;
}

#anakodxnce p {
  margin: 0;
  padding: 0;
}

#anakodxnce .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#anakodxnce .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#anakodxnce .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#anakodxnce .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#anakodxnce .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#anakodxnce .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#anakodxnce .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#anakodxnce .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#anakodxnce .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#anakodxnce .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#anakodxnce .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#anakodxnce .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#anakodxnce .gt_spanner_row {
  border-bottom-style: hidden;
}

#anakodxnce .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#anakodxnce .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#anakodxnce .gt_from_md > :first-child {
  margin-top: 0;
}

#anakodxnce .gt_from_md > :last-child {
  margin-bottom: 0;
}

#anakodxnce .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#anakodxnce .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#anakodxnce .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#anakodxnce .gt_row_group_first td {
  border-top-width: 2px;
}

#anakodxnce .gt_row_group_first th {
  border-top-width: 2px;
}

#anakodxnce .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#anakodxnce .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#anakodxnce .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#anakodxnce .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#anakodxnce .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#anakodxnce .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#anakodxnce .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#anakodxnce .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#anakodxnce .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#anakodxnce .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#anakodxnce .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#anakodxnce .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#anakodxnce .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#anakodxnce .gt_left {
  text-align: left;
}

#anakodxnce .gt_center {
  text-align: center;
}

#anakodxnce .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#anakodxnce .gt_font_normal {
  font-weight: normal;
}

#anakodxnce .gt_font_bold {
  font-weight: bold;
}

#anakodxnce .gt_font_italic {
  font-style: italic;
}

#anakodxnce .gt_super {
  font-size: 65%;
}

#anakodxnce .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#anakodxnce .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#anakodxnce .gt_indent_1 {
  text-indent: 5px;
}

#anakodxnce .gt_indent_2 {
  text-indent: 10px;
}

#anakodxnce .gt_indent_3 {
  text-indent: 15px;
}

#anakodxnce .gt_indent_4 {
  text-indent: 20px;
}

#anakodxnce .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;1-year survival (95% CI)&lt;/strong&gt;"><strong>1-year survival (95% CI)</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Overall</td>
<td headers="stat_1" class="gt_row gt_center">41% (34%, 49%)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
<div id="estimating-median-survival-time-1" class="section level4 hasAnchor" number="2.2.4.4">
<h4><span class="header-section-number">2.2.4.4</span> Estimating median survival time<a href="projects-1.html#estimating-median-survival-time-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Another quantity often of interest in a survival analysis is the average survival time, which we quantify using the median. Survival times are not expected to be normally distributed so the mean is not an appropriate summary.</p>
<p>We can obtain the median survival directly from the <code>survfit</code> object:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="projects-1.html#cb107-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung)</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ 1, data = lung)
## 
##        n events median 0.95LCL 0.95UCL
## [1,] 228    165    310     285     363</code></pre>
<p>We see the median survival time is 310 days The lower and upper bounds of the 95% confidence interval are also displayed.</p>
<p>Median survival is the time corresponding to a survival probability of 0.5:</p>
<p><img src="figs/survival5.png" /></p>
<p>What happens if you use a “naive” estimate? Here “naive” means that you exclude the censored patients from the calculation entirely to estimate median survival time among the patients who have had the event.</p>
<p>Summarize the median survival time among the 165 patients who died:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="projects-1.html#cb109-1" tabindex="-1"></a>lung <span class="sc">%&gt;%</span> </span>
<span id="cb109-2"><a href="projects-1.html#cb109-2" tabindex="-1"></a>  <span class="fu">filter</span>(status <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb109-3"><a href="projects-1.html#cb109-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_surv =</span> <span class="fu">median</span>(time))</span></code></pre></div>
<pre><code>##   median_surv
## 1         284</code></pre>
<p>You get an incorrect estimate of median survival time of 284 days when you ignore the fact that censored patients also contribute follow-up time.</p>
<p>Recall the correct estimate of median survival time is 310 days.</p>
<p>Ignoring censoring will lead to an underestimate of median survival time because the follow-up time that censored patients contribute is excluded (blue line). The true survival curve accounting for censoring in the lung data is shown in yellow for comparison.</p>
<p><img src="figs/survival6.png" /></p>
<p>We can produce nice tables of median survival time estimates using the <code>tbl_survfit()</code> function from the {<code>gtsummary</code>} package:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="projects-1.html#cb111-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb111-2"><a href="projects-1.html#cb111-2" tabindex="-1"></a>  <span class="fu">tbl_survfit</span>(</span>
<span id="cb111-3"><a href="projects-1.html#cb111-3" tabindex="-1"></a>    <span class="at">probs =</span> <span class="fl">0.5</span>,</span>
<span id="cb111-4"><a href="projects-1.html#cb111-4" tabindex="-1"></a>    <span class="at">label_header =</span> <span class="st">&quot;**Median survival (95% CI)**&quot;</span></span>
<span id="cb111-5"><a href="projects-1.html#cb111-5" tabindex="-1"></a>  )</span></code></pre></div>
<div id="yekcjfrvoo" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#yekcjfrvoo table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#yekcjfrvoo thead, #yekcjfrvoo tbody, #yekcjfrvoo tfoot, #yekcjfrvoo tr, #yekcjfrvoo td, #yekcjfrvoo th {
  border-style: none;
}

#yekcjfrvoo p {
  margin: 0;
  padding: 0;
}

#yekcjfrvoo .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#yekcjfrvoo .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#yekcjfrvoo .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yekcjfrvoo .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yekcjfrvoo .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yekcjfrvoo .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yekcjfrvoo .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yekcjfrvoo .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#yekcjfrvoo .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#yekcjfrvoo .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#yekcjfrvoo .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#yekcjfrvoo .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#yekcjfrvoo .gt_spanner_row {
  border-bottom-style: hidden;
}

#yekcjfrvoo .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#yekcjfrvoo .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#yekcjfrvoo .gt_from_md > :first-child {
  margin-top: 0;
}

#yekcjfrvoo .gt_from_md > :last-child {
  margin-bottom: 0;
}

#yekcjfrvoo .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#yekcjfrvoo .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#yekcjfrvoo .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#yekcjfrvoo .gt_row_group_first td {
  border-top-width: 2px;
}

#yekcjfrvoo .gt_row_group_first th {
  border-top-width: 2px;
}

#yekcjfrvoo .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yekcjfrvoo .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#yekcjfrvoo .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#yekcjfrvoo .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yekcjfrvoo .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yekcjfrvoo .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#yekcjfrvoo .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#yekcjfrvoo .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#yekcjfrvoo .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yekcjfrvoo .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yekcjfrvoo .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yekcjfrvoo .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yekcjfrvoo .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yekcjfrvoo .gt_left {
  text-align: left;
}

#yekcjfrvoo .gt_center {
  text-align: center;
}

#yekcjfrvoo .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yekcjfrvoo .gt_font_normal {
  font-weight: normal;
}

#yekcjfrvoo .gt_font_bold {
  font-weight: bold;
}

#yekcjfrvoo .gt_font_italic {
  font-style: italic;
}

#yekcjfrvoo .gt_super {
  font-size: 65%;
}

#yekcjfrvoo .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#yekcjfrvoo .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#yekcjfrvoo .gt_indent_1 {
  text-indent: 5px;
}

#yekcjfrvoo .gt_indent_2 {
  text-indent: 10px;
}

#yekcjfrvoo .gt_indent_3 {
  text-indent: 15px;
}

#yekcjfrvoo .gt_indent_4 {
  text-indent: 20px;
}

#yekcjfrvoo .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Median survival (95% CI)&lt;/strong&gt;"><strong>Median survival (95% CI)</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Overall</td>
<td headers="stat_1" class="gt_row gt_center">310 (285, 363)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
<div id="comparing-survival-times-between-groups-1" class="section level4 hasAnchor" number="2.2.4.5">
<h4><span class="header-section-number">2.2.4.5</span> Comparing survival times between groups<a href="projects-1.html#comparing-survival-times-between-groups-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can conduct between-group significance tests using a <code>log-rank test</code>.</p>
<p>The log-rank test equally weights observations over the entire follow-up time and is the most common way to compare survival times between groups. There are versions that more heavily weight the early or late follow-up that could be more appropriate depending on the research question (see <code>?survdiff</code> for different test options).</p>
<p>We get the log-rank p-value using the <code>survdiff</code> function. For example, we can test whether there was a difference in survival time according to sex in the lung data:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="projects-1.html#cb112-1" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(time, status) ~ sex, data = lung)
## 
##         N Observed Expected (O-E)^2/E (O-E)^2/V
## sex=1 138      112     91.6      4.55      10.3
## sex=2  90       53     73.4      5.68      10.3
## 
##  Chisq= 10.3  on 1 degrees of freedom, p= 0.001</code></pre>
<p>We see that there was a significant difference in overall survival according to sex in the lung data, with a p-value of <code>p = 0.001</code>.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="projects-1.html#cb114-1" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;survival&quot;</span>)</span>
<span id="cb114-2"><a href="projects-1.html#cb114-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;survminer&quot;</span>)</span>
<span id="cb114-3"><a href="projects-1.html#cb114-3" tabindex="-1"></a></span>
<span id="cb114-4"><a href="projects-1.html#cb114-4" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung)</span>
<span id="cb114-5"><a href="projects-1.html#cb114-5" tabindex="-1"></a></span>
<span id="cb114-6"><a href="projects-1.html#cb114-6" tabindex="-1"></a><span class="fu">ggsurvplot</span>(fit, <span class="at">data =</span> lung)</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="projects-1.html#cb115-1" tabindex="-1"></a><span class="fu">ggsurvplot</span>(</span>
<span id="cb115-2"><a href="projects-1.html#cb115-2" tabindex="-1"></a>  fit,</span>
<span id="cb115-3"><a href="projects-1.html#cb115-3" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb115-4"><a href="projects-1.html#cb115-4" tabindex="-1"></a>  <span class="at">size =</span> <span class="dv">1</span>,                 <span class="co"># change line size</span></span>
<span id="cb115-5"><a href="projects-1.html#cb115-5" tabindex="-1"></a>  <span class="at">palette =</span></span>
<span id="cb115-6"><a href="projects-1.html#cb115-6" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">&quot;#E7B800&quot;</span>, <span class="st">&quot;#2E9FDF&quot;</span>),<span class="co"># custom color palettes</span></span>
<span id="cb115-7"><a href="projects-1.html#cb115-7" tabindex="-1"></a>  <span class="at">conf.int =</span> <span class="cn">TRUE</span>,          <span class="co"># Add confidence interval</span></span>
<span id="cb115-8"><a href="projects-1.html#cb115-8" tabindex="-1"></a>  <span class="at">pval =</span> <span class="cn">TRUE</span>,              <span class="co"># Add p-value</span></span>
<span id="cb115-9"><a href="projects-1.html#cb115-9" tabindex="-1"></a>  <span class="at">risk.table =</span> <span class="cn">TRUE</span>,        <span class="co"># Add risk table</span></span>
<span id="cb115-10"><a href="projects-1.html#cb115-10" tabindex="-1"></a>  <span class="at">risk.table.col =</span> <span class="st">&quot;strata&quot;</span>,<span class="co"># Risk table color by groups</span></span>
<span id="cb115-11"><a href="projects-1.html#cb115-11" tabindex="-1"></a>  <span class="at">legend.labs =</span></span>
<span id="cb115-12"><a href="projects-1.html#cb115-12" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>),    <span class="co"># Change legend labels</span></span>
<span id="cb115-13"><a href="projects-1.html#cb115-13" tabindex="-1"></a>  <span class="at">risk.table.height =</span> <span class="fl">0.25</span>, <span class="co"># Useful to change when you have multiple groups</span></span>
<span id="cb115-14"><a href="projects-1.html#cb115-14" tabindex="-1"></a>  <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>()      <span class="co"># Change ggplot2 theme</span></span>
<span id="cb115-15"><a href="projects-1.html#cb115-15" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="Project_Archive_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
</div>
<div id="the-cox-regression-model-1" class="section level4 hasAnchor" number="2.2.4.6">
<h4><span class="header-section-number">2.2.4.6</span> The Cox regression model<a href="projects-1.html#the-cox-regression-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We may want to quantify an effect size for a single variable, or include more than one variable into a regression model to account for the effects of multiple variables.</p>
<p>The Cox regression model is a semi-parametric model that can be used to fit univariable and multivariable regression models that have survival outcomes.</p>
<p><span class="math display">\[h(t|Xi)=h0(t)exp(β1Xi1+⋯+βpXip)\]</span></p>
<dl>
<dt><span class="math inline">\(h(t)\)</span></dt>
<dd>
hazard, or the instantaneous rate at which events occur h0(t)
</dd>
<dd>
underlying baseline hazard
</dd>
</dl>
<p>Some key assumptions of the model:</p>
<p>non-informative censoring
proportional hazards</p>
<p><strong>Note:</strong> parametric regression models for survival outcomes are also available, but they won’t be addressed here.</p>
<p>We can fit regression models for survival data using the <code>coxph()</code> function from the {<code>survival</code>} package, which takes a <code>Surv()</code> object on the left hand side and has standard syntax for regression formulas in R on the right hand side.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="projects-1.html#cb116-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex, data = lung)
## 
##        coef exp(coef) se(coef)      z       p
## sex -0.5310    0.5880   0.1672 -3.176 0.00149
## 
## Likelihood ratio test=10.63  on 1 df, p=0.001111
## n= 228, number of events= 165</code></pre>
<p>We can obtain tables of results using the <code>tbl_regression()</code> function from the {<code>gtsummary</code>} package, with the option to <code>exponentiate</code> set to <code>TRUE</code> to return the hazard ratio rather than the log hazard ratio:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="projects-1.html#cb118-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex, <span class="at">data =</span> lung) <span class="sc">%&gt;%</span> </span>
<span id="cb118-2"><a href="projects-1.html#cb118-2" tabindex="-1"></a>  <span class="fu">tbl_regression</span>(<span class="at">exp =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="onxvrpjjsr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#onxvrpjjsr table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#onxvrpjjsr thead, #onxvrpjjsr tbody, #onxvrpjjsr tfoot, #onxvrpjjsr tr, #onxvrpjjsr td, #onxvrpjjsr th {
  border-style: none;
}

#onxvrpjjsr p {
  margin: 0;
  padding: 0;
}

#onxvrpjjsr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#onxvrpjjsr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#onxvrpjjsr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#onxvrpjjsr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#onxvrpjjsr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#onxvrpjjsr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#onxvrpjjsr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#onxvrpjjsr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#onxvrpjjsr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#onxvrpjjsr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#onxvrpjjsr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#onxvrpjjsr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#onxvrpjjsr .gt_spanner_row {
  border-bottom-style: hidden;
}

#onxvrpjjsr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#onxvrpjjsr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#onxvrpjjsr .gt_from_md > :first-child {
  margin-top: 0;
}

#onxvrpjjsr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#onxvrpjjsr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#onxvrpjjsr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#onxvrpjjsr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#onxvrpjjsr .gt_row_group_first td {
  border-top-width: 2px;
}

#onxvrpjjsr .gt_row_group_first th {
  border-top-width: 2px;
}

#onxvrpjjsr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#onxvrpjjsr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#onxvrpjjsr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#onxvrpjjsr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#onxvrpjjsr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#onxvrpjjsr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#onxvrpjjsr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#onxvrpjjsr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#onxvrpjjsr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#onxvrpjjsr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#onxvrpjjsr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#onxvrpjjsr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#onxvrpjjsr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#onxvrpjjsr .gt_left {
  text-align: left;
}

#onxvrpjjsr .gt_center {
  text-align: center;
}

#onxvrpjjsr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#onxvrpjjsr .gt_font_normal {
  font-weight: normal;
}

#onxvrpjjsr .gt_font_bold {
  font-weight: bold;
}

#onxvrpjjsr .gt_font_italic {
  font-style: italic;
}

#onxvrpjjsr .gt_super {
  font-size: 65%;
}

#onxvrpjjsr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#onxvrpjjsr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#onxvrpjjsr .gt_indent_1 {
  text-indent: 5px;
}

#onxvrpjjsr .gt_indent_2 {
  text-indent: 10px;
}

#onxvrpjjsr .gt_indent_3 {
  text-indent: 15px;
}

#onxvrpjjsr .gt_indent_4 {
  text-indent: 20px;
}

#onxvrpjjsr .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;HR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>HR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;p-value&lt;/strong&gt;"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">sex</td>
<td headers="estimate" class="gt_row gt_center">0.59</td>
<td headers="ci" class="gt_row gt_center">0.42, 0.82</td>
<td headers="p.value" class="gt_row gt_center">0.001</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> HR = Hazard Ratio, CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
<p>The quantity of interest from a Cox regression model is a hazard ratio (HR). The HR represents the ratio of hazards between two groups at any particular point in time.</p>
<p>The HR is interpreted as the instantaneous rate of occurrence of the event of interest in those who are still at risk for the event. It is not a risk, though it is commonly mis-interpreted as such. If you have a regression parameter β, then <span class="math inline">\(HR = exp(β)\)</span></p>
<p>A HR &lt; 1 indicates reduced hazard of death whereas a HR &gt; 1 indicates an increased hazard of death.</p>
<p>So the HR = 0.59 implies that 0.59 times as many females are dying as males, at any given time. Stated differently, females have a significantly lower hazard of death than males in these data.</p>

</div>
</div>
<div id="prosper-loan-data-1" class="section level3 hasAnchor" number="2.2.5">
<h3><span class="header-section-number">2.2.5</span> Prosper Loan data<a href="projects-1.html#prosper-loan-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="projects-1.html#cb119-1" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb119-2"><a href="projects-1.html#cb119-2" tabindex="-1"></a></span>
<span id="cb119-3"><a href="projects-1.html#cb119-3" tabindex="-1"></a><span class="co"># web &lt;- &quot;https://s3.amazonaws.com/udacity-hosted-downloads/ud651/prosperLoanData.csv&quot;</span></span>
<span id="cb119-4"><a href="projects-1.html#cb119-4" tabindex="-1"></a><span class="co"># loan &lt;- fread(web)</span></span>
<span id="cb119-5"><a href="projects-1.html#cb119-5" tabindex="-1"></a></span>
<span id="cb119-6"><a href="projects-1.html#cb119-6" tabindex="-1"></a><span class="co"># head(loan)[, c(51, 65, 6, 7, 19, 18, 50)]</span></span></code></pre></div>

</div>
<div id="customer-churn-1" class="section level3 hasAnchor" number="2.2.6">
<h3><span class="header-section-number">2.2.6</span> Customer Churn<a href="projects-1.html#customer-churn-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It usually costs more to acquire a customer than it does to retain a customer.</p>
<p>Focusing on customer retention enables companies to maximize customer revenue over their lifetime.</p>
<p>These models are seldom done optimally as they rely on binary classification flags (churn yes or no). Churn classification models do not tell WHEN a customer is likely to leave but only indicate that it’s going to happen within a certain number of days or months.</p>
<p>In the churn classification model, we don’t usually account for the differences in time.</p>
<p>It is probably a mistake to treat a customer that is at risk of leaving in 40 days the same as a customer that remains for over a 100 days. Traditional churn modeling does not make this differentiation.</p>
<p><img src="figs/churn1.png" /></p>
<p>As it fails to account for time, we have no clear idea at what point a marketing intervention is needed and it causes preventable customer attrition.</p>
<p>The only point in time here is the “within 40 days” threshold. As it fails to account for time, we have no clear idea at what point a marketing intervention is needed and it causes preventable customer attrition.</p>
<div id="re-framing-the-problem-to-know-when-1" class="section level4 hasAnchor" number="2.2.6.1">
<h4><span class="header-section-number">2.2.6.1</span> Re-framing the Problem to Know When<a href="projects-1.html#re-framing-the-problem-to-know-when-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Rather then use a binary classifier, we are going to re-frame the problem as time-dependent one. This enables us to intervene at the right time to stop customer attrition before it happens.</p>
<p>No longer relying on thresholds, we now set churn as continuous time conditioned event. As the below graph shows, we now know the time that attrition risk is most likely to happen.</p>
<p><img src="figs/churn2.png" /></p>
<p>No longer is time held constant, we now track risk over time to determine when a marketing intervention is needed to retain the customer.</p>
<p>If we model for both the time and event, the right moment to intervene and prevent attrition is apparent. A modeling technique called <code>Survival Analysis</code> allows for us to do this and with the advent of modern Machine Learning, it’s now a trivial task.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb120-1"><a href="projects-1.html#cb120-1" tabindex="-1"></a><span class="co"># %reload_ext autoreload</span></span>
<span id="cb120-2"><a href="projects-1.html#cb120-2" tabindex="-1"></a><span class="co"># %autoreload 2</span></span>
<span id="cb120-3"><a href="projects-1.html#cb120-3" tabindex="-1"></a><span class="co"># %matplotlib inline</span></span>
<span id="cb120-4"><a href="projects-1.html#cb120-4" tabindex="-1"></a></span>
<span id="cb120-5"><a href="projects-1.html#cb120-5" tabindex="-1"></a><span class="im">import</span> xgboost <span class="im">as</span> xgb</span>
<span id="cb120-6"><a href="projects-1.html#cb120-6" tabindex="-1"></a><span class="im">import</span> shap</span>
<span id="cb120-7"><a href="projects-1.html#cb120-7" tabindex="-1"></a><span class="im">import</span> sksurv.metrics <span class="im">as</span> surv_metrics</span>
<span id="cb120-8"><a href="projects-1.html#cb120-8" tabindex="-1"></a><span class="im">from</span> sksurv.datasets <span class="im">import</span> get_x_y</span>
<span id="cb120-9"><a href="projects-1.html#cb120-9" tabindex="-1"></a><span class="im">from</span> lifelines <span class="im">import</span> KaplanMeierFitter</span>
<span id="cb120-10"><a href="projects-1.html#cb120-10" tabindex="-1"></a><span class="im">from</span> lifelines.plotting <span class="im">import</span> plot_lifetimes</span>
<span id="cb120-11"><a href="projects-1.html#cb120-11" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb120-12"><a href="projects-1.html#cb120-12" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb120-13"><a href="projects-1.html#cb120-13" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb120-14"><a href="projects-1.html#cb120-14" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb120-15"><a href="projects-1.html#cb120-15" tabindex="-1"></a><span class="im">from</span> sklearn.compose <span class="im">import</span> ColumnTransformer</span>
<span id="cb120-16"><a href="projects-1.html#cb120-16" tabindex="-1"></a><span class="im">from</span> sklearn.exceptions <span class="im">import</span> DataConversionWarning</span>
<span id="cb120-17"><a href="projects-1.html#cb120-17" tabindex="-1"></a><span class="im">from</span> sklearn.impute <span class="im">import</span> SimpleImputer</span>
<span id="cb120-18"><a href="projects-1.html#cb120-18" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb120-19"><a href="projects-1.html#cb120-19" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb120-20"><a href="projects-1.html#cb120-20" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> OneHotEncoder, StandardScaler</span>
<span id="cb120-21"><a href="projects-1.html#cb120-21" tabindex="-1"></a></span>
<span id="cb120-22"><a href="projects-1.html#cb120-22" tabindex="-1"></a></span>
<span id="cb120-23"><a href="projects-1.html#cb120-23" tabindex="-1"></a></span>
<span id="cb120-24"><a href="projects-1.html#cb120-24" tabindex="-1"></a>plt.rcParams[<span class="st">&#39;figure.figsize&#39;</span>] <span class="op">=</span> [<span class="fl">7.2</span>, <span class="fl">4.8</span>]</span>
<span id="cb120-25"><a href="projects-1.html#cb120-25" tabindex="-1"></a>pd.set_option(<span class="st">&quot;display.float_format&quot;</span>, <span class="kw">lambda</span> x: <span class="st">&quot;</span><span class="sc">%.4f</span><span class="st">&quot;</span> <span class="op">%</span> x)</span>
<span id="cb120-26"><a href="projects-1.html#cb120-26" tabindex="-1"></a></span>
<span id="cb120-27"><a href="projects-1.html#cb120-27" tabindex="-1"></a>sns.set_style(<span class="st">&#39;darkgrid&#39;</span>)</span>
<span id="cb120-28"><a href="projects-1.html#cb120-28" tabindex="-1"></a></span>
<span id="cb120-29"><a href="projects-1.html#cb120-29" tabindex="-1"></a>SEED <span class="op">=</span> <span class="dv">123</span></span></code></pre></div>
<div class="sourceCode" id="cb121"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb121-1"><a href="projects-1.html#cb121-1" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">&quot;../../data/churn.txt&quot;</span>)</span>
<span id="cb121-2"><a href="projects-1.html#cb121-2" tabindex="-1"></a><span class="co"># denoting churn and duration</span></span>
<span id="cb121-3"><a href="projects-1.html#cb121-3" tabindex="-1"></a>df[<span class="st">&quot;event&quot;</span>] <span class="op">=</span> np.where(df[<span class="st">&quot;churn?&quot;</span>] <span class="op">==</span> <span class="st">&quot;False.&quot;</span>, <span class="dv">0</span>, <span class="dv">1</span>) </span>
<span id="cb121-4"><a href="projects-1.html#cb121-4" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>{<span class="st">&quot;account_length&quot;</span>: <span class="st">&quot;duration&quot;</span>})</span>
<span id="cb121-5"><a href="projects-1.html#cb121-5" tabindex="-1"></a><span class="kw">del</span> df[<span class="st">&#39;churn?&#39;</span>]</span>
<span id="cb121-6"><a href="projects-1.html#cb121-6" tabindex="-1"></a>df <span class="op">=</span> df.dropna()</span>
<span id="cb121-7"><a href="projects-1.html#cb121-7" tabindex="-1"></a>df <span class="op">=</span> df.drop_duplicates()</span>
<span id="cb121-8"><a href="projects-1.html#cb121-8" tabindex="-1"></a>df.head()</span></code></pre></div>
<div class="sourceCode" id="cb122"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb122-1"><a href="projects-1.html#cb122-1" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Total Records:&quot;</span>,df.shape[<span class="dv">0</span>],<span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span>
<span id="cb122-2"><a href="projects-1.html#cb122-2" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Percent Churn Rate:&quot;</span>,df.event.mean())</span>
<span id="cb122-3"><a href="projects-1.html#cb122-3" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;&quot;</span>)</span>
<span id="cb122-4"><a href="projects-1.html#cb122-4" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Duration Intervals&quot;</span>)</span>
<span id="cb122-5"><a href="projects-1.html#cb122-5" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">&#39;duration&#39;</span>].describe())</span></code></pre></div>
<p>For Survival models data is different from a traditional classification problem and requires:
- A Censor — For our purposes these are customers who’ve yet to churn. Read about right censoring here.</p>
<ul>
<li><p>Duration — The duration or time t of the customer’s activity. In this case, it’s Account Length in days.</p></li>
<li><p>Event — The binary target, in this case if they terminated their phone plan marked by Churn? .</p></li>
</ul>
<div class="sourceCode" id="cb123"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb123-1"><a href="projects-1.html#cb123-1" tabindex="-1"></a>ax <span class="op">=</span> plot_lifetimes(df.head(<span class="dv">10</span>)[<span class="st">&#39;duration&#39;</span>], df.head(<span class="dv">10</span>)[<span class="st">&#39;event&#39;</span>])</span>
<span id="cb123-2"><a href="projects-1.html#cb123-2" tabindex="-1"></a>_<span class="op">=</span>ax.set_xlabel(<span class="st">&quot;Duration: Account Length (days)&quot;</span>) _<span class="op">=</span>ax.set_ylabel(<span class="st">&quot;Customer Number&quot;</span>) _<span class="op">=</span>ax.set_title(<span class="st">&quot;Observed Customer Attrition&quot;</span>)</span></code></pre></div>
<p><img src="figs/churn3.png" /></p>
<p>In the above plot, the red lines indicates when a customer has left with the dots indicating the specific point in time.</p>
<p>Blue lines are customers that are still active up to the time measured on the x-axis in Duration.</p>
<p>Here we see that customer number 8 did not attrit until up to 195 days, with customer numbers 0 and 4 leaving in 163 and 146 days respectively. All other customers are still active.</p>
<p>Notice how all customers are set on the same time scale because the data is analytically aligned. Each customer might have come in at different times but we’ve set the days as the same.</p>
<p>This is what allowed us to right-censor the data on the churn event. Real world data needs both censoring and aligning before modeling can begin.</p>
</div>
<div id="the-risk-of-churn-1" class="section level4 hasAnchor" number="2.2.6.2">
<h4><span class="header-section-number">2.2.6.2</span> The Risk of Churn<a href="projects-1.html#the-risk-of-churn-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A more informative approach might be to estimate the Survival Function or the time in days a customer has until they attrit. For this purpose, we will use a Kaplan Meier Estimator to calculate how long until attrition occurs. The estimator is defined as:</p>
<p><img src="figs/churn4.png" /></p>
<p>Where <span class="math inline">\(𝑑_𝑖\)</span> are the number of churn events at time <span class="math inline">\(𝑡\)</span> and <span class="math inline">\(𝑛_𝑖\)</span> is the number of customers at risk of churn just prior to time <span class="math inline">\(𝑡\)</span>.</p>
<p>We will use the great python package <code>lifelines</code> to plot the Survival Function as the function is a component of the final churn model.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb124-1"><a href="projects-1.html#cb124-1" tabindex="-1"></a>kmf <span class="op">=</span> KaplanMeierFitter()</span>
<span id="cb124-2"><a href="projects-1.html#cb124-2" tabindex="-1"></a>kmf.fit(df[<span class="st">&#39;duration&#39;</span>], event_observed<span class="op">=</span>df[<span class="st">&#39;event&#39;</span>])</span>
<span id="cb124-3"><a href="projects-1.html#cb124-3" tabindex="-1"></a>kmf.plot_survival_function()</span>
<span id="cb124-4"><a href="projects-1.html#cb124-4" tabindex="-1"></a></span>
<span id="cb124-5"><a href="projects-1.html#cb124-5" tabindex="-1"></a>_<span class="op">=</span>plt.title(<span class="st">&#39;Survival Function for Telco Churn&#39;</span>)<span class="op">;</span> _<span class="op">=</span>plt.xlabel(<span class="st">&quot;Duration: Account Length (days)&quot;</span>)</span>
<span id="cb124-6"><a href="projects-1.html#cb124-6" tabindex="-1"></a>_<span class="op">=</span>plt.ylabel(<span class="st">&quot;Churn Risk (Percent Churned)&quot;</span>) </span>
<span id="cb124-7"><a href="projects-1.html#cb124-7" tabindex="-1"></a>_<span class="op">=</span>plt.axvline(x<span class="op">=</span>kmf.median_survival_time_, color<span class="op">=</span><span class="st">&#39;r&#39;</span>,linestyle<span class="op">=</span><span class="st">&#39;--&#39;</span>)</span></code></pre></div>
<p><img src="figs/churn5.png" /></p>
<p>Let’s look at the <code>median</code> survival time. This is the point by which half of customers have churned out. According to this graph, where it’s marked by the red dotted line, by about 152 days half of customers churn.</p>
<p>This is helpful because it gives overall baseline when intervention is needed. However, for each individual customer this is uninformative.
<strong>What is missing is the point in time in which churn risk is highest for each customer.</strong></p>
<p>For that we will create a model using <code>Cox’s Proportional Hazard</code> which uses a log-risk function <span class="math inline">\(h(x)\)</span>. The Hazard function is conditioned on rate of a customers remaining until time t or later, this allows to estimate the risk of churn overtime.</p>
<p>This will enable us to score each customer and anticipate when a marketing intervention is needed. However, before we proceed to that, we need to preprocess the data.</p>
</div>
<div id="data-splitting-and-preprocessing-1" class="section level4 hasAnchor" number="2.2.6.3">
<h4><span class="header-section-number">2.2.6.3</span> Data Splitting and Preprocessing<a href="projects-1.html#data-splitting-and-preprocessing-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>First we will split the data into training and testing. We’ll use the testing set as the validation for the example.</p>
<pre><code>In practice, you want all three of these splits so that you don’t tune to the validation set.</code></pre>
<p>Next, we take the numeric features and categorical features and then preprocess them for downstream modeling.</p>
<p>In the case of categories, we will first impute with the constant and then simply one-hot encode them. In the case of numerics, we will fill with the median then standardize them between values of 0 and 1. This is all wrapped into Sklearn’s Pipeline and ColumnTransformer for simplicity’s sake.
As part of the Churn Pipeline all these steps are included with the final preprocessor saved for use at inference time.</p>

</div>
</div>
<div id="deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws-1" class="section level3 hasAnchor" number="2.2.7">
<h3><span class="header-section-number">2.2.7</span> Deploying a Scalable End to End Customer Churn Prediction Solution with AWS<a href="projects-1.html#deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><a href="https://towardsdatascience.com/deploying-a-scalable-end-to-end-customer-churn-prediction-solution-with-aws-cbf3536be996">Source</a></p>
<p>Wouldn’t it be great if you could hold onto customers longer, maximizing their lifetime revenue?</p>
<p>In this blog post, you will deploy an End to End Customer Churn Prediction solution using AWS services.</p>

<div class="sourceCode" id="cb126"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb126-1"><a href="projects-1.html#cb126-1" tabindex="-1"></a><span class="im">import</span> findspark</span>
<span id="cb126-2"><a href="projects-1.html#cb126-2" tabindex="-1"></a>findspark.init()</span></code></pre></div>
<div class="sourceCode" id="cb127"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb127-1"><a href="projects-1.html#cb127-1" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb127-2"><a href="projects-1.html#cb127-2" tabindex="-1"></a><span class="im">from</span> pyspark <span class="im">import</span> SparkFiles</span>
<span id="cb127-3"><a href="projects-1.html#cb127-3" tabindex="-1"></a><span class="im">from</span> pyspark.ml.classification <span class="im">import</span> LogisticRegression</span>
<span id="cb127-4"><a href="projects-1.html#cb127-4" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> BinaryClassificationEvaluator, MulticlassClassificationEvaluator</span>
<span id="cb127-5"><a href="projects-1.html#cb127-5" tabindex="-1"></a><span class="im">from</span> pyspark.ml.tuning <span class="im">import</span> CrossValidator, ParamGridBuilder</span>
<span id="cb127-6"><a href="projects-1.html#cb127-6" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> VectorAssembler</span></code></pre></div>
<div class="sourceCode" id="cb128"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb128-1"><a href="projects-1.html#cb128-1" tabindex="-1"></a>my_appname <span class="op">=</span> <span class="st">&quot;LogisticRegression with PySpark MLlib&quot;</span></span>
<span id="cb128-2"><a href="projects-1.html#cb128-2" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.appName(my_appname).getOrCreate()</span></code></pre></div>
<div class="sourceCode" id="cb129"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb129-1"><a href="projects-1.html#cb129-1" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb129-2"><a href="projects-1.html#cb129-2" tabindex="-1"></a>url <span class="op">=</span> <span class="st">&quot;https://raw.githubusercontent.com/pkmklong/Breast-Cancer-Wisconsin-Diagnostic-DataSet/master/data.csv&quot;</span></span>
<span id="cb129-3"><a href="projects-1.html#cb129-3" tabindex="-1"></a>spark.sparkContext.addFile(url)</span>
<span id="cb129-4"><a href="projects-1.html#cb129-4" tabindex="-1"></a></span>
<span id="cb129-5"><a href="projects-1.html#cb129-5" tabindex="-1"></a>df <span class="op">=</span> spark.read.csv(SparkFiles.get(<span class="st">&quot;data.csv&quot;</span>), header<span class="op">=</span><span class="va">True</span>, inferSchema<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb129-6"><a href="projects-1.html#cb129-6" tabindex="-1"></a></span>
<span id="cb129-7"><a href="projects-1.html#cb129-7" tabindex="-1"></a><span class="co"># df.show()</span></span></code></pre></div>
<div class="sourceCode" id="cb130"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb130-1"><a href="projects-1.html#cb130-1" tabindex="-1"></a><span class="co"># Rename columns and map diagnosis to label</span></span>
<span id="cb130-2"><a href="projects-1.html#cb130-2" tabindex="-1"></a>columns <span class="op">=</span> [<span class="st">&#39;id&#39;</span>, <span class="st">&#39;diagnosis&#39;</span>] <span class="op">+</span> [<span class="ss">f&#39;feature_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">&#39;</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">32</span>)]</span>
<span id="cb130-3"><a href="projects-1.html#cb130-3" tabindex="-1"></a>data <span class="op">=</span> df.toDF(<span class="op">*</span>columns)</span>
<span id="cb130-4"><a href="projects-1.html#cb130-4" tabindex="-1"></a>data <span class="op">=</span> data.withColumn(<span class="st">&quot;label&quot;</span>, (data[<span class="st">&quot;diagnosis&quot;</span>] <span class="op">==</span> <span class="st">&quot;M&quot;</span>).cast(<span class="st">&quot;integer&quot;</span>)).drop(<span class="st">&quot;diagnosis&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb131"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb131-1"><a href="projects-1.html#cb131-1" tabindex="-1"></a><span class="co"># Assemble features into a single vector</span></span>
<span id="cb131-2"><a href="projects-1.html#cb131-2" tabindex="-1"></a>feature_columns <span class="op">=</span> [<span class="ss">f&#39;feature_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">&#39;</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">25</span>)]</span>
<span id="cb131-3"><a href="projects-1.html#cb131-3" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(inputCols<span class="op">=</span>feature_columns, outputCol<span class="op">=</span><span class="st">&quot;features&quot;</span>)</span>
<span id="cb131-4"><a href="projects-1.html#cb131-4" tabindex="-1"></a>data <span class="op">=</span> assembler.transform(data)</span></code></pre></div>
<div class="sourceCode" id="cb132"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb132-1"><a href="projects-1.html#cb132-1" tabindex="-1"></a><span class="co"># Split data into training and test sets</span></span>
<span id="cb132-2"><a href="projects-1.html#cb132-2" tabindex="-1"></a>train_data, test_data <span class="op">=</span> data.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb132-3"><a href="projects-1.html#cb132-3" tabindex="-1"></a></span>
<span id="cb132-4"><a href="projects-1.html#cb132-4" tabindex="-1"></a><span class="co"># Build the Logistic Regression model</span></span>
<span id="cb132-5"><a href="projects-1.html#cb132-5" tabindex="-1"></a>logistic_regression <span class="op">=</span> LogisticRegression(featuresCol<span class="op">=</span><span class="st">&quot;features&quot;</span>, labelCol<span class="op">=</span><span class="st">&quot;label&quot;</span>)</span>
<span id="cb132-6"><a href="projects-1.html#cb132-6" tabindex="-1"></a>model <span class="op">=</span> logistic_regression.fit(train_data)</span></code></pre></div>
<div class="sourceCode" id="cb133"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb133-1"><a href="projects-1.html#cb133-1" tabindex="-1"></a><span class="co"># Evaluate the model on test data</span></span>
<span id="cb133-2"><a href="projects-1.html#cb133-2" tabindex="-1"></a>predictions <span class="op">=</span> model.transform(test_data)</span></code></pre></div>
<div class="sourceCode" id="cb134"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb134-1"><a href="projects-1.html#cb134-1" tabindex="-1"></a><span class="co"># AUC-ROC</span></span>
<span id="cb134-2"><a href="projects-1.html#cb134-2" tabindex="-1"></a>evaluator <span class="op">=</span> BinaryClassificationEvaluator(rawPredictionCol<span class="op">=</span><span class="st">&quot;rawPrediction&quot;</span>, labelCol<span class="op">=</span><span class="st">&quot;label&quot;</span>)</span>
<span id="cb134-3"><a href="projects-1.html#cb134-3" tabindex="-1"></a>auc <span class="op">=</span> evaluator.evaluate(predictions)</span></code></pre></div>
<div class="sourceCode" id="cb135"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb135-1"><a href="projects-1.html#cb135-1" tabindex="-1"></a><span class="co"># Accuracy, Precision, and Recall</span></span>
<span id="cb135-2"><a href="projects-1.html#cb135-2" tabindex="-1"></a>multi_evaluator <span class="op">=</span> MulticlassClassificationEvaluator(labelCol<span class="op">=</span><span class="st">&quot;label&quot;</span>, predictionCol<span class="op">=</span><span class="st">&quot;prediction&quot;</span>)</span>
<span id="cb135-3"><a href="projects-1.html#cb135-3" tabindex="-1"></a>accuracy <span class="op">=</span> multi_evaluator.evaluate(predictions, {multi_evaluator.metricName: <span class="st">&quot;accuracy&quot;</span>})</span>
<span id="cb135-4"><a href="projects-1.html#cb135-4" tabindex="-1"></a>precision <span class="op">=</span> multi_evaluator.evaluate(predictions, {multi_evaluator.metricName: <span class="st">&quot;weightedPrecision&quot;</span>})</span>
<span id="cb135-5"><a href="projects-1.html#cb135-5" tabindex="-1"></a>recall <span class="op">=</span> multi_evaluator.evaluate(predictions, {multi_evaluator.metricName: <span class="st">&quot;weightedRecall&quot;</span>})</span>
<span id="cb135-6"><a href="projects-1.html#cb135-6" tabindex="-1"></a></span>
<span id="cb135-7"><a href="projects-1.html#cb135-7" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;AUC-ROC: </span><span class="sc">{</span>auc<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## AUC-ROC: 0.9989</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb137-1"><a href="projects-1.html#cb137-1" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Accuracy: </span><span class="sc">{</span>accuracy<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## Accuracy: 0.9651</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb139-1"><a href="projects-1.html#cb139-1" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Precision: </span><span class="sc">{</span>precision<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## Precision: 0.9653</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb141-1"><a href="projects-1.html#cb141-1" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Recall: </span><span class="sc">{</span>recall<span class="sc">:.4f}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<pre><code>## Recall: 0.9651</code></pre>


</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="preface-1.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/index.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Project_Archive.pdf", "Project_Archive.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
